### ISSUE TITLE
Not Getting Some Notifications in Telegram-FOSS 3.10.1

### ISSUE THREAD

**Issue by landry314** [Telegram-FOSS-Team/Telegram-FOSS#110]
Since I installed Telegram-FOSS 3.10.1 I am not getting some incoming notifications. I scroll down to find messages I have not read but which have been marked as read. This is happening a lot. I have not yet seen a pattern to why certain messsages are not being marked as new and not providing notifications but I will update this issue as I get more info.

**Comment by vanitasvitae** [comment]
I can confirm this. I  have to open the app to get Notifications.

**Comment by landry314** [comment]
This seems to happen when I open the app, it connects, and get a bunch of messages at once. Many are not marked as unread. It doesn't send notifications because I am online but it should be marking them as unread.

**Comment by landry314** [comment]
I think not having Google Play Services is causing this. Telegram help told me it is required for "reliable notifications".

**Comment by vanitasvitae** [comment]
@landry314: Since this is an unofficial fork answers of Telegram help won't help you much.

This is a FOSS oriented build and Google Play dependencies were removed to make Telegram work with devices without GCM. That worked well on earlier versions.

I guess there went something wrong when merging upstream changes. I saw that a class with AlarmService in its name has been removed. Maybe that causes an error now?

**Comment by Bubu** [comment]
I don't seem to have this problem. My notifications have all triggered thus far.

What are you settings for background connection and keep alive service.

I on the other hand this sounds like a problem we had earlier where the build id information wasn't incremented correctly.

**Comment by vanitasvitae** [comment]
I had "Background connection" on and "Keep-alive-service" off.

**Comment by Bubu** [comment]
That might be a problem of the upgrade process. Please try to set it both to on.

**Comment by landry314** [comment]
I have both "Background connection" on and "Keep-alive-service" on and I still have the problem occasionally. I do NOT have Google Play Services and I am using Cyanogenmod 11.

**Comment by vanitasvitae** [comment]
I guess, setting both toggles to "on" fixed the issue for me. I'll monitor that though.

**Comment by Bubu** [comment]
I have the same configuration and it works for me. I did a clean reinstall though, we had problems with that before.

Could you test that? (You will lose all secret chat data and settings)

**Comment by slp** [comment]
I've updated the internal build number, but as we jumped over some versions, this could still be a problem. As @Bubu suggests, doing a clean reinstall is your best option.

That said, we discovered some time ago that some combinations of devices and Android versions have trouble waking up from deep sleep, even when using RTC AlarmServices.

**Comment by mastad0n** [comment]
I can confirm I am still having this issue in 3.10.1 (821).
Background connection and Keep-alive-service are both on.
I don't have Google Play Services.

**Comment by kiwiASRALL** [comment]
Same here. 

Maybe 3.13 will fix it.

**Comment by Bubu** [comment]
Any changes with version 3.13? Otherwise if a clean reainstall does not work, this Problem might not be solvable for you (As slp mentioned earlier.).

**Comment by landry314** [comment]
yes, i have the same problems even with the play store version of telegram and no gapps on cyanogenmod 11... also, whatsapp has the same problems with telegram, but for me whatsapp is no having this problem much more and telegram is doing well.

i wonder if the use of this will solve the problem: https://github.com/microg/android_packages_apps_GmsCore/wiki

i will install this on my new phone and see. anyone else want to try? it is probably the lack of google push which is causing poor notifications... not sure if cyanogenmod 13 would be better.

**Comment by vanitasvitae** [comment]
I have to say it is working nicely for me on CopperheadOS (no GCM and or replacements), both on Nexus 5 and 6p.

**Comment by N-ik05** [comment]
@landry314 does whatsapp work better or worse than telegram?

For me Telegram notifications seem to work better.

**Comment by landry314** [comment]
yes, sorry, i edited my comment to be clearer. telegram does work better for me now. whatsapp sometimes just fails to notify until i open it. for both apps it must be the lack of google push running in the background and the other push systems not running properly in the background too... like i said, i will let you know in a week or so if cm13 with gmscore solves this...

**Comment by N-ik05** [comment]
@landry314 nut @vanitasvitae says he isn't using any replacements and its working fine. And both have their standalone push services.

Is there someone that knows how to debug this?

**Comment by N-ik05** [comment]
Looks indeed that this is a problem in Cyanogenmod 13 bacon. I tried Paranoid Android(Also without Gapps) and it seems I do not have any problems now.
