### ISSUE TITLE
Not Delivering Notifications for an Open Conversation While Phone is Sleeping

### ISSUE THREAD

**Issue by landry314** [Telegram-FOSS-Team/Telegram-FOSS#111]
If you have a conversation open in Telegram then put the phone to sleep right there with that conversation left in the foreground then you wont get new notifications for that conversation because Telegram thinks you are currently reading the new messages. I have to always back out to the conversation list before putting the phone to sleep to avoid this problem.

I guess Telegram is assuming I already saw the messages because the conversation is open so it doesnt notify me. This is how it works when the phone is not sleeping so maybe the sleeping awareness is the issue.

I have all the in-app notification and reliable notification settings turned on.

I informed Telegram of this and they said it is probably due to not having Google Play Services installed. That is why I am posting it here because Telegram-FOSS bypasses the need for Google Play Services and so maybe it can also fix this issue, I don't know. Anyone have any ideas?

I am using Cyanogenmod 11 without Google Play Services.

**Comment by vanitasvitae** [comment]
I can't confirm this. Works fine on my phone. Still experiencing #110 though.
