### ISSUE TITLE
Location doesn't really work

### ISSUE THREAD

**Issue by Salkin2** [Telegram-FOSS-Team/Telegram-FOSS#121]
When I try to share mi location I get this message:
![screenshot_tg](https://cloud.githubusercontent.com/assets/21989310/20069925/cd3dc1c8-a51e-11e6-92b2-ffbf81e0f67c.png)

I have Osmand installed, but having to open Osmand and sharing my location from it it's noy only far from optimal and handy but the worst is that it doesn't work either, at least doesn't work as well as desired; I mean, even if I close TG's window, open my launcher and launch Osmand, wait for the map to load and then I share my location with my interlocutor, there's no Osmand preview of my location on the chat windows but just a web link to my location map on the Osmand maps website (so the interlocutor needs to wait for his browser to open and load Osmand's site) and some geographic coordinates which Telegram can't interpret so they appear as plain text like "Location: geo:xx.xxxx,y.yyyyy?z=nn" but you can't tap on it for your maps app (Osmand in my case) to show it and set it as destination for a GPS guided trip.
Couldn't be done two things?:
- Show a small preview from Osmand maps website, or from Openstreemap's, or whatever open sourced maps platform you like, the same way the official app takes one from Gmaps. Many times we just need a slight idea of where is that bar, shop, wahtever we want to go and don't even open the location link, the image is enough.
- Use a "format" or whatever is called, for the geographic coordinates that are comprehensible by maps apps like Osmand, Maps.me, and similar OSS projects based on OSM, so if I need to use GPS to reach a location I can just tap on it for Osmand to load it.

I'm now informed that the purpose of this project is not adding features over the official client, but since this "bug" is due to the effort to liberate Telegram from Google's claws it probably needs a couple of features that the official client lacks, IMHO.

**Comment by Bubu** [comment]
This is indeed a bug, you should get a clickable preview of a google maps render. This worked in previous version and somehow broke (again) during the merge. (It doesn't work for me either.)

I will have to take a look at this.

**Comment by Bubu** [comment]
Re: the picture you posted:
Sharing a location from Telegram directly would require integrating a replacement for the google maps framework. (As you normally don't want to share 'your' location but 'some' location.)

There is https://github.com/osmdroid/osmdroid but someone would need to integrate (and maintain this.)
So sharing a location from OSMAnd to Telgram is the best we can get for now.
