### ISSUE TITLE
Telegram 3.18.0 source code!

### ISSUE THREAD

**Issue by mastad0n** [Telegram-FOSS-Team/Telegram-FOSS#131]
Looks like its updated :+1: :tada:

https://github.com/DrKLO/Telegram

Pavel Durov tweet: https://twitter.com/durov/status/847454485882355713

Telegram 3.18 blog: https://telegram.org/blog/calls

:tada:

**Comment by danialbehzadi** [comment]
Nice. Seems they decided to make it free software again.

**Comment by user1831** [comment]
Please start working on it! We had to wait so long...

**Comment by thermatk** [comment]
Trying to remember how my emoji generator works :+1: 
will send a PR probably if and when I do :)

**Comment by thermatk** [comment]
Emojis are ready
https://github.com/thermatk/TelegramEmojiGenerator/tree/master/workfiles/ready

**Comment by user1831** [comment]
Since 3.13 a lot of features have been included into Telegram. How long will it take to finish 3.18 of the FOSS version? It would be quite nice to get 3.18 from F-Droid soon!

**Comment by thermatk** [comment]
https://github.com/slp/Telegram-FOSS/pull/132
done :)

**Comment by iamale** [comment]
Anything else needs to be done here?
Anything a simple human being with almost no experience in mobile dev could help with?

**Comment by Bubu** [comment]
@iamale well it's probably not that complicated to merge the changes but it will take at least a few hours of work.

What I'm more concerned about is the fact that nobody is realistically able to do any code review on this on giant commit. At least it would take ages.

This project is supposed to be a privacy friendly version of telegram. We don't yet know what changed in this regard.

So what do we do? Release an unvetted version ass soon as possible and look at the privacy implications in the weeks to come? Or do we carefully look at all new code first and release a new version much later?

I can take a first look at what's needed to build the new version tomorrow night.

**Comment by Matttter** [comment]
I would say get it merged asap, and put an apk somewhere in the comments here, but not a release, so people who really want it can download it. Then review the code superficially, then do a release with a disclaimer, then continue reviewing code in more detail and remove the disclaimer? I'm maybe overthinking this

**Comment by user1831** [comment]
An apk file which is not signed by F-Droid will not be able to get installed on a device the F-Droid version is installed on. The user would have to reinstall Telegram. That's not quite nice! Of course with root you could backup the application data previously, but what about devices without root?

**Comment by danialbehzadi** [comment]
Telegram stores data on it's server. So you only loose secret chats by
reinstalling it.

**Comment by user1831** [comment]
I think a code review is absolutely mandatory but we have to provide the latest version of Telegram otherwise the gap between the official version and the F-Droid version is too wide. I would suggest to publish FOSS 3.18 on F-Droid very soon and do the code review afterwards. Of course an info about the missing review should be added, for instance to the repo. We cannot continue preventing any progess as @DrKLO did the whole time. We have to enable our users to use an apk directly build from the source code as soon as we can! FOSS means Free and open-source software, an audit is not necessarily needed. It's an additional feature and has to wait.

**Comment by thermatk** [comment]
What I see are two new dependencies:

- https://github.com/stripe/stripe-android in build.gradle, seems to be ok and not having additional dependencies of its own
- https://github.com/grishka/libtgvoip as a gitmodule

Ignoring assets, drawables and deletions(those shouldn't be important to review for privacy reasons), there are:

-  512 files changed, 57189 insertions, 28801 deletions
-  451 new file, 108750 insertions

A big part of the patch is actually the migration from exoplayer to exoplayer2 - 372 new files I believe. Mostly, it's the original Google's source code, but with changed package names.

Guys, who else is digging in review, let's divide it somehow. I'll continue crossing out exoplayer for now, diff's will follow

**Comment by thermatk** [comment]
My proposal is to merge it in parts and to actually do the review, in the end it will be less shocking. 

1. Merge assets, drawables, layouts and strings immediately
2. Do the deletions immediately
3. Merge the updated embedded dependencies 1by1, it's not just exoplayer, but also opus and some others
4. What will be left one could just skim through for now, but at least it should be a separate commit for anyone to easily dive in further in the future

**Comment by Matttter** [comment]
I don't think merging the deletions immediately without review is a good plan, deletions could do nefarious stuff as well.

**Comment by thermatk** [comment]
@Matttter how? Under the assumption that the previous source code was kind of known-to-be-ok, what could go wrong if some parts of it are deleted?
I'm having fun with it in my fork, anyway a bunch of separated commits will be a lot better then nothing
https://github.com/thermatk/Telegram-FOSS/commits/master

**Comment by Matttter** [comment]
```
{
do normal things       <--- not bad
other normal things  <--- not bad
more normal things   <--- not bad
}
if (user_press_bug_report_button){
send all the info to the overlords    <--- not bad, requires user agreement
}
```

Could be made into :
```
{
do normal things       <--- not bad
other normal things  <--- not bad
more normal things   <--- not bad

```
~~}
if (user_press_bug_report_button){~~
```

send all the info to the overlords    <--- really bad
}
```

Something like this, I would say. I have to say, I don't know very much about how the Telegram app works, so I'm just putting on my paranoid hat here

**Comment by thermatk** [comment]
I'm finished with what seemed to be the easy part, added a [REVIEW] to the commit one should pay attention to then.

**Comment by Bubu** [comment]
@thermatk very good suggestion in merging this step by step. But I agree we need to pay attention to the deletions too. 

And thanks for starting to look into the code.

**Comment by thermatk** [comment]
if it makes life easier, use this branch:
https://github.com/thermatk/Telegram-FOSS/commits/original3.13-to-3.18
It goes from upstream 3.13 and 3.18, but I've crossed out everything that one shouldn't check for malicious code. Everything else is still pretty big, but split into several commits with "[REVIEW]". As I'm not a security guy, I don't know if there's anything else I can do.

**Comment by Matttter** [comment]
These commits are so huge that it's nearly impossible to see them on github.com on my laptop. Even on my desktop I have to let it sit for 5 minutes to be able to scroll... If only they would develop in the open, or at least push all the separate commits to the repo instead of making one giant one. This just isn't behaviour compatible with what free software is about for me: trust and transparency.

**Comment by thermatk** [comment]
Soooooo

- In the branch https://github.com/thermatk/Telegram-FOSS/commits/3.18-to-3.18-foss I have implemented all your changes to the code of v3.13, excluding leftovers, on top of my 3.13-3.18 branch.
- The only thing i didn't touch is the jni where your boringssl->openssl things and replacing prebuilts with new builds(as far as I understood what is done there) are. There is a new library there, the git-moduled one, so i'm not sure what to do with this
- My FOSSed version works cool for me as it is, except for... calls are throwing an FC! It was like the only reason for v3.18 existence :-1: I didn't touch anything VoIP related, so I don't know what to do

**Comment by thermatk** [comment]
Ah, ok, i know why :) the jni thing! They only provide native prebuilts for armv7, and my emulator was x86

everything except jni is done then

**Comment by Matttter** [comment]
I'd love to test it on a real phone if you want. Just put up an apk for me to test out

**Comment by thermatk** [comment]
there you go, as it is a debug build you can install it alongside the usual app
https://github.com/thermatk/Telegram-FOSS/releases/tag/3.18FOSS-BETA
everything works as expected for me

**Comment by Matttter** [comment]
Yup works great, have a couple of questions about this. The "call quality" rating after a call, where does that go? It should be removed IMO in the FOSS build.

Is the call connection p2p or does it go through the server? (probably doesn't matter now that I think about it, encryption and stuff)

**Comment by thermatk** [comment]
@Matttter This call quality thing must be in the [REVIEW] parts, I didn't do anything new in this sense except merging previous patches.

**Comment by Matttter** [comment]
Ok, thought so. I hope someone into the native stuff gives us a hand here

**Comment by thermatk** [comment]
@Matttter 
Actually, I would be strongly against the removal of the call quality rating, but IFF (if and only if) it is implemented in the right way. For example, I didn't remove Giphy search either, because I don't see how harmful a network request done with the open source code provided can be, when you should explicitly go and tap "Search Giphy" for it to do something.

Let this really be about privacy and FOSS, optional features properly implemented upstream(not doing anything in a shady way without explicit click) shouldn't really be touched, because why??? :+1: Bing is gone, because of API key.

**Comment by Bubu** [comment]
@Matttter Re: p2p vs server: https://telegram.org/blog/calls#super-fast

**Comment by thermatk** [comment]
@Bubu @Matttter a cool and easy feature to do would be to show whether current call is p2p or server, maybe just add a one-liner toast :)

**Comment by Bubu** [comment]
@thermatk Thanks for all the work! Can you open Pull Requests against this repo with the changes I should merge into this repo?

**Comment by thermatk** [comment]
@Bubu be careful what you wish for :+1: 
https://github.com/slp/Telegram-FOSS/pull/133
my browser couldn't handle the pull request edit page until i disabled JS :)

**Comment by Bubu** [comment]
As a first step I just updated openssl to 1.0.2k. Openssl 1.0.1 is no longer maintained and we need openssl to properly build in fdroid. So this was a required step anyway.

I'll continue tomorrow, working through the changes.

**Comment by Bubu** [comment]
Can someone maybe gather up all the changelog entries from the intermediate releases?

@iamale @Matttter Ping.

**Comment by mastad0n** [comment]
Not sure if this is what you mean @Bubu 

What's New in Telegram v3.18.0 

+ v 3.18
+ Telegram Calls are here: secure, crystal-clear, constantly improved by artificial intelligence. We are rolling them out in Europe today, the rest of the world will get calls within a few days.
+ Choose between 5 grades of video compression and preview the quality of your video before you send it.

What's New in Telegram v3.17.1 

+ v 3.17
+ Use custom themes to change the appearance of the app.
+ Check out the new dark theme in Settings > Themes. See the @themes channel for more ideas.
+ Create your own themes using the new built-in editor.


What's New in Telegram v3.17.0 

+ v 3.17
+ Use custom themes to change the appearance of the app.
+ Check out the new dark theme in Settings > Themes. See the @themes channel for more ideas.
+ Create your own themes using the new built-in editor.


What's New in Telegram v3.16.1 

+ v. 3.16
+ Delete recently sent messages for everyone.
+ Network Usage in 'Data and Storage' Settings.
+ App remembers scroll position when switching to another chat and back.
+ Messages from one sender are grouped together.
+ Added a floating date to the top of the screen when scrolling.
+ Recently downloaded files are shown when sharing a file.
+ Report spam from Secret chats.
+ Send GIFs directly from Gboard.
+ Android 7.1: Added fast action menu to home screen.


What's New in Telegram v3.16.0 

+ v. 3.16
+ Delete recently sent messages for everyone.
+ Network Usage in 'Data and Storage' Settings.
+ App remembers scroll position when switching to another chat and back.
+ Messages from one sender are grouped together.
+ Added a floating date to the top of the screen when scrolling.
+ Recently downloaded files are shown when sharing a file.
+ Report spam from Secret chats.
+ Send GIFs directly from Gboard.
+ Android 7.1: Added fast action menu to home screen.


What's New in Telegram v3.15.0 

+ v. 3.15
+ Pin important chats to the top of the list so that you never miss a new message.
+ Link your Telegram account with hundreds of services like Twitter, Instagram, Spotify, Gmail, and others. Control apps via Telegram, or get messages when something happens. Talk to @IFTTT to set up.
+ Rotate photos by any number of degrees in the photo editor.
+ View YouTube and Vimeo in Picture-in-Picture mode.


What's New in Telegram v3.14.0 

+ v. 3.14
+ Instant View for Medium articles and some other sites. No more waiting for the pages to load!
+ ‘Groups in common’ in user profiles.
+ ‘Jump to date’ in message search.
+ 'View Pack' for recent stickers.
+ Setting a passcode now hides your chats from the task-switcher.
+ Improved camera speed, video compression.
+ Improved interfaces.
+ Also introducing telegra.ph, a new publishing platform. You can now use telegra.ph to publish articles – it’s clean, simple and efficient.


What's New in Telegram v3.13.2 

+ v. 3.13
+ Major update to Telegram's Bot Platform: Bots can now offer you rich HTML5 experiences, like games.
+ Check out @gamebot for examples of what's coming.
+ You can use these bots in inline mode in any of your chats to share a game and compete with friends.
+ All games are loaded as ordinary web pages, so this update won't add a single byte to the size of our apps.
+ Added many small improvements to the sticker panel.


What's New in Telegram v3.13.1 

+ v. 3.13
+ Major update to Telegram's Bot Platform: Bots can now offer you rich HTML5 experiences, like games.
+ Check out @gamebot for examples of what's coming.
+ You can use these bots in inline mode in any of your chats to share a game and compete with friends.
+ All games are loaded as ordinary web pages, so this update won't add a single byte to the size of our apps.
+ Added many small improvements to the sticker panel.


What's New in Telegram v3.13.0 

v. 3.13

 Major update to Telegram's Bot Platform: Bots can now offer you rich HTML5 experiences, like games.
+ Check out @gamebot for examples of what's coming.
+ You can use these bots in inline mode in any of your chats to share a game and compete with friends.
+ All games are loaded as ordinary web pages, so this update won't add a single byte to the size of our apps.
+ Added many small improvements to the sticker panel.

**Comment by thermatk** [comment]
@Bubu @mastad0n 
https://github.com/slp/Telegram-FOSS/pull/135

**Comment by Bubu** [comment]
@mastad0n @thermatk Merged, thanks.

**Comment by thermatk** [comment]
@Bubu as far as i can see from jni/, the sources for libWebRtcAec library are not there. The original webrtc sources are here: https://chromium.googlesource.com/external/webrtc/+/master/webrtc

Yet I don't understand how to get from this to libWebRtcAec, and it seems that some source files have to be edited for that to happen, as the header files here are edited compared to upstream
https://github.com/grishka/libtgvoip/tree/public/external/include/webrtc

As per last comment in https://github.com/grishka/libtgvoip/issues/1 , the developer is aware of missing sources for the libraries and had the intention of uploading them, 29 days ago :+1: I'm opening a bug upstream

**Comment by thermatk** [comment]
Ok
@Bubu https://github.com/slp/Telegram-FOSS/pull/136 is done
The missing libwebrtcaec sources will be there this week, as promised by the upstream developer in response to my request

**Comment by Bubu** [comment]
@thermatk @others What do you say about the SmsListener + related capability? I find that feature actually useful and we can check the code is doing nothing nefarious.

Do we add it back?

**Comment by thermatk** [comment]
@Bubu I would add it back, since compared to some other messengers it still gives you the option to fill in the code manually :) This is important to me, since I frequently use Telegram on a smartphone with a different sim.
It's just a speed-up. 
Reviewing the code gives us just one entry point, SmsListener.java, which forwards the text using `NotificationCenter.didReceiveSmsCode` . There are 20 usages of this notification, all of which seem legit to me, in 3 files:

- org/telegram/ui/CancelAccountDeletionActivity.java
- org/telegram/ui/ChangePhoneActivity.java
- org/telegram/ui/LoginActivity.java

The sms messages don't seem to be transferred to some shady internet service :+1:

**Comment by Matttter** [comment]
Yup I agree with this, if it does not send stuff to our corporate overlords I would think it's a useful feature.

**Comment by thermatk** [comment]
Accept #138 and then #137 
Only the libwebrtcaec will be remaining, but it doesn't depend on us.

**Comment by user1831** [comment]
The sources were uploaded!

**Comment by thermatk** [comment]
If someone wants to play with it, with the latest sources compiled and included in #138 , here is the arm sdk23+ debug apk:

[armv7_SDK23-debug.apk.zip](https://github.com/slp/Telegram-FOSS/files/909487/armv7_SDK23-debug.apk.zip)

Since it's a debug build, you can install it alongside usual Telegram and it will have the name "Telegram Beta". Calls are working fine here :+1:

**Comment by vn971** [comment]
Does the current Telegram server API allow receiving a confirmation code NOT through SMS? The desktop version and the previous FOSS mobile version allowed to receive the code on older instances of telegram, without the use of SMS at all.
Can we do that for the latest version? The new UI freezes when trying to confirm my code, and nothing is being sent to my other (already connected) devices.

**Comment by vn971** [comment]
This actually is kind of an **issue** for me, because I do not really have the SIM I've registered with anymore. Whenever I connected a new device I've send a code received by my other devices.

**Comment by thermatk** [comment]
@vn971 it does, although it chooses kind of randomly between sending to other devices, calling and sms.
You can force it to send the code to other device with higher probability if you take out the sim for the time you set up the app

**Comment by jooola** [comment]
@vn971 I had a similar issue so i don't know if this trick will help you.
But try to kill all "old unused sessions" in your current session and try to reconnect your device.

Beware not to remove "used sessions" since you don't have you SIM wich is needed for the first connection !

**Comment by vn971** [comment]
UPD: sorry, I had a local misconfiguration (the app did not have internet access). Edited the message above.

**Comment by Luca1991** [comment]
@thermatk I've tested your apk for the last 8 hours without any issue. Only the sms auto-detection haven't worked for me. Nice job, colleague, a beer for you.

**Comment by user1831** [comment]
@thermatk Good job indeed! I also experienced no issues while using your apk.

**Comment by mastad0n** [comment]
Works perfect! No issues here either! Thank you @thermatk !!

**Comment by Matttter** [comment]
Yup fine with me too! Let's get this on F-Droid I would say :)

**Comment by user1831** [comment]
Great idea! What are we currently waiting for?

**Comment by vn971** [comment]
@user1831 completing the review probably? After all, this should be a FOSS version.
(I'm not a maintainer.)

**Comment by thermatk** [comment]
@Bubu or @slp are managing this
 
If someone can review all the commits with [REVIEW] in #137 and #138 and tell us what's happening there, it will be beneficial too. If you find a vulnerability, don't forget to apply for the Telegram bounty program :rofl:

**Comment by vn971** [comment]
@thermatk BTW, do all devices have armv7 already? I'm trying to install the last published version on my old devices, and it doesn't work somehow. It says "there was a problem parsing the package". I do have "install from unknown sources" enabled.

**Comment by jooola** [comment]
Try to rename the apk to telegram.apk and install again .

One more time i'm absolutly not sure about this trick !

**Comment by thermatk** [comment]
@vn971 armv6 I haven't seen for six years or so. The thing is, this is for sdk 23+, which you probably don't have unless you use a custom ROM
I can compile all possible apks, but it would be better if this gets merged and f-droid compiles them signed with proper keys, etc.

**Comment by thermatk** [comment]
It looks like the Telegram source code includes a contagious disease that first made the original author hide for six months and now got our maintainers :rofl:

**Comment by mastad0n** [comment]
@Bubu @slp help needed!

**Comment by slp** [comment]
Hi all,

As I already hinted before, I'm no longer interested in maintaining this FOSS version of Telegram. These are my reasons:

1. Lack of time. 
2. Upstream maintains its extremely hostile development model.
3. I'm _really_ concerned about Telegram's purpose as an organization.
4. There are better alternatives, some fully FOSS and federated (like Matrix/Riot), some with PFS encryption (like Signal).
5. As a consequence of 2, 3 and 4, I'm no longer using Telegram for my personal communication needs.

If someone (@thermatk ?) wants to take over the work, I'll give him/her full access to this repo. If someone wants the job but prefers to use his/her own repo, I'll sponsor the switch on FDroid.

**Comment by Peque** [comment]
@slp Thanks for all your hard work during this period. Wish you the best.

**Comment by thermatk** [comment]
I would rather do this as part of a team, maybe it's time to transfer the repo to a Github organization and call for more people? I don't know much about native code and with every release this part is growing
And I think @Bubu is still around, he's just missing for a few days, so two people in the org already probably :+1: 
Who is in?

**Comment by thermatk** [comment]
@slp you can transfer the repo here then
https://github.com/Telegram-FOSS-Team
and we'll try to find a solution :)

**Comment by mastad0n** [comment]
@slp Thank you for everything!

@thermatk great idea!

**Comment by thermatk** [comment]
When the repo is transferred, I'll merge everything and push change to metadata on F-Droid. Shouldn't be hard

**Comment by thermatk** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/2190

**Comment by vn971** [comment]
The PR was merged, waiting for it to build.

**Comment by picsi** [comment]
is this real life/

**Comment by thermatk** [comment]
While it's not built, if someone knows how to do myLocationOverlay properly on osmdroid, please do it :)
#139 
it works, but I want full feature parity and beauty... which is really close, but not there yet
There you go with the latest debug apk:

[TMessagesProj-fat-debug.apk.zip](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/files/935078/TMessagesProj-fat-debug.apk.zip)

**Comment by mastad0n** [comment]
@thermatk seems like something went wrong :(

![org telegram messenger_-_f-droid_-_2017-04-19_16 24 51](https://cloud.githubusercontent.com/assets/20113301/25206442/c6bded9a-251c-11e7-89a9-eeadd0ad5c78.png)

https://f-droid.org/wiki/page/org.telegram.messenger

**Comment by iamale** [comment]
The build log is missing though? Strange.

**Comment by mastad0n** [comment]
@iamale @thermatk I made a Issue:

https://gitlab.com/fdroid/fdroiddata/issues/702

**Comment by thermatk** [comment]
The lastbuild page shows nothing after November, maybe it just means it has recognized the change in metadata and will try to build some time later? 🤔

**Comment by thermatk** [comment]
Yup, I checked with other apps. I think that it has never tried to build, everything should be ok, it's a step in the right direction 😉

**Comment by thermatk** [comment]
Now they have a problem with the build server, maybe next iteration is our big chance :+1: 
https://f-droid.org/wiki/page/org.telegram.messenger/lastbuild_9575

**Comment by mastad0n** [comment]
Thanks for the update @thermatk and for your hard work in this repo!

**Comment by thermatk** [comment]
Ok, now it really fails. Have no idea why yet :cry:

**Comment by thermatk** [comment]
I've tried it from scratch starting with git clone, no issues:
https://pastebin.com/xXYvFvgL

**Comment by mastad0n** [comment]
@thermatk 

I think they are telling us it has to do with their build server, but I'm not sure:

https://gitlab.com/fdroid/fdroiddata/issues/702

**Comment by thermatk** [comment]
I have a theory: I use ndk r14, build-server uses r12b
https://gitlab.com/fdroid/fdroiddata/merge_requests/2199
We really need someone who understands all those native code games :+1:

**Comment by vn971** [comment]
@thermatk can't this be the reason why I couldn't install telegram-beta on my old devices (Samsung Galaxy S3, Samsung Galaxy Note 8.0) ? IDK actually, just guessing.

**Comment by mastad0n** [comment]
@thermatk 

I think your merge request is working!

https://gitlab.com/fdroid/fdroiddata/commit/4810c4163bc252305fd92eeadeaee21e5f65f6e8


> Boris Kraut @krt commented about 2 hours ago
> 
> Yep, builds for me, thanks.

**Comment by kitsunyan** [comment]
@vn971 do you have installed APK on these devices? The certificates won't match in this case.

If you sure in this, try to install using adb (`adb install -r TMessagesProj-fat-debug.apk`), it will show you error mesage.
You also can try to use logcat. There should be messages tagged `PackageManager` or `PackageInstall` with error explanation.

**Comment by user1831** [comment]
Why does it take so long to build Telegram on F-Droid? The process until it's finally ready to use is so time-consuming and annoying... Already 26 days have elapsed since the source code were uploaded, the next version is going to be published in the next days...

**Comment by thermatk** [comment]
@user1831 the build server of F-Droid did not run since the 23rd, same delays happened after initial merge: they have some known issues with it.
But most of the time was spent because there was no one managing the project, so even when I did and redid the pull requests merging everything in three different variations with @Bubu coming and rethinking the structure and approach, nothing actually happened :rofl: 
And then @Bubu vanished as well in the process
I am open to PRs, so next time don't forget to contribute even if I'm busy with something :+1:

**Comment by thermatk** [comment]
It's over! :raised_hands: 
https://f-droid.org/wiki/page/org.telegram.messenger/lastbuild_9575

**Comment by Matttter** [comment]
Awesome! Party time :)

**Comment by mastad0n** [comment]
It's Christmas :smiley:

**Comment by user1831** [comment]
Don't rejoice too quickly, the APK is still not online! I'm fed up with waiting, which problem will occur next?! I think @slp is absolutely right with using alternatives to Telegram because it's no more user-friendly and maybe it has never been. Nevertheless, thanks for your work, you're doing a great job!

Hopefully, anyone will develop a **good** messenger at any time and there will be no need for a FOSS version because the original version matches this feature. Maybe I'm still alive when it happens.

**Comment by jooola** [comment]
> Hopefully, anyone will develop a good messenger at any time and there will be no need for a FOSS version because the original version matches this feature. Maybe I'm still alive when it happens.

Maybe if you give [Wire](https://wire.com/en/) a try !

**Comment by vn971** [comment]
@jooola as much as we want, I think we should refrain from discussing offtopics in this ticket.

**Comment by danialbehzadi** [comment]
> Hopefully, anyone will develop a good messenger at any time and there will be no need for a FOSS version because the original version matches this feature. Maybe I'm still alive when it happens.

What about [GNU Ring](https://ring.cx/)? it is completely GPLv3 free software, p2p with e2e encryption.

**Comment by thermatk** [comment]
@user1831 someday the developer of upstream app will change, because I have a feeling it's his personal opinion about open source, github, etc., that is affecting the source code releases. [The desktop client repo](https://github.com/telegramdesktop/tdesktop) is very much alive.
All the updated apps are to be signed and uploaded at once sometime this week,

@jooola just FYI, Wire, apart from having ~0 users, is not on F-Droid and you can't even be sure it will ever be, issue https://github.com/wireapp/wire-android/issues/5 is there since summer.
In my opinion, Telegram is still, to my own surprise, the only IM with a fully functional FOSS client and a lot of users at the same time. Luckily, in the world of end-to-end encryption the FOSS client is the required minimum to feel safe.
Signal only works as a gms-dependent apk signed by moxie, an attempt to make a compatible FOSS fork(just like ours!) talking to the same server resulted in [moxie "being not OK"](https://github.com/LibreSignal/LibreSignal/issues/37#issuecomment-217211165). For some months, Signal supports installation on devices without gms, but drains battery.
Riot has no users and functionality is different, I think. The future looks bright, as always.

I'll continue to support Telegram then, even if it means getting bleeding-edge functionality a month later :D

This has become a broad discussion topic a long time ago, I've even invented the blue label for it :rofl:

**Comment by jooola** [comment]
> @jooola just FYI, Wire, apart from having ~0 users, is not on F-Droid and you can't even be sure it will ever be, issue wireapp/wire-android#5 is there since summer.

Current ticket is [wireapp/wire-android/issues/233](https://github.com/wireapp/wire-android/issues/233).
But yeah, i still don't really use/know Wire and I didn't found better but @user1831 juste did ! Ring looks promising ! Still Wire is slowly on his way to the FOSS light. (only bad thing could be "Many employees working on Wire have previously worked with Skype, and Skype's co-founder Janus Friis is backing the project." Wikipédia)

> In my opinion, Telegram is still, to my own surprise, the only IM with a fully functional FOSS client and a lot of users at the same time.

👍

**Comment by mastad0n** [comment]
For me personally, every messenger has its issues. So far telegram has been stable, e2e (secret chats), easy to use, and like @thermatk said, one day upstream might see improvement. 

I tried Antox, Wire, Conversations, Ring, Riot and yet, I keep coming back to Telegram. It's not perfect, but its what works for me.

- Antox drains battery and data
- Riot is not really what I'm looking for, maybe good when working with a team though.
- Wire worried me [link](https://medium.com/@pepelephew/how-to-intercept-all-wire-voice-and-video-calls-13da1246675c) and I don't like the interface.
- Conversations doesn't handle mobile data -> wifi switching as good as Telegram (lots of missed notifications)
- Ring is alpha and drained my battery

This is just my experience, I'm personally happy this build is now working. Thanks again for all the hard work!

**Comment by Matttter** [comment]
What about Matrix? Doesn't that work yet?

**Comment by iamale** [comment]
@Matttter Riot is a Matrix client. It does work, but is a bit unstable right now (also, it looks like Slack, which is probably why @mastad0n thinks it is made for team chats (which is probably right)). Maybe a separate, more Telegram-ish Matrix client could be made, although this is a duplication of efforts IMO.

**Comment by iamale** [comment]
Has anybody tried [Actor](https://github.com/actorapp/actor-platform) though? It builds up on Telegram's legacy and looks almost identical, but has open-source server in addition to the clients. It isn't a federation, though, if I'm not mistaken (so it's impractical to run your own server if you don't want to set up a secret team or something like that).

**Comment by jooola** [comment]
> Has anybody tried Actor though? It builds up on Telegram's legacy and looks almost identical, but has open-source server in addition to the clients. It isn't a federation, though, if I'm not mistaken (so it's impractical to run your own server if you don't want to set up a secret team or something like that).

Looks like a great app too ! But app isn't aviable on fdroid and currently the website is down.
I installed it and I couldn't register ( maybe because I don't have the Google Service Framework (GSF) installed). Sad...

**Comment by iamale** [comment]
Oh, the site is down for me as well. I last checked it about half a year ago and it was still working. They might have abandoned the project after all. :(

And another thing that came to my mind:
- we have a near excellent (in terms of open source) desktop telegram client
- it is Qt-based
- it is already responsive and should look OK on mobiles (try resizing the window)
- Qt apps can be ported to Android
- ??????
- _profit_

**Comment by thermatk** [comment]
I'm not sure what you all guys want... %)
@iamale There is nothing wrong with the app we have here, no reason to port a less functional non-native(for Android) Qt app.
3.18 is here, with full feature parity because I've kind of ported location sharing to osmdroid, although it's not 100% done yet =D
Calm down, update f-droid repos in the next 1-5 days(last signing session happened on the 23rd, so another one should be close) and think how you can contribute to this very project :1st_place_medal:

**Comment by iamale** [comment]
@thermatk I'm not suggesting it would be useful right now, of course, just a backup plan :)

**Comment by Matttter** [comment]
What I meant was, doesn't Matrix "federate" with Telegram? Did anyone get that to work reliably? Because everyone is locked to the platform they're already in (my case, mostly Telegram after I just flat out refused to further communicate with Whatsapp, and that almost split my family in half), and if "federated" like that I can just switch and get people to switch gradually... I just can't figure out how to make it run on my rpi3? Maybe I'm just stupid

**Comment by av2k** [comment]
A big "Thank you!" to all contributors!
The Telegram Android client is of very high quality, waiting a few days or weeks to get it in FOSS flavor is absolutely worth it.
I would even go as far to say that Telegram is currently the best mobile messenger available in terms of security, source-openness, functionality and code stability.

**Comment by atemp** [comment]
Another big thank you from me. I hope the f-droid pipeline will soon spit out signed packages.

To me telegram is a nice solution that works now and is FOSS. What matters to me is to know what code is running on my hardware. And waiting a bit for the release is more than fair when you think about (as far as i get it) everyone working on it here is doing it for free/fun.

**Comment by thermatk** [comment]
Go update your Telegrams from F-Droid, this issue is resolved :) 
For offtopic conversations we better use a Telegram group I've just created :rofl: 
https://t.me/joinchat/AAAAAAh-hADrSzap8ebIJQ

If someone is in Munich, let's go celebrate :raised_hands:

**Comment by vn971** [comment]
Hm, how do I join the new group from telegram-s UI itself?
-- 
Sent from my mobile device. Please excuse my brevity.

**Comment by c33s** [comment]
tried to join the group but getting the error "sorry, this chat does not seem to exist."

![telegram](https://cloud.githubusercontent.com/assets/649209/25527480/367b4fda-2c19-11e7-9e99-c3c165cfe0e1.png)

**Comment by thermatk** [comment]
https://t.me/joinchat/AAAAAEFaw9LIC-VgKVCevg
change to supergroup changes invite link O_o

**Comment by Seferi** [comment]
Hi, just updated my Telegram. Thanks alot for continuing  to work on the FOSS version.

**Comment by JimmyS83** [comment]
Do anybody know, where I could download .apk from this version? Its been deleted or something from F-Droid :( I need a FOSS version, which can be runned on Android 2.3.6, and has MTProto2 at least somehow implemented :(

_3.18.0c, This version is built and signed by F-Droid, and guaranteed to correspond to the source tarball published with it. Version code: 9605_

**Comment by JimmyS83** [comment]
Does anybody know, where to download compiled v3.18.0c version? For some reason it isnt accesible from F-Droid. I need Telegram for Android 2.3.6, which kind a support MTProto 2.0 :(

**Comment by Self-Perfection** [comment]
@JimmyS83 just enable "F-Droid Archive" repository in F-Droid client settings. It stores old apk versions, v3.18.0c is still there
