### ISSUE TITLE
osmdroid instead of google maps

### ISSUE THREAD

**Issue by thermatk** [Telegram-FOSS-Team/Telegram-FOSS#134]
![screenshot_1491258733](https://cloud.githubusercontent.com/assets/2287483/24634480/729cf576-18ce-11e7-87ae-e614085bcc21.png)

I have never worked with osmdroid before and I have a hard time understanding the incredibly long Telegram source files without any comments, but it already kind of works :)

https://github.com/thermatk/Telegram-FOSS/tree/3.18-foss-osmdroid

**Comment by Bubu** [comment]
Wow! Really, really cool.

**Comment by thermatk** [comment]
Fully functional except for minor annoyances :+1:

**Comment by fabmazz** [comment]
Great news!

**Comment by thermatk** [comment]
Merged!
