### ISSUE TITLE
[WIP] osmdroid LocationActivity

### ISSUE THREAD

**Issue by thermatk** [Telegram-FOSS-Team/Telegram-FOSS#139]
The quick bring-up is in place and certainly does no more harm than the toast message before, but if someone knows how to do it properly, please share it. My objective was to replace Google Maps with least possible intrusion into source code, so to stay close to upstream, but with OpenStreetMap. Unfortunately, the APIs are really different. 
I think, that actually the only more or less failing thing now is the random appearance of the marker(overlay) of your current location, when you receive a message with some other location.
All the fun happens here:
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/master/TMessagesProj/src/main/java/org/telegram/ui/LocationActivity.java

**Comment by utack** [comment]
Do you mean you want to replace the small Google Maps preview image with OSM?
