### ISSUE TITLE
Add APK to release Downloads

### ISSUE THREAD

**Issue by elouin** [Telegram-FOSS-Team/Telegram-FOSS#141]
Hello,

Could you add an APK File to the Downloads on the Releases Page?

**Comment by thermatk** [comment]
I could, signed with my keys. It would make it not possible to install over the previous F-Droid build or install the next F-Droid build over it. That's why i doubt whether I should do it

**Comment by stefan-niedermann** [comment]
Why not download the apk from the F-Droid page as soon as it is built? This way it is signed by F-Droid. But why the need to host it here on github? Better paste a link into the readme file to https://f-droid.org/repository/browse/?fdcategory=Internet&fdid=org.telegram.messenger&fdpage=5 where all F-Droid-signed apk files are hostet?

**Comment by thermatk** [comment]
the link is there and it says "Get it on F-Droid" :+1: 
Let's be patient and wait till they fix the build server, then v3.18 will be up
