### ISSUE TITLE
 NDK: ERROR:/Users/.../Desktop/Telegram/TMessagesProj/jni/Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    

### ISSUE THREAD

**Issue by PattyGeorgi** [Telegram-FOSS-Team/Telegram-FOSS#142]
Hello,

I cloned the latest code from the DrKlo Telegram github repository: 3.18.0
When i try to run it in Android Studio i get the following error:

Error while executing process /Users/.../Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/.../Desktop/Telegram/TMessagesProj/jni/Android.mk NDK_APPLICATION_MK=/Users/.../Desktop/Telegram/TMessagesProj/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-14 NDK_OUT=/Users/.../Desktop/Telegram/TMessagesProj/build/intermediates/ndkBuild/armv7/debug/obj NDK_LIBS_OUT=/Users/.../Desktop/Telegram/TMessagesProj/build/intermediates/ndkBuild/armv7/debug/lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
/UsersA/.../Library/Android/sdk/ndnkd-bundle/build/core/prebuilt-library.mk:r4o5: *** Ainddroid NDK: Aborting    .  Stop.
 NDK: ERROR:/Users/.../Desktop/Telegram/TMessagesProj/jni/Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /Users/.../Desktop/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_armeabi-v7a.a exists  or that its path is correct   

I did not check if the path is correct, as i did a clean clone and did not change anything in the code just yet, so i guess that's not the problem. I'd be really grateful if someone could help me with this really urgend issue.

Thank you in advance

**Comment by thermatk** [comment]
check if you cloned the submodule at all, or whether it's on the right commit somewhere back in the history - the static prebuilts have been replaced by source code on our request recently.

**Comment by PattyGeorgi** [comment]
i am on branch master and the last commit is the most recent one: 

commit 6a1cf64f6f45ba0d0e7ff898e8a6c677ddc3ef33
Author: DrKLO <drklo.2kb@gmail.com>
Date:   Fri Mar 31 02:58:05 2017 +0300

    Update to 3.18.0

do you think it has anything to do with the ndk or with my android studio settings?

**Comment by thermatk** [comment]
no, I mean the commit of the submodule
https://github.com/grishka/libtgvoip/commits/public
0.3.2 is the version to be compiled with DrKLO's source

**Comment by PattyGeorgi** [comment]
what submodule? i just want the original telegram to run in android studio.

**Comment by thermatk** [comment]
telegram source code includes a git submodule since v.3.18.0
If you have no files under TMessagesProj/jni/libtgvoip , just find a way to force pulling the submodule for your OS/Android Studio/git or whatever

**Comment by thermatk** [comment]
I would expect that this will be the answer you're looking for
https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by PattyGeorgi** [comment]
yes you are right, there is nothing under TMessagesProj/jni/libtgvoip. so, if there is nothing under this folder, telegram won't build in android studio since v 3.18.0?

**Comment by thermatk** [comment]
just get the submodule to this folder and it will compile :+1:

**Comment by PattyGeorgi** [comment]
thanks a lot!

**Comment by PattyGeorgi** [comment]
ps: where can i see the changes (like the one with the submodule) when there is a new telegram version. i went through the DrKlo github repo and didn't find any readme which said what changed compared to the last update.

**Comment by mahdi899** [comment]
can you help me how to add submodule? where i add  
"git clone --recursive -j8 git://github.com/foo/bar.git
cd bar" this codes?

**Comment by M3000j** [comment]
in the terminal of android studio.
the terminal tab is on the bottom of android studio.

**Comment by s-kh** [comment]
i wrote this command
(git clone --recurse-submodules -j8 git://github.com/foo/bar.git) 
in android studio's terminal and i faced this error
(fatal: remote error:
  Repository not found.):
C:\dev\workspace\downloads\Telegram-master\Telegram-master>git clone --recurse-submodules -j8 git://github.com/foo/bar.git
Cloning into 'bar'...
fatal: remote error:
  Repository not found.

i dont know what's wrong!! can you help me?

**Comment by jagamypriera** [comment]
@s-kh dude, that repo doesn't exist yet

**Comment by Toni111111** [comment]
I also have this problem
