### ISSUE TITLE
Help: How to install android-ndk-r14b-darwin-x86_64.zip on MacBook

### ISSUE THREAD

**Issue by PattyGeorgi** [Telegram-FOSS-Team/Telegram-FOSS#143]
Hi everyone,

i cloned the latest Telegram code from DrKlo Github. In your ReadMe it says that i need to install the NDK: Important: You also need the Android-NDK and run ndk-build in the TMessagesProj directory before building the apk.

I downloaded Android-NDK but i don't know how to install it and when i try ndk-build in the TMessagesProj directory i get the following error message:  command not found: ndk-build

It would be awesome if someone can help me how to do this.

Thank you :)

**Comment by mastad0n** [comment]
You have to set the PATH of NDK

**Comment by thermatk** [comment]
I think `ndk-build `thing is outdated, gradle does it now. Just set the env variables and run gradle assembly or use Android Studio

**Comment by PattyGeorgi** [comment]
i set the path to the NDK in the project structure:

/Users/.../Library/Android/sdk/ndk-bundle

is this correct?

ps: how do i set the env variable?

**Comment by thermatk** [comment]
Please Google it, this is some very general android dev on macos question I have no idea about :)
