### ISSUE TITLE
Cant compile - openssl/aes errors on Windows

### ISSUE THREAD

**Issue by JimmyS83** [Telegram-FOSS-Team/Telegram-FOSS#148]
Hello,

I am sorry for maybe stupid questions, but I am pretty new on Android stuff. Could you please help me with compiling the source? I downloadded latest Android Studio 2.3.1, recursivelly git Telegram-FFOS (or Telegram from drKLO), but somehow I cant get the IDE configuring right. I also installed LLDB, CMake, and the NDK from the SDK Manager. I installed there 7.1.1 and 4.0 SDK Platforms. http://imgur.com/a/b85qp.

Import project, info message shows like "Unregistered VCS root detected d:\TBuild\Telegram-FOSS\TMessagesProj\jni\libtgvoip\", I click OK / sync, and it looks satisfied. I tried Make Project, but got various errors, starting from "Android NDK: Aborting Stop" - then I install additional Android 4.0 SDK, now I am getting:

```
D:/TBuild/Telegram-FOSS/TMessagesProj/jni/./jni.c:7:25: fatal error: openssl/aes.h: No such file or directory
 #include <openssl/aes.h>
```
 
I did also "`mklink /D d:\TBuild\Telegram-FOSS\TMessagesProj\jni\openssl\include\openssl d:\TBuild\Telegram-FOSS\TMessagesProj\jni\openssl\crypto`" according https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/123, but seems that doesnt help with "./jni.c:7:25: fatal error: openssl/aes.h" :(

Which parts of SDK, and maybe some other stuff must be installed before compiling source (Windows 7)?

Thank you in advance

**Comment by thermatk** [comment]
Hi!
in #123 they also mention copying all header files across directories, it helped everyone else. I can't really help with Windows, I have Arch and Ubuntu ;)

**Comment by JimmyS83** [comment]
It seems that was just my overlook. Those openssl .h "crosslinks" are quite a mess on windows :)  Sorry for duplicite.
