### ISSUE TITLE
Google PUSH notifications

### ISSUE THREAD

**Issue by JimmyS83** [Telegram-FOSS-Team/Telegram-FOSS#149]
Hello,

Didnt you consider add another version to this fork, allowing using of GAPPS, therefore PUSH notification? So it could be also offered through Google Play? I would appretiate that (push notif. -> better battery life from my experience).

Thank you for your work, anyway ;)

**Comment by thermatk** [comment]
Hi!
I don't really understand your request, is there a foss-library to be included in the project which supports push notifications through gms?
What do you propose to offer on Google Play and why? :)

**Comment by JimmyS83** [comment]
As I understand (maybe I am wrong), but foss project has taken out google code (or something like that), which allows original application use GMS (if GMS allows native google pus notification).

I know, that telegram offers also his own background service (checked by default), but I always disable additional services, and use google push up notifications. So, also in original telegram, I disabled background service, and app works fine with notifications through google/android wake-ups.

I understand, that there are some people (and maybe vast majority of F-Droid users), which dont have "GAPPS" (I mean google code) in their phones. And its great that they have functionall app, just because additional background service. I just think, it would be nice also for other users (like me), which using google play-google apps, which using google GMS (or something like that).

Does it sound more clear? :)

**Comment by thermatk** [comment]
What will the difference between this and original Telegram be then? :rofl: 
It's exactly about gms library being proprietary binary which no one knows what it's doing

**Comment by JimmyS83** [comment]
Hmm, its kinda point, admitting that. I personally differentiate between hockeyapp/foursquare bloat and google code, and also I have feeling that original Telegram author quite ignoring PR and so on, so this fork would have a meaning in my eyes.

But I respect your strict opinion about that.

**Comment by thermatk** [comment]
There is a view that there should be another version of this fork massively accepting features and PRs, but since it will be FOSS too returning gms is not one of them 
An app with gms can't be accepted in F-Droid, even if in your opinion google backdoors are better than some others :)
