### ISSUE TITLE
Don't use Google Maps

### ISSUE THREAD

**Issue by theel0ja** [Telegram-FOSS-Team/Telegram-FOSS#150]
The shared location view is using Google Maps.

**Comment by thermatk** [comment]
If you mean the thumbnail, it's just a picture, there are no maps-related binary dependencies left. 
Or is it something else?

**Comment by theel0ja** [comment]
Ok, but the app's maps should be using one uniform look (OSM's maps).

**Comment by thermatk** [comment]
Ok, make a PR, but only if it's not too big and intrusive. I'd suspect the image comes from 
Personally, I don't see this affecting anything in any way :+1:
