### ISSUE TITLE
OpenStreetMap should be attributed

### ISSUE THREAD

**Issue by Robot8A** [Telegram-FOSS-Team/Telegram-FOSS#151]
As stated in osm.org/copyright, the map should include the attribution © OpenStreetMap Contributors
![screenshot_2017-05-14-17-32-32](https://cloud.githubusercontent.com/assets/19521377/26035386/7ac4b5f0-38cb-11e7-9526-7ebb48d464c0.png)

**Comment by thermatk** [comment]
Sure, I expected osmdroid does it in the corner and didn't see that it doesn't 
If someone could add an overlay with attribution, please PR, I have exams these weeks

**Comment by thermatk** [comment]
This a reference to understand how to add it:
https://github.com/osmdroid/osmdroid/issues/501
