### ISSUE TITLE
NDK path issue

### ISSUE THREAD

**Issue by WaqarAhmadAwan** [Telegram-FOSS-Team/Telegram-FOSS#154]
Kindly help me with this issue.

Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-14 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/fat/release/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\fat\release\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_x86.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-23 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/x86_SDK23/foss/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\x86_SDK23\foss\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_x86.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-14 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/armv7/foss/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\armv7\foss\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_armeabi-v7a.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-14 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/armv7/debug/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\armv7\debug\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
process_begin: CreateProcess(NULL, "", ...) failed.
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_armeabi-v7a.a exists  or that its path is correct   
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-23 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/armv7_SDK23/foss/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\armv7_SDK23\foss\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_armeabi-v7a.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-14 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/fat/debug/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\fat\debug\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_x86.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-23 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/x86_SDK23/debug/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\x86_SDK23\debug\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_x86.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-23 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/armv7_SDK23/debug/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\armv7_SDK23\debug\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_armeabi-v7a.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-23 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/armv7_SDK23/release/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\armv7_SDK23\release\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_armeabi-v7a.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-14 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/x86/debug/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\x86\debug\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_x86.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-14 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/x86/release/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\x86\release\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_x86.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-14 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/x86/foss/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\x86\foss\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_x86.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-14 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/fat/foss/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\fat\foss\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_x86.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-14 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/armv7/release/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\armv7\release\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_armeabi-v7a.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=D:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-23 NDK_OUT=D:/Telegram/TMessagesProj/build/intermediates/ndkBuild/x86_SDK23/release/obj NDK_LIBS_OUT=D:\Telegram\TMessagesProj\build\intermediates\ndkBuild\x86_SDK23\release\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-14 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:D:\Telegram\TMessagesProj\jni\Android.mk:WebRtcAec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/Telegram/TMessagesProj/jni/./libtgvoip/external/libWebRtcAec_android_x86.a exists  or that its path is correct   
process_begin: CreateProcess(NULL, "", ...) failed.

**Comment by thermatk** [comment]
Hi.

1. You aren't even building telegram-foss ;) 
2. Windows has a lot of issues  with symlinks, see closed issues here
3. But your problem for now is you didn't even initialize git modules, see previously closed issues as well

**Comment by blukhi99** [comment]
External Native Build Issues
Build command failed.
Error while executing 'D:\adt-bundle-windows-x86_64-20140321_\android-ndk-r12b\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Android.mk NDK_APPLICATION_MK=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDEBUG=0 APP_PLATFORM=android-21 NDK_OUT=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\.externalNativeBuild\ndkBuild\release\obj NDK_LIBS_OUT=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\build\intermediates\ndkBuild\release\lib NDK_APPLICATION_MK=src/main/jni/Application.mk GSTREAMER_JAVA_SRC_DIR=src/main/java GSTREAMER_ROOT_ANDROID=/path/to/gstreamer/android GSTREAMER_ASSETS_DIR=src/main/assets APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -n}
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Android.mk    
process_begin: CreateProcess(NULL, "", ...) failed.
Error:executing external native build for ndkBuild E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Android.mk
Build command failed.
Error while executing 'D:\adt-bundle-windows-x86_64-20140321_\android-ndk-r12b\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Android.mk NDK_APPLICATION_MK=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDEBUG=1 APP_PLATFORM=android-21 NDK_OUT=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\.externalNativeBuild\ndkBuild\debug\obj NDK_LIBS_OUT=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\build\intermediates\ndkBuild\debug\lib NDK_APPLICATION_MK=src/main/jni/Application.mk GSTREAMER_JAVA_SRC_DIR=src/main/java GSTREAMER_ROOT_ANDROID=/path/to/gstreamer/android GSTREAMER_ASSETS_DIR=src/main/assets APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -n}
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Android.mk    
process_begin: CreateProcess(NULL, "", ...) failed.
Error:executing external native build for ndkBuild E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Android.mk
D:\adt-bundle-windows-x86_64-20140321_\android-ndk-r12b\build\core\add-application.mk
Error:(197, 0) *** Android NDK: Aborting...    .  Stop.
<a href="openFile:D:/adt-bundle-windows-x86_64-20140321_/android-ndk-r12b/build/core/add-application.mk">Open File</a>
Error:(197, 0) *** Android NDK: Aborting...    .  Stop.
<a href="openFile:D:/adt-bundle-windows-x86_64-20140321_/android-ndk-r12b/build/core/add-application.mk">Open File</a>

**Comment by shubhamhackz** [comment]
Hello,I got this error too..

**Comment by Bubu** [comment]
That means you are also building on Windows? That's not gonna work... with the4 latest ffmpeg changes far less so than before.

**Comment by shubhamhackz** [comment]
NO....I am building on Mac

**Comment by oplarshad** [comment]
me too... got the same problem
