### ISSUE TITLE
Share location pin not so accurate

### ISSUE THREAD

**Issue by mnirfan** [Telegram-FOSS-Team/Telegram-FOSS#155]
When v3.18b share a location, it doesn't show as same as the location when pinning it. The mislocation is not so far, maybe just some tens meters. Maybe because the balloon pointing with different point.

**Comment by n00bus** [comment]
it's a feature of 3.18.0b, approximate location. so you don't need to wait gps, but there is a button for gps afaik.

**Comment by thermatk** [comment]
I can confirm, but I didn't understand yet whether it is an issue of marker drawn wrong over a geopoint or the geopoint being sent is wrong

**Comment by thermatk** [comment]
It's the point marker being drawn centered, while you would expect it's bottom tip to actually show the location

**Comment by mnirfan** [comment]
Thank you for fixing this 😊
