### ISSUE TITLE
External Native Build Issues i got this issue

### ISSUE THREAD

**Issue by blukhi99** [Telegram-FOSS-Team/Telegram-FOSS#156]
External Native Build Issues
Build command failed.
Error while executing 'D:\adt-bundle-windows-x86_64-20140321_\android-ndk-r12b\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Android.mk NDK_APPLICATION_MK=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDEBUG=0 APP_PLATFORM=android-21 NDK_OUT=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\.externalNativeBuild\ndkBuild\release\obj NDK_LIBS_OUT=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\build\intermediates\ndkBuild\release\lib NDK_APPLICATION_MK=src/main/jni/Application.mk GSTREAMER_JAVA_SRC_DIR=src/main/java GSTREAMER_ROOT_ANDROID=/path/to/gstreamer/android GSTREAMER_ASSETS_DIR=src/main/assets APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -n}
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Android.mk    
process_begin: CreateProcess(NULL, "", ...) failed.
Error:executing external native build for ndkBuild E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Android.mk
Build command failed.
Error while executing 'D:\adt-bundle-windows-x86_64-20140321_\android-ndk-r12b\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Android.mk NDK_APPLICATION_MK=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDEBUG=1 APP_PLATFORM=android-21 NDK_OUT=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\.externalNativeBuild\ndkBuild\debug\obj NDK_LIBS_OUT=E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\build\intermediates\ndkBuild\debug\lib NDK_APPLICATION_MK=src/main/jni/Application.mk GSTREAMER_JAVA_SRC_DIR=src/main/java GSTREAMER_ROOT_ANDROID=/path/to/gstreamer/android GSTREAMER_ASSETS_DIR=src/main/assets APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -n}
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Android.mk    
process_begin: CreateProcess(NULL, "", ...) failed.
Error:executing external native build for ndkBuild E:\Loops\projects\UPWORK\Wang GukHoo\gst-examples\playback\player\android\app\src\main\jni\Android.mk
D:\adt-bundle-windows-x86_64-20140321_\android-ndk-r12b\build\core\add-application.mk
Error:(197, 0) *** Android NDK: Aborting...    .  Stop.
<a href="openFile:D:/adt-bundle-windows-x86_64-20140321_/android-ndk-r12b/build/core/add-application.mk">Open File</a>
Error:(197, 0) *** Android NDK: Aborting...    .  Stop.
<a href="openFile:D:/adt-bundle-windows-x86_64-20140321_/android-ndk-r12b/build/core/add-application.mk">Open File</a>

**Comment by shubhamhackz** [comment]
I am getting this issue ..what to do??
