### ISSUE TITLE
Not so easy to build with ndk r15+

### ISSUE THREAD

**Issue by thermatk** [Telegram-FOSS-Team/Telegram-FOSS#161]
Bundled breakpad, as well as upstream one, is broken
https://bugs.chromium.org/p/google-breakpad/issues/detail?id=733
Use r14 instead

**Comment by omkarnathsingh** [comment]
@thermatk NDK 15 has issues from Google. But there is a temporary fix to it. 
Add the following to Application.mk file. 

`APP_DEPRECATED_HEADERS := true`

Reference: https://stackoverflow.com/questions/44141159/ndk-issue-in-android-studio-canary-3-0

**Comment by Bubu** [comment]
@omkarnathsingh The fix doesn't seem to work, I get the same errors.

**Comment by omkarnathsingh** [comment]
@Bubu I am not sure then. I am using Android Studio 3 Canary build and doing that tweak helped me. I can build the project now.

**Comment by ghost1372** [comment]
just use ndk 14-rb

**Comment by thermatk** [comment]
Fix is there
https://chromium.googlesource.com/breakpad/breakpad/+/afa9c52715db1e4bfaa4b01c9aec40cc249b689b
No need to apply it here though, we have no need to rebuild yet anyway

**Comment by thermatk** [comment]
#191 #193 need to be fixed

**Comment by Bubu** [comment]
#196 has a hint to what might be going on.

**Comment by thermatk** [comment]
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/ca8e690cd64fc2fc3b7fb10b5290c0463d92d837/TMessagesProj/jni/opus/opusfile/internal.h#L27
Deleting this line should fix it I think
if it does, also worth notifying https://github.com/deltachat/deltachat-android/issues/220

**Comment by omkarnathsingh** [comment]
@thermatk Why was this issue closed? Is the latest NDK good enough to use now?

**Comment by thermatk** [comment]
see Readme
for now you have to combine r14b and r16b, because I couldn't make ffmpeg build with r16b yet

**Comment by nickaein** [comment]
As the time of writing, the Readme recommends doesn't mention r14b anymore. Is r16b the only needed NDK?
