### ISSUE TITLE
Video compression seems to be missing

### ISSUE THREAD

**Issue by eiszfuchs** [Telegram-FOSS-Team/Telegram-FOSS#166]
Ahoy!

I got the 4.1 update via F-Droid today, and it seems that video compression does not work as before.
Before, I could select a video from the gallery, trim it and select a compression tier (e.g. 480p).

![screenshot_2017-07-20-08-32-53](https://user-images.githubusercontent.com/240167/28403839-e7b03d30-6d26-11e7-9d0a-1bfbc854ce28.jpg)

Now, it looks like there is no such selection anymore, but in fact, there is a blank button (I can tell because it shows a ripple when holding it and it showed "240" before, but would just send the video in 4K anyway) in the middle of the bottom toolbar, but this just takes me to an empty screen where I can watch the video.
Though this might be a problem with the original App, I thought maybe this is something that broke with the recent merge?

If it is, I'm sorry to have bothered you! 👍

**Comment by thermatk** [comment]
Hi @eiszfuchs 
For me everything is ok and there are no changes to video-related things, except for the ffmpeg build, so I'd say it's an upstream thing. I don't really have 4k videos to test, it might be related to video encoding or size itself, which makes the button disappear for incompatible files.
Search for `compressItem.setVisibility` in the [VideoEditorActivity](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/master/TMessagesProj/src/main/java/org/telegram/ui/VideoEditorActivity.java)

**Comment by eiszfuchs** [comment]
It worked before and was pretty useful to not spam friends with insanely huge files, that's why I was wondering. I'll keep an eye on it.

**Comment by eiszfuchs** [comment]
Just in case somebody else has got the problem, too: I tried several things and it seems that selecting the video in the in-App gallery does not work, but when the video is shared via a gallery App, e.g. Piktures, then Telegram shows the compression slider I was missing.

![steps](https://user-images.githubusercontent.com/240167/28490472-1cc47ab2-6edb-11e7-896b-be3cee510a71.png)

**Comment by thermatk** [comment]
They changed the whole thing, I'm not sure for bad or good, but it's different anyway
