### ISSUE TITLE
Telegram 4.2.0 source code available

### ISSUE THREAD

**Issue by zikalify** [Telegram-FOSS-Team/Telegram-FOSS#167]
https://github.com/DrKLO/Telegram/commits/master

**Comment by Bubu** [comment]
This doesn't seem to be relaesed on google play yet. They pushed a commit before a google play release? Madness! :-)

Commit log:
> source before release? how this even possible?

**Comment by Bubu** [comment]
And people are already complaining there that the code is relaesed but the update is not :-(

**Comment by moriel5** [comment]
Update: it seems to have been released.
However, don't rush yourselves, we have (at least I do) patience.

**Comment by thermatk** [comment]
Rebased and released, shouldn't have any problems and new gms dependencies. Yet, can't try to build myself till tomorrow

**Comment by Bubu** [comment]
Haha, v4.2.1 already pushed.

**Comment by moriel5** [comment]
I had just read about it on the tgbeta channel, then rushed to check if anyone had alrwady mentioned it here.
Has the world flipped over?

**Comment by thermatk** [comment]
v4.2.1 is up instead of v4.2, still have no access to a PC 😢

**Comment by Bubu** [comment]
@thermatk I don't quite understand what happened with your commits. They show up as made 14 days ago. I guess that is because of some rebase operation? (But if you change the commits, they should get a new date...)

Also you removed the 4.2.0 tag so that it doesn't get build y f-droid?

@moriel5 Whats the TGBeta channel?

**Comment by Bubu** [comment]
I tried building the new version, first gradle stumbled over some weird utf16 mark in build.gradle. I fixed that.
Than somehow the ndk build doesn;t work from gradle but that's probably a problem with my local setup.
Running ndk-build inside the `TMessagesProj` folder starts the build but fails with:

```
make: *** No rule to make target `jni/./libtgvoip/client/android/tg_voip_jni.cpp', needed by `obj/local/armeabi/objs/tmessages.27/./libtgvoip/client/android/tg_voip_jni.o'.  Stop.
```

I'll see if I can get further.

(Using ndk r14b as with r15 I got the breakpad error)

(Also sorry for being absent for so long. Thanks for maintaining this *thing* ;-))

**Comment by moriel5** [comment]
The TGBeta channel is an unofficial indonesian telegram channel dedicated to news pertaining to Telegram (including prerelease versions, source code releases, Telegram press news, etc.).
I am not indonesian, however the channel is in English, so I have no problem reading what is posted there.

https://www.t.me/tgbeta

**Comment by thermatk** [comment]
@Bubu Great to see you again!
Sorry again for utf16, it's my mobile-editing failure. Rebased onto upstream fix anyway. I've switched to this new approach when we have structured commits always sitting nicely on top of plain upstream, with the changelog being the last one(so that it's easy to amend 👍 ). I know it's probably not the proper git-way, but it's easy to audit and see Telegram-FOSS changes in a clean way throughout every file's history

**Comment by thermatk** [comment]
4.2 was broken upstream in many places, even if it would build, that's why we have 4.2.1 now :)

**Comment by Bubu** [comment]
Argh, and git submodules strike again. :woman_facepalming:
Got the ndk-build works now. And seems like this also fixed the gradle externalNativeBuild (I don't know how it works, but it was failing instantly before)

@thermatk Can you share what you do on each release/upstream commit? And when I want to add some stuff (Readme, changelog fixes, etc.) What should I do? New commit on top of master? Squash with the corresponding commit if applicable?

**Comment by Bubu** [comment]
I'm still a bit confused what f-droid will do now. The auto-updatecheck ran one hour before you retagged the release. Will it pick up the fixed version now? If it doesn't would we need to add a v4.2.1a release?

**Comment by thermatk** [comment]
@Bubu I see no problem, the tag has the same name, it worked like that before

**Comment by thermatk** [comment]
It's just that now we have to wait for another buildserver-running-wave 😢 
It is easy to recognize by monitoring [this page](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&hidebots=0) for a bunch of lastbuilds

**Comment by Bubu** [comment]
I just wasn't sure if it will retry a failed. Here is the first failed one: https://f-droid.org/wiki/page/org.telegram.messenger/lastbuild_10435

Let's see what happens.

(repeating in case you have missed it:)@thermatk Can you share what you do on each release/upstream commit? And when I want to add some stuff (Readme, changelog fixes, etc.) What should I do? New commit on top of master? Squash with the corresponding commit if applicable?

**Comment by Bubu** [comment]
Build and published  on F-Droid!

**Comment by shijilsmb** [comment]
Hi, @Bubu I am stuck with the same issue ('make: *** No rule to make target `jni/.......'), tried both ndk versions r14b and  r15 but still got the same error.

**Comment by Bubu** [comment]
@shijilsmb Have you done a `git clone --recursive`? Or if you already cloned it you can do `git submodule update --init`.

**Comment by hediehloo** [comment]
download submodule libtgvoip from link:
https://github.com/grishka/libtgvoip/tree/e42287b6f4a520b7ddabc6cdcff205f4e7e216ec
replace in libtgvoip folder
