### ISSUE TITLE
Any way to download old Telegram builds?

### ISSUE THREAD

**Issue by GijsTimmers** [Telegram-FOSS-Team/Telegram-FOSS#168]
Hi,

I'm running an old phone with Gingerbread. Can't update because no one makes roms for this phone anymore. However, the phone itself still works well. I would like to download Telegram for it so it still has some use. Is there any way to do so without building myself?

**Comment by Bubu** [comment]
They should be in the f-droid archive repo. Install f-droid and in settings enable the archive repo. You should then be able to install Telegram-FOSS versions from quite a while back.

**Comment by ildar** [comment]
Also 4pda.ru is known for apk-s archive, if you ask about apk made by
vendor.
P.s. only registered users can download.
