### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ghost1372** [Telegram-FOSS-Team/Telegram-FOSS#170]
hi i want to compile telegram, but when i want compile jni folder i get error,
is there anyone send me compiled libtmessages.22.so ? i cant compile c++ source.
![untitled](https://user-images.githubusercontent.com/9213496/28961090-4d155426-7916-11e7-9c7f-eb5828e2e8ea.png)

**Comment by Bubu** [comment]
See for example [here](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/148) or all the other compile issues on Windows.

Or just use Linux :)

**Comment by ghost1372** [comment]
tnx i used linux and compiled successfully.
