### ISSUE TITLE
Telegram version 4.6 Upstream release.

### ISSUE THREAD

**Issue by omkarnathsingh** [Telegram-FOSS-Team/Telegram-FOSS#173]
Dependent on @DrKLO 's source release.

**Comment by espectalll** [comment]
Version 4.6 has just been uploaded! https://github.com/DrKLO/Telegram/commit/5630ad862398a54e425a4578e8dea7f93c7f2c8f

**Comment by cauebs** [comment]
Why hasn't it showed up on F-Droid yet?
