### ISSUE TITLE
Multi account / second instance

### ISSUE THREAD

**Issue by Pimmetje** [Telegram-FOSS-Team/Telegram-FOSS#174]
I hope this is the correct place to post this. 

Is there any way to use a second account in the android app? Or is there a way to install a second instance?

I have one account i use many for work. But i also have a personal one. I would like to have them both on one phone. I would change the namespace and complile the app myself. But i don't think i am the only one with this problem. 

So whats your vision?

Thanks for reading in any case.

**Comment by thermatk** [comment]
Hi!
not really the place, but you can try something like Island
https://forum.xda-developers.com/android/apps-games/closed-beta-test-incoming-companion-app-t3366295
