### ISSUE TITLE
[FAQ] Invoking osmand app from telegram bot

### ISSUE THREAD

**Issue by kirantpatil** [Telegram-FOSS-Team/Telegram-FOSS#176]
Hi,

Is it possible to invoke osmand app from telegram bot ?

For example, I have a bot and in it I add a button called "Navigate", and clicking on it should open the osmand application 

Please throw some light on it.

Thanks.

**Comment by ildar** [comment]
May I try?
IMHO if the button will fire up the URL that is intercepted by OSMand, then
you get what you want. Just check its intents. AFAIK you can find http://
osmand.net among them.
Check this:
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/AndroidManifest.xml

**Comment by kirantpatil** [comment]
@ildar, Great and Thanks.

Please upload any sample code if you can come up.

**Comment by ildar** [comment]
Sorry, not a Java programmer. But you can find a lot of it around on your
own.
