### ISSUE TITLE
Change telegram package name?

### ISSUE THREAD

**Issue by HamidVO** [Telegram-FOSS-Team/Telegram-FOSS#177]
I imported telegram source code into Android studio and now I want to change package name :
  from  org.telegram   to    org.yazi
but after changing, app does not worked. when I installed on my cellphone it starts and show an empty page (with title "Telegram") and force closes.

  do I have to change anything else? 

I change package name using Android studio and set package name in manifest and gradle files.
I also created firebase for this namespace and copied json file inside project.
Inside buildvars I have set "APP_HASH" and "HOCKEY_APP_HASH" and "HOCKEY_APP_HASH_DEBUG" and "APP_ID".

What else?
I do not know whay is doe not works?

**Comment by vrone23** [comment]
h howi did your problem soled?

**Comment by r4sas** [comment]
Read about `applicationId` option for gradle.

**Comment by vrone23** [comment]
After package name change it is not working.
Does anyone have idea about it or custom code for telegram your own package name?
Please send it to me or message me
mr.vinodinsan1@gmail.com

**Comment by Ahmad-Mustafaa** [comment]
any solution till yet ?
