### ISSUE TITLE
ARMv6 (armeabi) support

### ISSUE THREAD

**Issue by maximpashuk** [Telegram-FOSS-Team/Telegram-FOSS#178]
Previously telegram client has support for armv6 devices (armeabi platform).
I can see armeabi references is still in code.

Is it possible to enable support of armeabi platform in FOSS telegram client?

**Comment by Bubu** [comment]
@maximpashuk Should be fixed by the linked PR. But can you test this APK I build to confirm it's working correctly? https://cloud.bubu1.eu/index.php/s/dB7evhAM1CHE1hf/download

**Comment by maximpashuk** [comment]
@Bubu Version you provide me works fine on LG Optimus One P500.
So I think your pull request is correct.

**Comment by Bubu** [comment]
@maximpashuk Can you test a bit more, maybe including the call feature? @thermatk had doubts that these would work.

**Comment by maximpashuk** [comment]
Just checked voice calls from LG P500, works fine.
Video calls not supported since this phone has no front camera.

Text messages, stickers, bots, gifs works ok - I use apk you provided since yesterday.

**Comment by thermatk** [comment]
@maximpashuk awesome! Even x86 didn't work for me before 👍

**Comment by thermatk** [comment]
it is in, but I would prefer not to trigger a rebuild for everyone, so we'll just calmly wait for the next release 👍 
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/commit/4f699003ef569ccfe8202edd31540d56c23493aa
