### ISSUE TITLE
When trying to upload videos as GIFs, Ignores and uploads video with audio anyway

### ISSUE THREAD

**Issue by Pwnulatr** [Telegram-FOSS-Team/Telegram-FOSS#180]
When taking a video from storage, I mute the audio in the upload screen. At that point it should convert it to a GIF or just not upload the audio, but it uploads the full video with audio. It will, however, work when I am recording said video inside the telegram app and request that it be uploaded as a GIF.

**Comment by Bubu** [comment]
@thermatk Is there anything we can/should do here? Otherwise this issue should be closed.
