### ISSUE TITLE
[v4.2.1a] Video msg without audio

### ISSUE THREAD

**Issue by jsparber** [Telegram-FOSS-Team/Telegram-FOSS#189]
All video msgs are sent without audio since v4.2.1a but audio msg work.

**Comment by Bubu** [comment]
Thanks for the report, this is probably realted to upgrading ffmpeg to the latest version. 

I think I can reproduce this. (I have never used audio or video messages before I think...)
I'll try to get some log output for this.

**Comment by jsparber** [comment]
what output would you need?

**Comment by Bubu** [comment]
adb logcat if it shows anything related to this. If it doesn't we need a special binary with ndk debugging enabled... I'm not quite sure how to do this right now.
