### ISSUE TITLE
Telegram crashes when I try to share a file from other app

### ISSUE THREAD

**Issue by moshpirit** [Telegram-FOSS-Team/Telegram-FOSS#190]
Right now using v. 4.2.1a from F-droid on Android 6.0.1

Steps to reproduce:

1. Open a picture/video/pdf/... viewer
2. Share the file
3. Select Telegram when the options are listed

It doesn't happen if I try to share them directly from the app though:

1. Open Telegram
2. Tap the clip icon
3. Select the file

**Comment by thermatk** [comment]
This is fixed, but not built by fdroid for some days. Look for 4.2.1b or 4.6

**Comment by moshpirit** [comment]
Great! I'll check the other issue as well when I get it
