### ISSUE TITLE
Doesn't show me the blue reproducion guide on audios

### ISSUE THREAD

**Issue by moshpirit** [Telegram-FOSS-Team/Telegram-FOSS#191]
When we receive an audio message (directly from the microphone) it shows the audio icon( [pic 1](https://i.imgur.com/oQ8k9JR.png) ) but not the typical blue line that shows us on what part of the audio are we ( [pic 2](https://i.imgur.com/0HLDXOf.png) ). This said, it appears (only) when we advance in the audio (which only advances for a few seconds) ( [pic 3](https://i.imgur.com/fUdcR2F.png) )

I find this really annoying when I'm already used to the other version, so I would really appreciate a quick new release when this bug get fixed if it's not asking too much.

Telegram v. 4.2.1a from F-droid on Android 6.0.1

**Comment by Bubu** [comment]
There were some video/audio recording and playtback issues with 4.2.1a these should be fixed in 4.2.1b and 4.6.0 which should be available from fdroid in a few days.

Can you retest with one of these version (when available) and report back. (There is a chance it's a different issue.)

**Comment by moshpirit** [comment]
Using v. 4.6.0 (F-droid): no fixed yet :\

Thank you for replying though!

**Comment by Bubu** [comment]
I can reproduce this. Just to be sure, this doesn;t happen on 4.2.1 but appeared on 4.2.1a, right?

**Comment by moshpirit** [comment]
Exactly!

**Comment by elvecio** [comment]
Plz, also see this https://github.com/deltachat/deltachat-android/issues/220 . I'm waiting for a solution for both. Thanks

**Comment by Bubu** [comment]
@moshpirit This problem is resolved when compiling tg-foss with ndk r14 instead of r15. No idea why yet though...

**Comment by Bubu** [comment]
Should be available from F-Droid in a few days.
