### ISSUE TITLE
Getting this error when trying to build..(MAC)

### ISSUE THREAD

**Issue by shubhamhackz** [Telegram-FOSS-Team/Telegram-FOSS#192]
External Native Build Issues
    Build command failed.
    Error while executing process /Users/hackz/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk NDK_APPLICATION_MK=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/x86/release/obj NDK_LIBS_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/x86/release/lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-16 -j5 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
    Android NDK: ERROR:/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk:avutil: LOCAL_SRC_FILES points to a missing file    
    Android NDK: Check that /Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/./ffmpeg/android/i686/lib/libavutil.a exists  or that its path is correct   
    Build command failed.
    Error while executing process /Users/hackz/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk NDK_APPLICATION_MK=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/armv7/release/obj NDK_LIBS_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/armv7/release/lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-16 -j5 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
    Android NDK: ERROR:/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk:avutil: LOCAL_SRC_FILES points to a missing file    
    Android NDK: Check that /Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/./ffmpeg/android/armv7-a/lib/libavutil.a exists  or that its path is correct   
    Build command failed.
    Error while executing process /Users/hackz/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk NDK_APPLICATION_MK=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-23 NDK_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/x86_SDK23/release/obj NDK_LIBS_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/x86_SDK23/release/lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-16 -j5 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
    Android NDK: ERROR:/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk:avutil: LOCAL_SRC_FILES points to a missing file    
    Android NDK: Check that /Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/./ffmpeg/android/i686/lib/libavutil.a exists  or that its path is correct   
    Build command failed.
    Error while executing process /Users/hackz/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk NDK_APPLICATION_MK=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-23 NDK_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/x86_SDK23/debug/obj NDK_LIBS_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/x86_SDK23/debug/lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-16 -j5 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
    Android NDK: ERROR:/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk:avutil: LOCAL_SRC_FILES points to a missing file    
    Android NDK: Check that /Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/./ffmpeg/android/i686/lib/libavutil.a exists  or that its path is correct   
    Build command failed.
    Error while executing process /Users/hackz/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk NDK_APPLICATION_MK=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/fat/debug/obj NDK_LIBS_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/fat/debug/lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-16 -j5 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
    Android NDK: ERROR:/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk:avutil: LOCAL_SRC_FILES points to a missing file    
    Android NDK: Check that /Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/./ffmpeg/android/i686/lib/libavutil.a exists  or t/hUsers/hacakzt its pat/hLibrary/An droid/sdk/indk-bundsle/build/core/prebuilt-library.mk:45: ***  Android NDK:correct   
     Aborting    .  Stop.
    Build command failed.
    Error while executing process /Users/hackz/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk NDK_APPLICATION_MK=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/armv7/debug/obj NDK_LIBS_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/armv7/debug/lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-16 -j5 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
    Android NDK: ERROR:/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk:avutil: LOCAL_SRC_FILES points to a missing file    
    /AUsers/hackz/Library/Android/sdk/ndk-bundle/buinld/dcrooried/ pNrDeKb:u iClhte-clki brtahrya.tm k/:U4s5e:r s*/**h aAcndkrzo/iDde sNkDtKo:p /ATbeolretgirnagm - F O S.S / TSMteosps.a
    gesProj/jni/Telegram-FOSS/TMessagesProj/jni/./ffmpeg/android/armv7-a/lib/libavutil.a exists  or that its path is correct   
    Build command failed.
    Error while executing process /Users/hackz/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk NDK_APPLICATION_MK=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-23 NDK_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/armv7_SDK23/release/obj NDK_LIBS_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/armv7_SDK23/release/lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-16 -j5 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
    Android NDK: ERROR:/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk:avutil: LOCAL_SRC_FILES points to a missing file    
    Android NDK: Check that /Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/./ffmpeg/android/armv7-a/lib/libavutil.a exists  or that its path is correct   
    Build command failed.
    Error while executing process /Users/hackz/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk NDK_APPLICATION_MK=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/x86/debug/obj NDK_LIBS_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/x86/debug/lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-16 -j5 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
    Android NDK: ERROR:/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk:avutil: LOCAL_SRC_FILES points to a missing file    
    Android NDK: Check that /Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/./ffmpeg/android/i686/lib/libavutil.a exists  /oUser rtsh/ahta ciktzs/ Lpiabtrhary /iAsn dcrooirdr/escdtk / n d
    k-bundle/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
    Build command failed.
    Error while executing process /Users/hackz/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk NDK_APPLICATION_MK=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-23 NDK_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/armv7_SDK23/debug/obj NDK_LIBS_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/armv7_SDK23/debug/lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-16 -j5 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
    Android NDK: ERROR:/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk:avutil: LOCAL_SRC_FILES points to a missing file    
    Android NDK: Check that /Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/./ffmpeg/android/a/rUsers/hackzm/vL7-a/lib/libiabvruatil.ry/Androiad /exisstds  ko/r that its path is correct   
    ndk-bundle/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
    Build command failed.
    Error while executing process /Users/hackz/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk NDK_APPLICATION_MK=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/fat/release/obj NDK_LIBS_OUT=/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/build/intermediates/ndkBuild/fat/release/lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-16 -j5 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
    Android NDK: ERROR:/Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/Android.mk:avutil: LOCAL_SRC_FILES points to a missing file    
    Android NDK: Check that /Users/hackz/Desktop/Telegram-FOSS/TMessagesProj/jni/Telegram-FOSS/TMessagesProj/jni/./ffmpeg/android/i686/lib/libavutil.a exists  or that its path is correct   
/Users/hackz/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk
    Error:Error:line (44)*** Android NDK: Aborting    .  Stop.
<a href="openFile:/Users/hackz/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk">Open File</a>
    Error:Error:line (44)*** Android NDK: Aborting    .  Stop.
<a href="openFile:/Users/hackz/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk">Open File</a>
    Error:Error:line (44)*** Android NDK: Aborting    .  Stop.
<a href="openFile:/Users/hackz/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk">Open File</a>
    Error:Error:line (44)*** Android NDK: Aborting    .  Stop.
<a href="openFile:/Users/hackz/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk">Open File</a>
    Error:Error:line (44)*** Android NDK: Aborting    .  Stop.
<a href="openFile:/Users/hackz/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk">Open File</a>
    Error:Error:line (44)*** Android NDK: Aborting    .  Stop.
<a href="openFile:/Users/hackz/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk">Open File</a>

**Comment by Bubu** [comment]
You are building with ndk r16, see the readme and use ndk r15c.

**Comment by shubhamhackz** [comment]
@Bubu Thank you...

**Comment by Bubu** [comment]
If you still have problems please reopen, and please provide a better formatted error log :-/.
