### ISSUE TITLE
Voice massages doesn't play

### ISSUE THREAD

**Issue by TheKourosh** [Telegram-FOSS-Team/Telegram-FOSS#193]
Telegram 4.6 on huawei g750 android 4.2.2
When i tap on the play button, nothing happen except the blue circle (for unplayed voices) disappear.

**Comment by thermatk** [comment]
Hi
It seems it might be affected by the same change as #191 
Could you please test this beta? Or just compile the latest source with NDK r14?

[4.6.beta.NDK14.apk.zip](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/files/1565669/4.6.beta.NDK14.apk.zip)

**Comment by susobaco** [comment]
I've tried the beta version, and audio playback works.

**Comment by thermatk** [comment]
Wait for new release
