### ISSUE TITLE
Build native FFmpeg dependency

### ISSUE THREAD

**Issue by Hussamalsh** [Telegram-FOSS-Team/Telegram-FOSS#195]
Hi, 
I am using windows and android studio to compile and run the app on my mobile phone. I dont understand how to build native FFmpeg dependency. You mentioned  to do like this "export NDK=[PATH_TO_NDK]" but i just write this to to command line of windows ? please explain more step by step.
Thank you and any help will be appreciated.

**Comment by Bubu** [comment]
I don't think it's possible to cross-compile ffmpeg under windows using it's native autotools build system. I'd recommend using a Ubuntu VM.

From our Readme: 
> Building under Windows may be problematic and won't be fixed
