### ISSUE TITLE
.ogg file not play in android 19

### ISSUE THREAD

**Issue by Reza-saeedi** [Telegram-FOSS-Team/Telegram-FOSS#196]
hello 
i clone telegram 4.6 code from github.com and build project
every thing work well in android api 25 but in android api 19 .ogg file not play(ex: recorded sound).
telegram not change audio.c file in new version but i get different answer from this method for same file:

isOpusFile(cacheFile.getAbsolutePath())=1 in version 4.2.1

isOpusFile(cacheFile.getAbsolutePath())=0 in version 4.6

**Comment by Bubu** [comment]
Which with ndk version are you building. We had problems with ndk r15, but it started working with ndk r14 again.

**Comment by thermatk** [comment]
@Bubu this actually gives us a good testcase with and exact function failing

**Comment by Reza-saeedi** [comment]
thank you.
I use ndk version 16 after change ndk version the problem was solved.

**Comment by thermatk** [comment]
I never even tried r16, too many scary changes
