### ISSUE TITLE
unsupported content for url sharing

### ISSUE THREAD

**Issue by danialbehzadi** [Telegram-FOSS-Team/Telegram-FOSS#200]
When you try to share a url with comments by telegram (e.g. share a f-droid app via share button on top of the page in f-droid app and select telegram) there is a "unsupported content" toast and nothing will happen.

**Comment by beerisgood** [comment]
Can confirm this with latest F-Droid version in LineageOS

**Comment by Bubu** [comment]
I'll look into it!

**Comment by Bubu** [comment]
Fixed. Just need to retag the release.
