### ISSUE TITLE
Audio problems from version 4.2.1a

### ISSUE THREAD

**Issue by lupo472** [Telegram-FOSS-Team/Telegram-FOSS#201]
After updating I discovered that audio in app in broken. When I try to play an audio message it won't start, as if I did't press anything.
I tried also updating to 4.6.0 but with no success.

**Comment by Bubu** [comment]
It should be fixed in 4.6.0a which will hopefully be published in the next few days on fdroid. If you compile from source yourself make sure to use ndk 14 instead of 15.

**Comment by lupo472** [comment]
OK thanks!!
