### ISSUE TITLE
Any way to toggle Apple Emoji?

### ISSUE THREAD

**Issue by mastad0n** [Telegram-FOSS-Team/Telegram-FOSS#202]
Just wondering if we're stuck with Twemoji now?

**Comment by thermatk** [comment]
Apple doesn't have proper licensing information for usage, one should make a deal through https://www.apple.com/legal/contact/
I don't know which deal upstream Telegram made and whether we will get a DMCA takedown request, so I'd rather say no. You can revert the commit with pngs in self-builts though, if you want.

**Comment by mastad0n** [comment]
@thermatk Thank you, I sent Apple an email to ask.
