### ISSUE TITLE
Enable adb backup

### ISSUE THREAD

**Issue by Agno94** [Telegram-FOSS-Team/Telegram-FOSS#203]
Possibility:
in file "TMessagesProj/src/main/AndroidManifest.xml" change ' android:allowBackup="false" ' into ' android:allowBackup="true" '.
I think you should allow backup with "adb backup" as all the application data should be "property" of the user, so there should be no problem if the user get the data.

**Comment by Bubu** [comment]
Related to #197. Has someone tested this? Does `adb backup` just work then? The cons are probable similar to the concerns of #197

**Comment by thermatk** [comment]
doesn't it also toggle backup uploads to google play backups, for those with GMs installed? That would be really bad behaviour

**Comment by thermatk** [comment]
Closing in favor of #197
