### ISSUE TITLE
Deleted contacts are not deleted

### ISSUE THREAD

**Issue by kq01526** [Telegram-FOSS-Team/Telegram-FOSS#205]
Hi,

when you add a contact to your Google/device contacts, which is not yet a Telegram user, and then delete that contact from Google/device contacts and the user then becomes a Telegram user, Telegram for Android still reminds you that this contact has now become a Telegram user, even though that contact is already gone from your Google/device contacts for a long time.

So, apparently Telegram for Android still has those contacts "invisibly" cached somewhere...

Enabling: "Android system settings -> Accounts -> Telegram -> Sync -> Contacts -> Enable" does not solve this issue.

Where does Telegram for Android store it's internal contact list?

**Comment by kq01526** [comment]
Additionally, even when "Android system settings -> Accounts -> Telegram -> Sync -> Contacts -> Enable" is enabled, and even if the contact still exists in the Google/device contacts and you then delete that contact, not even that contact is being deleted from Telegram.

**Comment by thermatk** [comment]
that's really not a question for our project

Telegram uploads contacts to the cloud, where apparently there is a separate contact list
