### ISSUE TITLE
Sqlite3.c build error

### ISSUE THREAD

**Issue by nefrin79** [Telegram-FOSS-Team/Telegram-FOSS#206]
Hi, 
I am using NDK15 & updated sdk tools.
But when I try to build then this error shows up:
```
\Projects\Telegram\TMessagesProj\jni\sqlite\sqlite3.c
Error:(30879, 42) error: 'mmap' undeclared here (not in a function)

```
Here is the related part in sqlite3.c:
```
#if !defined(SQLITE_OMIT_WAL) || SQLITE_MAX_MMAP_SIZE>0
  { "mmap",         (sqlite3_syscall_ptr)mmap,            0 },
#else
  { "mmap",         (sqlite3_syscall_ptr)0,               0 },
#endif
```
Is there any idea why does this happen?

**Comment by thermatk** [comment]
you're using upstream code?

(ndk r14b)

**Comment by nefrin79** [comment]
yeas, cause i'm having problems with foss version too. 
( `Android NDK: ERROR:E:Android.mk:avutil: LOCAL_SRC_FILES points to a missing file `)
But in this case I need hockeyapp implemention completely.
So i need to use the upstream code.
I use ndk r15c.

**Comment by Mran** [comment]
have you solved this problem?
