### ISSUE TITLE
Cannot Play voice messages.

### ISSUE THREAD

**Issue by kokoko3k** [Telegram-FOSS-Team/Telegram-FOSS#208]
I'm running telegram from F-Droid repo; Version 4.6.0 (11555)
I can record voice messages, but when i try to play them back, nothing happens; the slider does not advance.

Logcat shows the following:
```
I/str_params(  306): key: 'bgm_state' value: ''
E/MediaPlayerService(  306):   error: -2147483648
E/MediaPlayer( 6835): Unable to create media player
```
Other audio files like mp3 do play without problems.
My device is an asus zenfone ze551ml, running stock 5.01 lollipop.

Telegram from Play store works as expected.

Did something changed? I don't use voice messages a lot, but i'm sure they worked in the past.

**Comment by thermatk** [comment]
#198 #201 
and it's all fixed, but fdroid doesn't build it for almost a month now 😢

**Comment by kokoko3k** [comment]
Ok, thank you!

**Comment by thermatk** [comment]
Let's leave it, so we stop getting duplicates

**Comment by thermatk** [comment]
Update released, should be fixed
