### ISSUE TITLE
[REQUEST] Please update the F-Droid repo with latest version

### ISSUE THREAD

**Issue by nezorflame** [Telegram-FOSS-Team/Telegram-FOSS#209]

**Comment by nezorflame** [comment]
F-Droid still lists 4.6.0 as the latest version, although 4.6a is here for a while already.

**Comment by Bubu** [comment]
Build problems on F-Droid side :-(.
We can't do anything here but wait right now.

**Comment by nezorflame** [comment]
I see, feel free to close this then. Thanks for the answer.

**Comment by Bubu** [comment]
Let's leave this open for visibility until it's sorted out.

**Comment by elvecio** [comment]
There is a way to download  the apk somewhere? (out f-droid and of course google version)
It is more than a month that this problem ( https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/193 ) exists, it is complicated to live with this situation, even more so if the rest of your family lives in another continent. For listen to the audio messages I have to get home and turn on the desktop version in the computer. Really, it's not easy.

**Comment by thermatk** [comment]
@elvecio the version downloaded from fdroid should be replaced by a new version built by fdroid, because of signatures. If reinstall is an option, it would be better to downgrade to 4.2.1 from fdroid than me sharing another apk with my signature, no?
@Bubu what would you say if in the future I attach a beta apk to releases, which one can install alongside the normal? Really a sad situation when a quick and easy fix is being delivered a month already 😭

**Comment by elvecio** [comment]
' a beta apk to releases, which one can install alongside the normal'
I approve 👍 :-)

**Comment by thermatk** [comment]
@elvecio try it then
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/releases/tag/v4.6a

**Comment by elvecio** [comment]
@thermatk  it works 👍 thanks 🎃

**Comment by mastad0n** [comment]
What about running our own F-droid repo?

Like microG: https://microg.org/fdroid.html

**Comment by beerisgood** [comment]
What about just wait until F-Droid fix it?! Maybe help them to fix it faster

**Comment by Mikaela** [comment]
Is there any issue that can be upvoted and followed at F-Droid's?

**Comment by mastad0n** [comment]
@Mikaela https://gitlab.com/fdroid/fdroidserver/issues/437

@beerisgood feel free to help.

**Comment by thermatk** [comment]
https://gitlab.com/fdroid/fdroidserver/issues/437
