### ISSUE TITLE
Words are overlapped on portrait mode (but not on landscape mode)

### ISSUE THREAD

**Issue by moshpirit** [Telegram-FOSS-Team/Telegram-FOSS#210]
Telegram v.4.6.0 (F-droid) on Android 7.1.2

[Screenshot here](https://imgur.com/JBeKzIA)

I shared the message with the group chat too.

**Comment by thermatk** [comment]
As I can't reproduce immediately, I don't know whether it affects the 4.6a. Could you try with the beta in the release section please?

**Comment by moshpirit** [comment]
The problem persists: [Up: Telegram Beta, Down: Telegram stable](https://i.imgur.com/Ynb7wWg.png)

**Comment by thermatk** [comment]
@moshpirit v4.9?

**Comment by moshpirit** [comment]
As I can tell, the bug is not present for now, if it appears again, I'll just come back here :) thanks for the support!
