### ISSUE TITLE
add orbot connection support

### ISSUE THREAD

**Issue by herotux** [Telegram-FOSS-Team/Telegram-FOSS#211]
please add orbot connection support to telegram foss use the telegram more securely and also help peoples acces them even if it’s normally blocked(like iran) or monitored  .

with Orbot Helper:
we can do this by add an option that by enable it check if Orbot (Tor for Android) is installed, and whether it is currently running or not. Allows your app to request Orbot to start (user is prompted whether to start or not). Finally, it can show a user prompt to install Orbot, either from Google Play, or via direct APK download from torproject.org or the guardianproject.info site.

https://guardianproject.info/code/onionkit/
https://github.com/guardianproject/NetCipher

**Comment by thermatk** [comment]
Isn't orbot already working with proxies?

**Comment by biomanw** [comment]
Its work ,but add an option to force app use orbot and run it directly if installed its that i want to say.

**Comment by abesty** [comment]
I think you can setting manually in Socks proxy inside telegram apps or force by apps such OrWall.
