### ISSUE TITLE
Unsopported content

### ISSUE THREAD

**Issue by susobaco** [Telegram-FOSS-Team/Telegram-FOSS#212]
Hi. When I try to share a "queet" from the "[twidere](https://github.com/TwidereProject/Twidere-Android)" client, I get this message, while if I do it from the web browser, for example, I can share it without any problem. Is it a bug? I seem to remember earlier if I could share from "twidere".
If I share from twidere to "[Conversations](https://github.com/siacs/Conversations)", there is no problem

**Comment by thermatk** [comment]
Update released, should be fixed
