### ISSUE TITLE
[Feature Request] Option to set sticker size

### ISSUE THREAD

**Issue by ArmeF97** [Telegram-FOSS-Team/Telegram-FOSS#213]
Add an option that let decide the user how big a sticker is drawed on screen

It's possibile to set the size of the text in telegram, so why not stickers? I, in a fork of mine, called CryptoGram, have set stickers as small

https://github.com/ArmeF97/CryptoGram2/commit/5977b3894b08136e4119cb04c1604e4500d0cf4c#diff-f64f47a0a8bd9c7a24ab9480c4c3871a see only the file TMessagesProj/src/main/java/org/messenger/ui/Cells/ChatMessageCell.java in the linked commit, you'll see I simpled divided by 2 the max height and width for the sticker. So there can be a option in telegram 

:tada:

**Comment by Bubu** [comment]
I don't think this is in scope for telegram Foss, so closing this.
