### ISSUE TITLE
Telegram X source

### ISSUE THREAD

**Issue by ali-mahmoodvand** [Telegram-FOSS-Team/Telegram-FOSS#214]
Please update repository for Telegram X source code
https://telegram.org/blog/telegram-x
@DrKLO

**Comment by thermatk** [comment]
Please tell me where it is :wink:

**Comment by ali-mahmoodvand** [comment]
New version of Telegram

**Comment by thermatk** [comment]
The source

**Comment by ali-mahmoodvand** [comment]
Ha ??

**Comment by Peque** [comment]
@thermatk Would it make sense to leave this issue open just to track any possible updates on this matter? For people to subscribe to it or share any updates that they find. :blush:

Maybe (I don't know), the fact that Telegram is promoting the "X" version means the current version is being discontinued. If that was the case, sooner or later Telegram-FOSS might have to switch to that source code base? I am assuming they will continue not supporting a free source code nor really accepting contributions/feedback from the community.

**Comment by thermatk** [comment]
#217 👍
