### ISSUE TITLE
How does Telegram-FOSS do push notifications?

### ISSUE THREAD

**Issue by schemar** [Telegram-FOSS-Team/Telegram-FOSS#216]
Does Telegram-FOSS rely on push notifications? If so: how? What is the delay?

Nextcloud Talk is trying to figure out a way no do push, especially for incoming calls: https://github.com/nextcloud/talk-android/issues/58

**Comment by Bubu** [comment]
Well, this is not going to be useful for nextcloud-tallk. TG has a second push implementation completely independent of google play. I only ever used that, there is basically no delay to pushes. But there is of course a server-side component to this, which is not open source.

**Comment by Bubu** [comment]
To add, they do pushes form telegrams servers directly in case your are not using GCM/FCM.

**Comment by schemar** [comment]
Okay, thank you for the quick reply. So Telegram implemented a proprietary push protocol where the server implementation is closed, right? Too bad :(

**Comment by Bubu** [comment]
> So Telegram implemented a proprietary push protocol where the server implementation is closed, right?

Well it's basically a tcp socket being kept open and a lot of keep-alive dances around that. So 'protocol' might be a bit misleading, but in principle yeah. 

If you want to look at what they are doing client-side it's basically all here: https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/v4.6/TMessagesProj/jni/tgnet/ConnectionsManager.cpp (search for push)

I only skimmed it so far.

**Comment by thermatk** [comment]
An important point to note is that it's useless for new projects anyway:
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/172
We are forced to find some new cool unified solution for FOSS-ROM users, and it better not be just disabling the restrictions, but who knows.

**Comment by schemar** [comment]
Thank you!

**Comment by schemar** [comment]
@Bubu you offered in https://github.com/nextcloud/talk-android/issues/58 to create a project for an independent, open push service. While I very much like the idea and am definitely willing to contribute, I wonder whether this would actually help Telegram-FOSS, as you depend on the Telegram server implementation, right?

Anyways, the expertise from Telegram-FOSS would be very helpful, as I know that you spent a lot of effort into battery optimization on the client device 🙂

**Comment by ildar** [comment]
I see some progress going on:
https://f-droid.org/en/2020/02/03/openpush-talk.html

>

**Comment by moradi-morteza** [comment]
hi, i am woundering to know how telegram push service work? they open a connection to their servier in android background, but that pocess will not close by android platform, how they do that? when you create a service in background it closed by android after you close the app, but telegram services or connection is still open!
please give me data if you know
thanks

**Comment by moradi-morteza** [comment]
> > So Telegram implemented a proprietary push protocol where the server implementation is closed, right?
> 
> Well it's basically a tcp socket being kept open and a lot of keep-alive dances around that. So 'protocol' might be a bit misleading, but in principle yeah.
> 
> If you want to look at what they are doing client-side it's basically all here: https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/v4.6/TMessagesProj/jni/tgnet/ConnectionsManager.cpp (search for push)
> 
> I only skimmed it so far.

did you find anything about tgnet? how it work on background presistently?
