### ISSUE TITLE
"/" forwards slash commands are linked and visible in general chat. 

### ISSUE THREAD

**Issue by meadowhb** [Telegram-FOSS-Team/Telegram-FOSS#218]
Expected behavior is same as IRC clients.

**Comment by Bubu** [comment]
I'm pretty sure that's not a Telegram-FOSS issue but one that is present in upstream telegram.

Will close unless someone disagrees with this assessment.

**Comment by meadowhb** [comment]
Can you share link for appropriate repo pls, thank you.

**Comment by Bubu** [comment]
It's in our readme: https://github.com/DrKLO/Telegram

there is no issue tracker there though... You'll have to reach them via support chat or something to report bugs.
