### ISSUE TITLE
Is there some release date for version 4.8?

### ISSUE THREAD

**Issue by p4t0g3n0** [Telegram-FOSS-Team/Telegram-FOSS#219]
Any info about a release date for version 4.8 from FOSS team  or DrKLO

**Comment by thermatk** [comment]
How are we supposed to know? :joy:
Let's leave this one open

**Comment by Younes-L** [comment]
Anyone knows what happened right after 3.10 ?? Seems drklo got lazy shortly after (5% chance) , unless it's <insert conspiracy theory> (95% chance) 😂

**Comment by r4sas** [comment]
Please review, found via search: https://github.com/tgapps/android
