### ISSUE TITLE
Feature Request: Proxy

### ISSUE THREAD

**Issue by ti-wa** [Telegram-FOSS-Team/Telegram-FOSS#22]
Hi,
I think it would be pretty useful to have network proxys on Telegram.

Thanks!

**Comment by fazlerabbi37** [comment]
@stefan-niedermann [DrKLO/Telegram](https://github.com/DrKLO/Telegram) seems to have no issue tab. How would we create an issue for it?

**Comment by stefan-niedermann** [comment]
Yeah, they closed it some time ago. I think you won't have much choice but contact them via twitter or so... 😒
