### ISSUE TITLE
Possible plagiarism 

### ISSUE THREAD

**Issue by twentz** [Telegram-FOSS-Team/Telegram-FOSS#220]
I came across this app "Nepali Messanger" which is an exact copy of Telegram plus extra ads.  I've reported the app in the play store but i dont know what really can be done? Any ideas? And yes the dev knows and acknowledges that his app is s a copy of telegram but says open source can be copied. Is this true? 

See pic,  and the reply to first comment is where he acknowledges but instead threatens to sue the guy (not me btw) who points it out. 
![screenshot_2018-03-06-13-24-19-23](https://user-images.githubusercontent.com/37100977/37020908-ab8b7094-2145-11e8-822f-3c8db9e59b2b.png)

**Comment by Poussinou** [comment]
@thermatk 

Just to let you know, there is another copy of FOSS Telegram just [here](https://play.google.com/store/apps/details?id=org.viento.colibri). No consideration of GNU GPL v2 in this one.
