### ISSUE TITLE
Add a more useful default zoom and center for share location view

### ISSUE THREAD

**Issue by Bubu** [Telegram-FOSS-Team/Telegram-FOSS#221]
I don't have network location on my phone, so it takes a few seconds to get a GPS fix after selecting the share location option. Of I'm indoors I'm out of luck anyway.

So more often than not I manually send some location to other people. The problem with this is that without a location fix the osmdroid map starts at max zoom somewhere in the south of antarktika. This always takes a while to  zoom ou and orient myself on the map.

We could easily choose a more useful default, the question is what is best to do.

* Save some last used coordinates/zoom into the preferences?
* Just view a zoomed out world map?
* some other arbitrary place?

**Comment by thermatk** [comment]
To use any microg providers, one needs the play store version. Here I ported to system location API, so if we want to save something, it needs to be manually added

**Comment by ildar** [comment]
iirc UnifiedNLP can be used with GApps.

**Comment by thermatk** [comment]
The code using fused location provider is in the removed play services blob

**Comment by ildar** [comment]
ok but 4.6.0c behavior is irritating. Will it be fixed by the next release?

**Comment by thermatk** [comment]
I zoomed in a bit :+1:

**Comment by ildar** [comment]
aha! waiting in F-Droid channel. Thanks!

**Comment by thermatk** [comment]
restored upstream behaviour
