### ISSUE TITLE
Internet connection not detected immediately via USB OTG Ethernet adapter

### ISSUE THREAD

**Issue by lope** [Telegram-FOSS-Team/Telegram-FOSS#227]
When my Samsung Galaxy S5 CM13 Android 6 phone has been on Wifi on Telegram I can make calls.
Then I activate aeroplane mode.
I plug in a USB OTG cable that's connected to a USB Ethernet adapter.
The USB Ethernet icon appears on my phone, and I can send text messages on telegram. But I cannot make calls immediately.
So I switched to Whatsapp and made a call via Whatsapp.
Then After a long time I switched back to Telegram, still on the USB Ethernet connection, and then I could make a telegram voice call.

So it seems that Telegram is slow to detect that the internet is connected via USB Ethernet.

**Comment by Bubu** [comment]
This has nothing to do with the Telegram-FOSS fork. We don't have the capacities to provide general support for this version so we can only focus on bugs that are either introduced by the changes we made or things that improve privacy in some way. Please contact telegram developers and hope they release the sources if they happen to fix a bug here.
