### ISSUE TITLE
Wrong version of Telegram-FOSS on F-Droid

### ISSUE THREAD

**Issue by yvan-sraka** [Telegram-FOSS-Team/Telegram-FOSS#229]
Hello,

The version of [Telegram on F-Droid](https://f-droid.org/packages/org.telegram.messenger/) does not match the version on the Google Play Store ...

Do you know who manages the publication of the app?

Thank you in advance,

**Comment by Bubu** [comment]
@yvan-sraka Telegram has not released any source code for versions newer than in this repository/F-Droid.

Please bug Telegram/Durov on twitter or anywhere else you can find about it!
