### ISSUE TITLE
If can't login without proxy, also can't set proxy before login

### ISSUE THREAD

**Issue by thermatk** [Telegram-FOSS-Team/Telegram-FOSS#230]
In the wake of blocks in Russia, the built-in support for socks5 proxy became an important feature for a big amount of users, yet one can only set up proxies after the login sequence has been done. Since Telegram obviously can't login with its servers blocked, it is a closed circle.
The only way is to use a VPN for login even if the main approach for censorship circumvention will be a proxy afterwards.

**Comment by thermatk** [comment]
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/commit/6a3827a73e1c483ad251610a6fbdae6e34cec6e6 fixed

**Comment by thermatk** [comment]
@n8fr8 patches/PRs would be accepted for this, but bear in mind the whole internet connection stuff is hidden in native code here

**Comment by MikePryadko** [comment]
This problem still exists in `iOS` client! (version `10.8.2`)
