### ISSUE TITLE
backdoors?

### ISSUE THREAD

**Issue by hotlittlewhitedog** [Telegram-FOSS-Team/Telegram-FOSS#231]
Hi Bubu, all,

For info: 
https://www.developpez.net/forums/attachments/p370849d1523951107/systemes/securite/france-gouvernement-va-lancer-propre-application-messagerie-chiffree/damien.jpg/

Seems that Telegram has many backdoors.

https://www.developpez.net/forums/d1841810/systemes/securite/france-gouvernement-va-lancer-propre-application-messagerie-chiffree/#post10167554

Use Google Translate... for English.

**Comment by thermatk** [comment]
Hi @hotlittlewhitedog 
This would mean the usual trick of intercepting sms for login and reading cloud chats afterwards
It's not a backdoor, it's an abused feature 😆 2fa and secret chats fix that
