### ISSUE TITLE
Incorrect color for one heart icon 

### ISSUE THREAD

**Issue by ShalokShalom** [Telegram-FOSS-Team/Telegram-FOSS#233]
This icon is supposed to be purple and appears so in other clients: 

<a href="http://funkyimg.com/view/2FdAy" target="_blank"><img src="http://funkyimg.com/i/2FdAy.png" alt="Free Image Hosting at FunkyIMG.com" border="0"></a>

**Comment by Bubu** [comment]
What's the problem here? This is just using the [Twemoji](http://twitter.github.io/twemoji/) set and they chose to make this one with a read background.

**Comment by ShalokShalom** [comment]
No, it is purple, in the iOS client, as said.
Send this emoji onto iOS and it shows purple.
Maybe, this is an issue on their side.

**Comment by thermatk** [comment]
https://emojipedia.org/heart-decoration/
twitter doesn't categorize it with other symbols

**Comment by ShalokShalom** [comment]
I raised an issue on their repo
