### ISSUE TITLE
Incorrect displayed heart icons 

### ISSUE THREAD

**Issue by ShalokShalom** [Telegram-FOSS-Team/Telegram-FOSS#234]
It displays correct on the iOS client: 

<a href="http://funkyimg.com/view/2FdCf" target="_blank"><img src="http://funkyimg.com/i/2FdCf.png" alt="Free Image Hosting at FunkyIMG.com" border="0"></a>

**Comment by Bubu** [comment]
This is a performance optimization done in upstream code. The emoji-replacer only runs for the first 30 or so emojis, after that the black hearts are you native Android emojis.
