### ISSUE TITLE
Stickers not being displayed

### ISSUE THREAD

**Issue by daltonfury42** [Telegram-FOSS-Team/Telegram-FOSS#240]
I just installed Telegram FOSS on my phone running LineageOS, and everything is working great except stickers. Stickers don't get rendered.

**Comment by thermatk** [comment]
That's not our bug 99%
Maybe it was a DC problem or country censorship?

**Comment by utack** [comment]
Question that is slightly related:  
How hard would it be to download all full-res stickers in a pack, when added?  
It would certainly save data in the long run, and make stickers work when the servers are down or on poor connections like Edge
