### ISSUE TITLE
BoringSSL

### ISSUE THREAD

**Issue by thermatk** [Telegram-FOSS-Team/Telegram-FOSS#246]
Somehow upstream claims to use BoringSSL, but when I tried to do the same, it turned out that BoringSSL never included the required AES IGE encryption. Very strange :confused: 
The attempt will remain in a [branch](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/tree/boringssl).

**Comment by thermatk** [comment]
![default](https://user-images.githubusercontent.com/2287483/41729187-e0526a30-7578-11e8-9547-3130f894806a.png)

Mystery solved, kind of

**Comment by thermatk** [comment]
The next mystery is to determine which commit is used here

**Comment by Bubu** [comment]
Something very close to https://github.com/google/boringssl/commit/3c92e80d7a9ff939f030f33053dac7ca9d9646b6

Only aes ige stuff seems really added, some headers added back in from openssl to work around libtgvoip actually wanting to build against this.

**Comment by thermatk** [comment]
medal goes to @Bubu
