### ISSUE TITLE
Sharing images to Telegram duplicates the caption

### ISSUE THREAD

**Issue by Streetwalrus** [Telegram-FOSS-Team/Telegram-FOSS#247]
When sharing an image from Firefox, the source URL is included as a caption. But with the current version of tg-foss, the caption is duplicated into a second message, in addition to being attached to the image itself.
The correct behavior would be to send only one message: the shared picture with the URL as a caption.
I know this has been fixed upstream, but it is quite annoying and I expect this to be a pretty simple fix until we get a proper source release.

**Comment by Streetwalrus** [comment]
Why would this require the upstream source to fix? I think I've already found the problem:
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/1ea6efbc594ea89b200d89a215c843d6a412d22d/TMessagesProj/src/main/java/org/telegram/ui/LaunchActivity.java#L1759-L1785
Here, if a video is being shared, `sendingText` gets nulled out, which prevents a text message from being sent, but it doesn't do it for photos, and it always tries to send a text message before handling the other media types.

**Comment by thermatk** [comment]
I'm adding this label because it's fixed upstream, as you shared. 
You're suggesting L1768 to be `sendingText = null; ` ?
Seems ok

**Comment by Streetwalrus** [comment]
Yeah I think that would do it. For completeness's sake, you could also move lines 1772-1774 below the rest and add that null assignment to every other case, but I don't think it's as important considering they don't handle captioning.

**Comment by Streetwalrus** [comment]
Is there any particular reason not to patch this and ship it, considering how trivial it is? I can submit a pull request if you want. This bug is pretty annoying as I run into it all the time.

**Comment by thermatk** [comment]
Fixed on master
Main reason would be lack of enthusiasm due to lack of new sources, always expecting the new source release to finally come someday soon
And its potential diff size grows, so whatever work we bury into the old code base, it must theoretically be less relevant with every passing day. Bugs will be fixed and features will need to be completely reimplemented :sob:  
Also, I'm trying to clean Chromium and find a job atm :joy:

**Comment by Streetwalrus** [comment]
Fair enough. Thanks for fixing it and good luck with your job search. :)
