### ISSUE TITLE
Notifications are sent intermittently

### ISSUE THREAD

**Issue by lanyla** [Telegram-FOSS-Team/Telegram-FOSS#252]
I have iOS 11.4.1 and iPhone 8+. Notifications worked perfectly fine until I updated OS to the aforementioned version. Now they do not appear on screen or appear intermittently if Telegram app is not running.  When I open app, it writes Connecting.. then Updating and after that I see a dozen dialogues and messages that I missed. 

Could you please look into the issue?

**Comment by DC7IA** [comment]
You're commenting on the project of the open source Android version, not the iOS  client.

This is not droid you're looking for.

**Comment by Bubu** [comment]
@DC7IA thanks :)
