### ISSUE TITLE
New location preview tiles (v4.9) are not attributed

### ISSUE THREAD

**Issue by Robot8A** [Telegram-FOSS-Team/Telegram-FOSS#254]
I guess the data comes from OpenStreetMap, in which case it should be attributed. This also happens in the official Telegram app, but I don't know where to open an issue for them.
![image](https://user-images.githubusercontent.com/19521377/44021468-2c50acb8-9ee5-11e8-9a9c-99b9ad03a354.png)
![image](https://user-images.githubusercontent.com/19521377/44021473-313a34a6-9ee5-11e8-8d46-b6c152ec2fe9.png)

**Comment by thermatk** [comment]
It's an upstream bug, but I consider it solved in our case: when you tap the static preview, you get OSM again and I have added attribution there already, so we're covered I hope. For upstream it's more of a problem, because the preview leads to a completely independent Google map

**Comment by thermatk** [comment]
Notified upstream dev, suggested to include at least a small reference in the corner.
