### ISSUE TITLE
Telegram 4.9.1 source released

### ISSUE THREAD

**Issue by octoghost** [Telegram-FOSS-Team/Telegram-FOSS#258]
https://github.com/DrKLO/Telegram/commits/master
>- New “Exceptions” section in Notification settings that lists all your chats with custom notifications.
>- Telegram Passport now supports more types of data including translated versions of documents.
>- Improved password hashing algorithm to better protect Telegram Passport data.
>- Export your chats using the latest version of Telegram Desktop.

**Comment by thermatk** [comment]
Merged, verifying

**Comment by octoghost** [comment]
On F-Droid now, thank you!
