### ISSUE TITLE
build boringssl

### ISSUE THREAD

**Issue by emjeykm** [Telegram-FOSS-Team/Telegram-FOSS#259]
hi when i try to build boringssl get this error

./build_boringssl.sh
Configuring...
CMake Error at CMakeLists.txt:10 (project):
  Running

   'D:/Android/sdk/ninja' '--version'

  failed with:

   Access is denied

-- Configuring incomplete, errors occurred!
See also "D:/Android/AndroidStudioProjects/Telegram-FOSSUpdateto491/TMessagesProj/jni/boringssl/build/armeabi-v7a/CMakeFiles/CMakeOutput.log".

**Comment by ildar** [comment]
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues?utf8=%E2%9C%93&q=is%3Aissue+windows
looks like Windows isn't a great platform for this project.
@devs: worth mentioning in README?

**Comment by n00bus** [comment]
"6. Building under Windows may be problematic and won't be fixed"

**Comment by emjeykm** [comment]
i got this error in linux
/bin/bash^M: bad interpreter: No such file or directory

**Comment by ildar** [comment]
what did you do exactly? Did you git-clone in Linux?

**Comment by emjeykm** [comment]
not git-clone in windows install linux use file in there

**Comment by emjeykm** [comment]
ig this in linux

./build_boringssl.sh
Configuring...
CMake Warning at /opt/android-ndk-r16b/build/cmake/android.toolchain.cmake:63 (message):
  Using custom NDK path (ANDROID_NDK is set): /opt/android-ndk-r16b/
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:10 (project)


CMake Error at CMakeLists.txt:10 (project):
  Running

   '/opt/ninja-linux/' '--version'

  failed with:

   Permission denied


-- Configuring incomplete, errors occurred!
See also "/home/emjeykm/Telegram-FOSS/TMessagesProj/jni/boringssl/build/armeabi-v7a/CMakeFiles/CMakeOutput.log".
