### ISSUE TITLE
Problem on compiling

### ISSUE THREAD

**Issue by enolp** [Telegram-FOSS-Team/Telegram-FOSS#265]
I'm trying to compile the code but running ./build_ffmpeg_clang.sh shows me an error:

"GNU assembler not found, install/update gas-preprocessor"

I installed https://git.libav.org/?p=gas-preprocessor.git;a=blob;f=gas-preprocessor.pl;h=c56301c50131dd73f0580a6596c10608eaaeb1fe;hb=HEAD on /usr/local/bin but it doesn't work neither. Right now I'm using Ubuntu 18.04 and I installed all dependencies riquired (ndk, golang and ninja)

Any ideas?

**Comment by thermatk** [comment]
Extremely strange, never had to install any gas-preprocessors. I'm building without issues under Manjaro, fdroidserver is building under Debian Jessie

Maybe I already had all build essentials, try the respective meta packages?

**Comment by daniellandau** [comment]
It's still a problem on my up-to-date Arch system. The following patch fixes it for me.

```
diff --git a/TMessagesProj/jni/build_ffmpeg_clang.sh b/TMessagesProj/jni/build_ffmpeg_clang.sh
index c71e787eb..914b6b09e 100755
--- a/TMessagesProj/jni/build_ffmpeg_clang.sh
+++ b/TMessagesProj/jni/build_ffmpeg_clang.sh
@@ -163,7 +163,7 @@ ARCH=arm64
 CPU=arm64-v8a
 OPTIMIZE_CFLAGS=
 PREFIX=./build/$CPU
-ADDITIONAL_CONFIGURE_FLAG="--enable-neon --enable-optimizations"
+ADDITIONAL_CONFIGURE_FLAG="--enable-neon --enable-optimizations --disable-asm"
 build_one
 
 
@@ -176,7 +176,7 @@ ARCH=arm
 CPU=armv7-a
 OPTIMIZE_CFLAGS="-marm -march=$CPU"
 PREFIX=./build/armeabi-v7a
-ADDITIONAL_CONFIGURE_FLAG="--enable-neon"
+ADDITIONAL_CONFIGURE_FLAG="--enable-neon --disable-asm"
 build_one
 
 #x86 platform
```

**Comment by enolp** [comment]
Wow, epic necro-bump but I appreciate your fix. Right now, I use Arch Linux as my main OS so this might help.

Let's see if I can build it.
