### ISSUE TITLE
Notification Question 

### ISSUE THREAD

**Issue by mudlee** [Telegram-FOSS-Team/Telegram-FOSS#266]
Hi guys!

How did you solve that telegram-foss can run in background and android won't kill it? I mean is that a background service or what? If so, how it wont be killed?

**Comment by thermatk** [comment]
Hi!
You kind of answered your own question in the title of your post
[backstory here](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/172)
or the[ file you may as well see when you tap the notification](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/master/Notifications.md)

**Comment by moradi-morteza** [comment]
i have the same question but still could not find the answer! please clear the context
