### ISSUE TITLE
[ENCHANTMENT]What about making VagrantFile + Ansible support for fast & easy deployment of VM builder?

### ISSUE THREAD

**Issue by Sudokamikaze** [Telegram-FOSS-Team/Telegram-FOSS#268]
Howdy! I'm thinking about such idea, because not of all users want to mess with those scripts

So I came to idea of making Vagrantfile for deploying VM in Virtualbox/KVM/HyperV and ansible will do the trick of installing software + deps + compile everything with handling errors 

I have an experience with Ansible & VMs(such ESXi/QEMU+KVM via libvirtd/HyperV and ofc Virtualbox) so I could make these playbooks but I'm not sure yet about Vagrant, but ofc I'd like to try :)

**Comment by Bubu** [comment]
I'm not quite sure about the goal of this ticket... but if it's about having a build environment for android apps you've basically just described the f-droid infrastructure... :-p.

Hvae a look here: https://gitlab.com/fdroid/fdroidserver

**Comment by Sudokamikaze** [comment]
Oh I see. Main goal is to archive best efforts with making APK for users/developers locally without messing up with scripts/etc

**Comment by Sudokamikaze** [comment]
Anyway, let me know if you want this feature :(
