### ISSUE TITLE
Telegram is automatically started when I use a share button in antother app

### ISSUE THREAD

**Issue by Massedil** [Telegram-FOSS-Team/Telegram-FOSS#269]
Telegram is automatically started when I use a share button in antother app even if I don't choose to share with Telegram app.

I can see that telegram is started because there is the notification icon that appears.

I don't know if there is a good reason that the app starts, but it stays opened after.

How to avoid that ?

![2](https://user-images.githubusercontent.com/20357783/46886533-7bd98980-ce5b-11e8-8edc-aeb11cf5e31a.png)

**Comment by thermatk** [comment]
duplicate #270

**Comment by Massedil** [comment]
I think it is not really linked to the issue #270. And now that #270 is resolved (the service is stopped when the app is not in foreground), there is still a connection to Telegram when I share something (because I receive new messages at this time).
