### ISSUE TITLE
Suggestion : recover the better YouTube inline player from older telegram

### ISSUE THREAD

**Issue by Younes-L** [Telegram-FOSS-Team/Telegram-FOSS#277]
Telegram dumbed down their YouTube player with the 4.3 update to comply with play store policy, I think you guys can do otherwise ;)
AFAIK it's just a matter of recovering the old code from version 4.2 , I'd make a pr but I'm not familiar with this so idk where to find the targeted code

**Comment by thermatk** [comment]
I don't think so.
For one, YouTube recently changed a bit and newpipe, youtubedl, etc stopped working. No one here can support it
