### ISSUE TITLE
[Bug] Emoji 11 doesn't display

### ISSUE THREAD

**Issue by ArmeF97** [Telegram-FOSS-Team/Telegram-FOSS#278]
It seems that Telegram Foss is not updated with unicode standard, Emoji 11, as of 5 june 2018

**Comment by utack** [comment]
Twitter already added them, if I understood correctly it is now possible to correctly "map" them by looking at how the official 5.0 client sends them  
https://github.com/twitter/twemoji/commit/0dd7c46f41837f1aff7ae930e1993e20d66ddd62

**Comment by Bubu** [comment]
This should come via upstream source code release. It has nothing to do with the protocol and is only local to the client displaying them.

**Comment by ArmeF97** [comment]
I get it but the app is yours, and you are using an outdated version of Unicode, isn't this a missing feature? You can always grab the last one from Twitter's emoji, that are opensource
