### ISSUE TITLE
"Send by Enter" should be separate for visual keyboard and hardware keyboard

### ISSUE THREAD

**Issue by JonasT** [Telegram-FOSS-Team/Telegram-FOSS#285]
"Send by Enter" are currently linked and should be separate for visual keyboard and hardware keyboard, for two reasons:

- The natural expected default for the visual keyboard for "Send by Enter" is "off" (which is the current default), which makes sense since there is a separate graphical button right above the keyboard to send. However, the natural default for a physical keyboard is "on" since that mirrors behavior of 99% of all desktop chat programs where you can just type a line and hit return/enter. It's really weird and confusing when that initially doesn't work

- It just doesn't make too much sense to link the position of visual keyboard buttons to whether I want to use CTRL/SHIFT on a hardware keyboard. "Send by Enter" makes kind of sense on the screen where the button is right there, but on the hardware keyboard there is no separate send button right next to anywhere, and using CTRL/SHIFT all the time is clumsy

I would also report this upstream (I assume it might have the same problem, the Play Store app I mean) but they don't have a bugtracker...

**Comment by JonasT** [comment]
@Bubu if I may ask, is this just the wrong place to file it? Or is there a chance if it's filed here (since it's definitely also present in the FLOSS version) that this gets forwarded? Because if this is not a useful place to get Telegram devs to know about this, then I really don't know what is

**Comment by JonasT** [comment]
(and I'm seeing other upstream-bug tickets that remained open, apparently because they're not fixed yet. Was this closed because it's actually fixed in a newer Telegram upstream version?)

**Comment by Bubu** [comment]
On January 23, 2019 4:10:42 PM GMT+01:00, JonasT <notifications@github.com> wrote:
>@Bubu if I may ask, is this just the wrong place to file it? Or is
>there a chance if it's filed here (since it's definitely also present
>in the FLOSS version) that this gets forwarded? Because if this is not
>a useful place to get Telegram devs to know about this, then I really
>don't know what is
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/285#issuecomment-456837749

We don't know either, sorry.

**Comment by Bubu** [comment]
On January 23, 2019 4:11:42 PM GMT+01:00, JonasT <notifications@github.com> wrote:
>(and I'm seeing other upstream-bug tickets that remained open,
>apparently because they're not fixed yet. Was this closed because it's
>actually fixed in a newer Telegram upstream version?)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/285#issuecomment-456838102

I just think it doesn't make a lot of sense tracking these here. We don't have any intention in fixing upstream bugs.

I guess if others want to contribute such fixes this is generally fine but so far this hasn't happened either.

**Comment by JonasT** [comment]
I'm always happy to be forwarded to an upstream bugtracker, or report form, or e-mail address, or whatever. This tracker was simply the highest up one in the chain I found. You already hinted at in the other ticket that you don't have any good contacts either, but if there's some place you can think of, let me know.

(Also I'm a bit surprised, doesn't this come up very frequently? How do other people report bugs that happen to be upstream, but still affect this project?)

I'm willing to report this anywhere it's necessary to get it fixed, this is really just the only place suitable I found so far
