### ISSUE TITLE
When doing Wifi outgoing call from Android to desktop on the other end, quality is bad

### ISSUE THREAD

**Issue by JonasT** [Telegram-FOSS-Team/Telegram-FOSS#286]
When doing a Wifi outgoing call from Android to desktop on the other end, quality is really bad - like, shortly-before-dropping-out voice call style with insane compression that almost strips out all consonants and a huge delay. If I do a desktop outgoing call (on Linux with the open-source telegram desktop) to the same target in the same wifi,  then I get absolutely stellar quality. Since normal voice calls and other apps on Android don't have this problem, this seems to be a Telegram bug.

I tested this on a Samsung Galaxy S4 mini (with lineageos), and a friend of mine had the same issue on one of the nexus phones (with stock google ROM), so it doesn't seem to be necessarily hardware-related, or if it is then not one single device or ROM.

My friend tried this with Telegram Play Store/upstream though, so the bug seems to be in both versions. However, I haven't reported this to upstream yet since I don't know how (no bugtracker, support chat is unhelpful)

**Comment by Bubu** [comment]
Well, if this is an upstream problem, we really can't and don't want to fix it here...

**Comment by Bubu** [comment]
On January 23, 2019 4:12:53 PM GMT+01:00, JonasT <notifications@github.com> wrote:
>How can I let upstream know about this? The support chat I already
>tried, you get people trying to "help" and when I suggested some things
>should be forwarded I just got silence
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/286#issuecomment-456838557

We, don't know, sorry. We have no communication channel with upstream.

**Comment by JonasT** [comment]
Ok. That seems a bit sad, given I saw some comments (e.g. from @thermatk ) that made me hope otherwise, but oh well. Thanks for letting me know
