### ISSUE TITLE
5.2.1

### ISSUE THREAD

**Issue by theel0ja** [Telegram-FOSS-Team/Telegram-FOSS#287]
https://github.com/DrKLO/Telegram/commit/ae90d60e0c34e9ceb20f1a9f7edaf9c85044ed7e

**Comment by thermatk** [comment]
Exactly

**Comment by r4sas** [comment]
Seems like f-droid sources pull is disabled for package (https://f-droid.org/wiki/page/org.telegram.messenger):
>We have the current version of this app. (Check mode: None) (Auto-update mode: None)
>The current (recommended) version is 4.9.1 (version code 13580).

When it will be avaliable on f-droid?
