### ISSUE TITLE
Make minimized notification

### ISSUE THREAD

**Issue by tom-rade** [Telegram-FOSS-Team/Telegram-FOSS#290]
I'm fine with the push notification. But don't make it a full notification. Other apps show small/thin notications when they are minimized.

**Comment by thermatk** [comment]
@tom-rade surely would be great, but you have to minimize it yourself, otherwise it makes no sense
as already said in Notifications.md

> Sadly, if the app would set the notification to lower priority (to hide it a bit in the lower part of the notification screen), you would immediately get a system notification about Telegram "using battery", which is confusing and is the reason for this not being the default. Despite Google's misleading warnings, there is no difference in battery usage between v4.6 in "true background" and v4.9+ with notification.
