### ISSUE TITLE
Add support for accessibility so apps like Oversec works

### ISSUE THREAD

**Issue by beerisgood** [Telegram-FOSS-Team/Telegram-FOSS#294]
So we can use the app Oversec and also voice helper apps.

Oversec problem info: https://help.oversec.io/setup/per-app-config/org-telegram-messenger/

Oversec at F-DROID: https://f-droid.org/packages/io.oversec.one/

**Comment by r4sas** [comment]
I think that is not Telegram-FOSS issue, so write @DrKLO.

**Comment by beerisgood** [comment]
How can I write them this issue? They closed whole issues <.<

**Comment by c33s** [comment]
@beerisgood you can only write to them via telegram. 

settings >  ask a question (in the support  section). if you are lucky, they pass your issue to the developers. but i won't count on it
