### ISSUE TITLE
Bettergram-based version?

### ISSUE THREAD

**Issue by dimqua** [Telegram-FOSS-Team/Telegram-FOSS#298]
https://github.com/bettergram/bettergram-android

Bettergram is an unofficial Telegram client built by team behind LiveCoinWatch.

This fork has the following features:
- Separate **tabs** for favorites, groups, private messages, and announcements;
- Increased **pin limit** to 50 chats;
- Track over 2,000 cryptocurrency prices, built-in cryptocurrency news and video feeds.

**Comment by fcore117** [comment]
Most people have no need for these features, especially cryptocoins. Telegram is fast bloat free communication app not some cryptocurrency center.

**Comment by dimqua** [comment]
There is no need to incorporate all their features. But it's probably possible to use their patches for tabs in the interface. AFAIK, it's a desirable feature for many users.

**Comment by M86xKC** [comment]
@dimqua I agree, if possible to add favourite groups/channels/pms or increase the number of pin messages, also separating channels/groups from regular messages will be a nice addition!

**Comment by DI555** [comment]
First 2 points(from topic) of features are great! And would be nice to be implemented(or just port from their sources)!

**Comment by ildar** [comment]
Why not just build it into F-Droid separately?

**Comment by DI555** [comment]
Dear developers, please add this features inToDo list!
• Separate tabs for favorites, groups, private messages, and announcements
• Increase pin limit to unlimited

**Comment by thermatk** [comment]
#257
