### ISSUE TITLE
Build error Failed to find target with hash string 'android-28'

### ISSUE THREAD

**Issue by nickaein** [Telegram-FOSS-Team/Telegram-FOSS#304]
I followed the [Build instructions](https://github.com/nickaein/Telegram-FOSS#building) in Readme and I am getting the this error when I run `./gradlew assembleAfatRelease` (full error log at below):

```
* What went wrong:
A problem occurred configuring project ':TMessagesProj'.
> Failed to find target with hash string 'android-28' in: /home/isaac/Android/android-ndk-r16b
```

Two things that I'm suspicious of are:

1. What should I do at step 4 that says `For the whole project set NDK to r16b`. I created a `local.properties` file at root and set its content to `sdk.dir=/home/isaac/Android/android-ndk-r16b/`. Is that correct?

2. I haven't done any Android (nor Java) development on this Linux VM. Should I download anything else besides NDK (I've already installed java) for building this project?

There is the build log:

```
$isaac> ./gradlew assembleAfatRelease
Parallel execution with configuration on demand is an incubating feature.

> Configure project :TMessagesProj 
WARNING: The option 'android.enableD8' is deprecated and should not be used anymore.
Use 'android.enableD8=true' to remove this warning.
It will be removed in AGP version 3.3.
Checking the license for package Android SDK Build-Tools 28.0.3 in /home/isaac/Android/android-ndk-r16b/licenses
License for package Android SDK Build-Tools 28.0.3 accepted.
Preparing "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)".
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" ready.
Installing Android SDK Build-Tools 28.0.3 in /home/isaac/Android/android-ndk-r16b/build-tools/28.0.3
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" complete.
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" finished.
Checking the license for package Android SDK Platform 28 in /home/isaac/Android/android-ndk-r16b/licenses
License for package Android SDK Platform 28 accepted.
Preparing "Install Android SDK Platform 28 (revision: 6)".
"Install Android SDK Platform 28 (revision: 6)" ready.
Installing Android SDK Platform 28 in /home/isaac/Android/android-ndk-r16b/platforms/android-28
"Install Android SDK Platform 28 (revision: 6)" complete.
"Install Android SDK Platform 28 (revision: 6)" finished.


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':TMessagesProj'.
> Failed to find target with hash string 'android-28' in: /home/isaac/Android/android-ndk-r16b

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 27s
$isaac>
```

**Comment by r4sas** [comment]
> Failed to find target with hash string 'android-28' in: /home/isaac/Android/android-ndk-r16b

**Comment by nickaein** [comment]
You're correct. I fixed it by this `local.properties`:
```
sdk.dir=/home/isaac/Android/sdk
ndk.dir=/home/isaac/Android/android-ndk-r16b
```

where `sdk` directory only contained `licenses`. Apparently gradle automatically populate `sdk` and other requirements.

Next I was getting `Java Null Pointer exceptions` errors. By downgrading from JDK 11 to JDK 8 the issue was resolved. Nevertheless, what JDK version is recommended the build?

Currently I am getting out of memory errors during `> :TMessagesProj:mergeAfatReleaseJniLibFolders`. Isn't 4GB RAM enough for the build? I tried to tweak following settings in `gradle.properties` but I didn't help yet.

`org.gradle.jvmargs=-Xmx4096M -XX:MaxPermSize=4096m`

**Comment by r4sas** [comment]
I had same out of memory errors, but I tried start build few times and it built at the end.

I'm tested build with android-ndk-r17c.

**Comment by nickaein** [comment]
Gradle daemon opens too many threads (~8000 threads!) during the late stages of build. I tried to circumvent crashes by increasing ulimit parameters and the build succeeded by chance. But there is clearly a bug in build system, at least on JDK8.

**Comment by nickaein** [comment]
The generated apk cannot be installed on phone with Android Pie. I've disabled `Play Protect` to make sure it doesn't cause any interference. 

The apk provided in [releases page](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/releases) can be installed though.

Is there any steps (e.g. signing) that I am missing to get install-able apk?

**Comment by r4sas** [comment]
You must sign that APK or build debug version to use without signing.

**Comment by nickaein** [comment]
To build the debug version I run `gradle assemble` as [suggested here](https://stackoverflow.com/a/17471298/161640) but the build error is back:

```
> unable to create new native thread
```

As I said in https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/304#issuecomment-465263499, at the late stages of build (during `> :TMessagesProj:mergeArm64DebugJniLibFolders`), gradle shoots up too many threads  (~8K threads) which cause the build to fail. I tried to limit number of threads by adding following line to `gradle.settings` but it didn't help:

```
org.gradle.parallel.threads=4
```

There might be some buggy script that runs too many threads inside a loop and causes the failure.

**Comment by thermatk** [comment]
I experience the same issues sometimes, yet it manages to build fine in the end on 16gb and even on 4gb if you adjust the gradle parameters 
I guess we'll have to live with its demands :rofl:

**Comment by nickaein** [comment]
The initial issue has been fixed, but the issue described in https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/304#issuecomment-465360251 was still present. I believe it is either a bug in build script or in my configuration. I will give it another try and post it on more detail.
