### ISSUE TITLE
GIF playing issue on latest 5.4

### ISSUE THREAD

**Issue by archi-doctor** [Telegram-FOSS-Team/Telegram-FOSS#308]
Gifs seems like a video which has corrupt codec. Gifs are showing as colored horizontal lines. This issue started ith 5.4 1517 version.
My telegram t.me/archi_dagac

**Comment by Bubu** [comment]
Can you provide more detailed reproduction steps? Or join our Telegram Group (https://t.me/tfossofftop) and demonstrate the problem there?

**Comment by Bubu** [comment]
Ah, right, we talked about this in the group. Turned out to be an upstream bug. Not sure if fixed in latest version (for which we don't yet have any source.)

**Comment by CryptOwl** [comment]
It's still broken in 5.6.1.
