### ISSUE TITLE
 Link Preview Should Be Blocked/Display Warning for Untrusted Redirects

### ISSUE THREAD

**Issue by FreeCitizin** [Telegram-FOSS-Team/Telegram-FOSS#312]
I've noticed an attack on group of activists on Telegram. The attack consisted of the following:
1. Short url from twitter (t.co) 
2. IP logger
3. A destination that looks legit (Google doc)
I've created similar link with free public IP logger and a document I've found on the internet
YOUR IP WILL GET RECORDED, DO NOT OPEN IF YOU DON'T WANT
https://t.co/PI1uy0mFks

People active on twitter may think that this is a link to a tweet with the document but it's a trap to expose IP.

Solution IMHO is not to show preview if link is going through redirects. Or at least to show a warning. 

![RedirectDetective](https://user-images.githubusercontent.com/48927232/54948851-90a36880-4f35-11e9-958d-cbc442e81099.png)

![image](https://user-images.githubusercontent.com/48927232/55217549-b19ae080-51f7-11e9-86fd-c13a25fc6fff.png)

**Comment by Bubu** [comment]
The preview is done fully server side. So I don't think there's anything that can be done client side here except completely disable URL previews. Which also doesn't help in deciding if a link is save to click or not.

**Comment by Bubu** [comment]
I can't think of anything we can do here, sorry.
