### ISSUE TITLE
Please add ability to disable proximity sensor when playing voice messages

### ISSUE THREAD

**Issue by hey-you-its-me** [Telegram-FOSS-Team/Telegram-FOSS#313]
When playing voice messages, Telegram checks if the proximity sensor is triggered, and if it is, it shuts off the display and doesn't allow touch input.
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/c83823dd3f020e66ca0eb598c0e3fd1944f1ce88/TMessagesProj/src/main/java/org/telegram/messenger/MediaController.java#L1311

Optical proximity sensors have been replaced in some phones with ultrasonic software-only proximity sensors. If the microphone that is listening for the ultrasonic sound is unable to detect the ultrasonic sound, the phone will think that the proximity sensor is triggered and Telegram will shut off the display. This can happen if a hand, corrugated cardboard, cloth, or any other sound-blocking object is covering the speaker or microphone used for ultrasound.

If Telegram had an option in the settings menu to disable the proximity sensor completely while listening to voice messages, this behavior could be avoided, while still keeping the proximity sensor available for things like telephone calls.

**Comment by Bubu** [comment]
This should be handled upstream really, we can't implement general features here.
