### ISSUE TITLE
Remote control

### ISSUE THREAD

**Issue by DI555** [Telegram-FOSS-Team/Telegram-FOSS#314]
Please add remote control option... it's very awaited!!!
I saw some tg bots that do that, but they're closed sources or/and use suspicious services(((
One example of remote control feature is - ip cam features : online video&audio streaming, recording with mods(normal, cycled, etc...) , move_sensor/noise_sensor alarms and actions , plus many more!
Many thanks in advance!

**Comment by Bubu** [comment]
You know, there's an app for that: https://guardianproject.github.io/haven/

This is very much out of scope for this project.

**Comment by DI555** [comment]
Thank you, but is it possible to force/use to work Haven thrue the Telegam ?
Now Haven uses Tor as I've known. But force it uses Telegramwould be the great idea!
