### ISSUE TITLE
Configuration error with boringssl

### ISSUE THREAD

**Issue by charan15923** [Telegram-FOSS-Team/Telegram-FOSS#316]
./build_boringssl.sh
Configuring...
CMake Error at CMakeLists.txt:10 (project):
  Running

   '/Users/charan/Downloads' '--version'

  failed with:

   Permission denied

-- Configuring incomplete, errors occurred!
See also "/Users/charan/Documents/test/Telegram-FOSS/TMessagesProj/jni/boringssl/build/armeabi-v7a/CMakeFiles/CMakeOutput.log".

And this is the LOG MESSAGE
The target system is: Android - 1 - armv7-a
The host system is: Darwin - 15.6.0 - x86_64

**Comment by Bubu** [comment]
No idea. Would need a full terminal output form a build attempt.

**Comment by ngodn** [comment]
write the full path to the ninja binary file:
in your case, it might be

/Users/charan/Downloads/ninja
export NINJA_PATH="/Users/charan/Downloads/ninja"

**Comment by mohammadmirdar** [comment]
I had  error like this, but i can't solve with spending 12 hours for this error.

**Comment by thermatk** [comment]
@ngodn obviously got it right
