### ISSUE TITLE
Addition of 'smart reply option' in the telegram

### ISSUE THREAD

**Issue by peerzadaaabid** [Telegram-FOSS-Team/Telegram-FOSS#319]
Of course, after using the app for the quite large time I found there is a need to include smart reply option in the telegram.
By smart reply, I mean the user should be able to reply to the message without opening the telegram app.
I wanna prepare a full blog , if you wanna include this fearure.

Thanks

**Comment by Kyle2142** [comment]
You can already reply via notifications

**Comment by Bubu** [comment]
> You can already reply via notifications

Indeed. Pr not sure what else was meant.
