### ISSUE TITLE
Source code released! Please update to 5.6.1

### ISSUE THREAD

**Issue by batzuli** [Telegram-FOSS-Team/Telegram-FOSS#321]
https://github.com/DrKLO/Telegram

**Comment by Pikari0** [comment]
I wonder if the new "large emoji" feature will work with our set :thinking:

**Comment by sbth** [comment]
Yes please! I'd love to have this updated!

**Comment by Hiboycubano** [comment]
No updates since 5.4 betha! Please pdate to 5.6.1 soon

**Comment by Pikari0** [comment]
Thank you @thermatk :heart:
