### ISSUE TITLE
google remove most of all unofficial telegram

### ISSUE THREAD

**Issue by rexi1r** [Telegram-FOSS-Team/Telegram-FOSS#328]
hi, recently google remove unofficial telegram without any specific reason.do you know why?

**Comment by andrew-ld** [comment]
![hqdefault](https://user-images.githubusercontent.com/43882924/58908362-a5a82f00-8710-11e9-81c1-1b4b729b51bb.jpg)

**Comment by r4sas** [comment]
Read this:
https://core.telegram.org/api/terms

>4.2. If you do not update the app to fix the highlighted issues within 10 days, we will have to discontinue your access to Telegram API and contact the app stores about the removal of your apps that are using the Telegram API in violation of these terms.

That's why.
