### ISSUE TITLE
Update to v.5.7 source code is available!

### ISSUE THREAD

**Issue by batzuli** [Telegram-FOSS-Team/Telegram-FOSS#330]
https://github.com/DrKLO/Telegram

**Comment by DI555** [comment]
Any good news about f-droid builds, please?

**Comment by r4sas** [comment]
5.7.1 was merged 4 days ago, please wait.
https://gitlab.com/fdroid/fdroiddata/merge_requests/4939

**Comment by thermatk** [comment]
@r4sas and built 3 days ago :)
https://f-droid.org/wiki/page/org.telegram.messenger/lastbuild_16080

**Comment by r4sas** [comment]
> @r4sas and built 3 days ago :)
> https://f-droid.org/wiki/page/org.telegram.messenger/lastbuild_16080

Yes, I've seen that tracker... and understand that package waiting for validation before publishing. But someone think that package was built and all stucked.

**Comment by DI555** [comment]
Wow, many thanks for quick builings in f-droid repo!

**Comment by DI555** [comment]
Pardon me ;) , I see new 5.9.0 is already there ;)) !!!
