### ISSUE TITLE
help/nudge microG to add third party push notification support

### ISSUE THREAD

**Issue by tleydxdy** [Telegram-FOSS-Team/Telegram-FOSS#331]
https://github.com/microg/android_packages_apps_GmsCore/issues/714

**Comment by Bubu** [comment]
I'm not surw what you are expecting here. How would you ever convince the telegram server to send push notifications to your custum push server?

**Comment by tleydxdy** [comment]
you don't, and that's the point. the server proxy notifications from FCM when apps doesnt support it, but it enables free software devs to stop using it(or having two versions)

**Comment by tleydxdy** [comment]
microg could also just listen to other servers parallel to Google's server so user would'nt need to give their tokens.

**Comment by Bubu** [comment]
Both of these are certainly options. It doesn't really have anything todo with telegram though.

When there's no control over the server there is nothing you can do fundamentally better than 1) use fcm (through a proxy or not, doesn't matter) and live with the dependency on google and the privacy implications. 2) don't use fcm but the live with the lack of it.

1) would mean recompiling with the microg client implementation of fcm (which AFAIK currently doesn't work.)

But what I want to get across is that telegram will never benefit from 3rd party Push services as in the issue title. Unless you make them change their server implementation. Good luck with that.
