### ISSUE TITLE
F-Droid stable builds?

### ISSUE THREAD

**Issue by fcore117** [Telegram-FOSS-Team/Telegram-FOSS#332]
I do not like Google play edition, i have long time user of Telegram-FOSS and i update manually when i need. This far everything is worked really fine for me without push stuff, i still get needed notification when i wake screen and that is all i need. I do not use Google play at all, i even disabled it in system apps.

**Comment by Bubu** [comment]
I... What is this issue about?

**Comment by fcore117** [comment]
Issue was that perhaps provide release builds here as alternate if f-droid fails.

**Comment by thermatk** [comment]
Makes no sense, because then you would have to wipe the fdroid one and
install from scratch.

ср, 12 июн. 2019 г., 12:27 fcore117 <notifications@github.com>:

**Comment by notpushkin** [comment]
@thermatk You'll have to do it only once though, and everything (except for the Secret Chats and the cache) will be intact — I personally don't see any problem here :—)
