### ISSUE TITLE
First word to emoji lookup security concern

### ISSUE THREAD

**Issue by c33s** [Telegram-FOSS-Team/Telegram-FOSS#337]
since the upgrade to telegram 5.6 i noticed that typing the first word in a chat also shows a suggestion for a emoji.

like:

- kiss -> lips
- grins (german "slang" for "to grin") -> laugh emoji
- lol

how does this lookup work? i searched in the code for "grins" (because the search for other words had to many hits in the code) and wasn't able to find it. does this mean the first word (or even more) i am entering in a secret chat is sent to the telegram server for emoji lookup?

maybe someone can show me the related part in the code.

related to #326

**Comment by Bubu** [comment]
> does this mean the first word (or even more) i am entering in a secret chat is sent to the telegram server for emoji lookup?

See for yourself: enter airplane more, type word, ..., suggestions appear.

**Comment by c33s** [comment]
> See for yourself: enter airplane mode, type word, ..., suggestions appear.

but i don't know if its only cached data. thats the reason i asked for the code part. airplane mode alone tests doesn't guarantee the safty

**Comment by AbsurdlySuspicious** [comment]
I'd found `fetchNewEmojiKeywords` method which is evidently fetches all keywords at once to the local db ans its only input data is locale code so there is no much reason to worry about privacy

https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/1e7a1e4d23b894a8951bb2db41390745783df329/TMessagesProj/src/main/java/org/telegram/messenger/DataQuery.java#L4109
