### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by samantohermes** [Telegram-FOSS-Team/Telegram-FOSS#343]
Is there any plans to implement this different method of push notifications?
https://f-droid.org/en/2018/09/03/replacing-gcm-in-tutanota.html

**Comment by thermatk** [comment]
@samantohermes Who wants an IM with 15 minutes of delay

**Comment by samantohermes** [comment]
> and we also try to keep it alive afterwards.

**Comment by bibz** [comment]
@thermatk everybody that would like to stay away from the Play Services.

Even though I support and like the idea of skipping FCM altogether, I doubt this can be leveraged here. It requires resources commitment from the team/company hosting the (centralised) service.

As far as I understand this repository is only about packaging the client code that Telegram eventually makes available through @DrKLO/Telegram. The server has not been open-sourced and so this issue should be raised with Telegram directly (directly there maybe?).

**Comment by thermatk** [comment]
What does this issue have to do with anything? I can implement a service that runs every 15 minutes, which would not be a proper messenger in my opinion. I have no idea how to keep it alive, and if it exists it's a hack that is not working everywhere and will stop working

**Comment by samantohermes** [comment]
Conversations (an IM app) doesn't use a persistent notification in Android 8+.

**Comment by thermatk** [comment]
😂 https://github.com/siacs/Conversations/blob/master/README.md#im-getting-this-annoying-permanent-notification
Yes, they do it the other way around and ask you to completely exempt the app from battery optimizations in foss builds

**Comment by samantohermes** [comment]
@siacs
