### ISSUE TITLE
Change packagename

### ISSUE THREAD

**Issue by A2DNEW** [Telegram-FOSS-Team/Telegram-FOSS#344]
Hi
How i can change package name of telegram messenger?

**Comment by A2DNEW** [comment]
Why close this issue?!

**Comment by A2DNEW** [comment]
@thermatk ?

**Comment by ildar** [comment]
If you explain your intentions to do so then maybe Ruslan would answer.
Anyway I cannot talk for him, just an assumption.

**Comment by DrPhilosophus** [comment]
@ildar Because the fingerprint is different it's installed as another app instead as an update to 5.7.1.

**Comment by ildar** [comment]
then what? you want to change the pkg name and have two Telegrams on one
phone?
Isn't it right to backup (optional) then remove the old then install new?

**Comment by thermatk** [comment]
Changing package name is a very basic and general Android dev skill, no need to spam the issues section here
