### ISSUE TITLE
Split APK into Architecture-targeted APKs

### ISSUE THREAD

**Issue by moriel5** [Telegram-FOSS-Team/Telegram-FOSS#345]
I am well aware of the reasons behind merging the APKs into one, as I have been around since well before the official Telegram's public repo had disabled creating issues, however I am asking to reconsider this.

20+ MB is ridiculus for an FOSS messaging app (or any messaging app, for that matter), especially since there are no trackers or adware included.

More importantly, this does have a severe impact on old low-end devices (think 4GB internal storage with a custom ROM, when in practice there may be only ~2 GB available to the user). After all, it is not only the APK size, but also the Dalvik/ART cache, and extracted libraries, and there are other applications which will be competing for space (I have seen this myself, on my mother's LG G3 Beat, and she runs a noGAPPS build, like me (we don't have need for the Play Services)).

My recommendation, is to create two variants, one for arm and one for arm64 (x86/x86-64 utilizes Intel's unofficial extension to the spec), and if other architectures are required, see what can be reused.

As controversial as is it, even Google is going that route (farther actually) with Split-Installer-APKs, so this may be a good way to lay the foundations for something more efficient (without sacrificing practicality).

**Comment by Bubu** [comment]
This will save about 7-8 MB of space while introducing a bunch more maintenance and testing work. If someone wants to commit to that, please start submitting MR's here and in fdroiddata. 

An x86 variant would be needed as well.

**Comment by thermatk** [comment]
@Bubu Only commit to fdroiddata
We're ready for split on the code side, just pick the non-"fat" flavors

**Comment by Bubu** [comment]
Might not be that hard, I'll see if I can get it to work in an hour.

**Comment by Bubu** [comment]
Shall we build the non _SDK23 variants as well?

**Comment by Bubu** [comment]
Added here: https://gitlab.com/fdroid/fdroiddata/commit/687158a0e50f2d0649ab86d00dfda1e5d780603b

These builds use ndkr20 which I only just added. Which means it might take quite a while until this is available on the buildserver. As this is not a feature update I think it's fine (or possibly even preferred) if that gets pushed if this is delayed by about a month.

**Comment by r4sas** [comment]
> Shall we build the non _SDK23 variants as well?

Of course! Please keep API16 as long as possible.

**Comment by moriel5** [comment]
Wow, that was more than I had expected.
I can test on arm, and once ready, x86 and x86-64 (if required), however I have never succeded in compiling an Android app (mostly due to my limited knowledge in Android code compiling).

As long as it is possible, and not too much work, you can take your time, no hurries.

**Comment by DI555** [comment]
Please keep the app names of f-droid and github builds be different, as it now is!

**Comment by Bubu** [comment]
This is done now.

**Comment by Bubu** [comment]
We now have minsdk 23 on the new builds :roll_eyes:

**Comment by daufinsyd** [comment]
Hi thanks for the 10MB (it's always pleasant to have apps as light as possible :-D )
May I suggest to bump the fdroid version to 5.9.1 (At first sight, I thought you were highjacked or something, 3 times the 5.9.0 update and 10MB less ;-) ) ?

**Comment by DI555** [comment]
I would suggest , to avoid missunderstandings , to name versions inside one telegram build number by a subdigit!
So this would be 5.9.0.1 !

**Comment by DI555** [comment]
What the heck with minsdk i see on f-droid? why minsdk 23 ?
What about keeping the old minsdk 16 ?
At least please don't go upper than minsdk 21 !!!!!!!

**Comment by DI555** [comment]
I see a little confusion on f-droid, there's no description about 3 different builds(((.
May be should write a little in a head description about what which build is ?

**Comment by moriel5** [comment]
F-Droid should be able to show what architecture each APK is for, at least from my experience.

**Comment by DI555** [comment]
Could it be possible in F-droid versions to sign all arch.-targeted apk'es by the same sign as the universal apk?
Without it not possible to upgrade and skip from uni. to arch.-targ. installation (((

**Comment by thermatk** [comment]
@DI555 It's the same signature, but version number is only allowed to go up
You can go up to the next fat release
Yet the numbers are actually sorted in a way that you don't have to switch 👌

**Comment by DI555** [comment]
@thermatk ,
i got an error when was updating from global apk to arc-specific one...
arm v7 android 5.1 ... from 5.10.0  to 5.11.0
what i did: downloaded all 3 arc-spec apks, found my arm v7 one and got error exactly the same how it used to be with different signature (((
so i'm updated to tge global one instead...

**Comment by moriel5** [comment]
That is odd, I had no issues upgrading to the 5.10.0 armv7 build when it came out.

**Comment by DI555** [comment]
Hm.., may be it os version depends..
i was trying to update on android 5.1

**Comment by moriel5** [comment]
My APK (I keep backups) shows minimum Android as 4.1.
