### ISSUE TITLE
UI - Folders for Chats and Channels

### ISSUE THREAD

**Issue by nwildner** [Telegram-FOSS-Team/Telegram-FOSS#347]
Hi.

It would be awesome if Telegram-FOSS could support something like folders for chats, groups and channels.

I'm not a designer so, my mockup will be text only. But the idea is to create folders to better organize them, and show the sum of your unread messages on that folder. Examples:

Main UI chat screen with unread messages:

- GNU/Linux Group(30)
- Arch Linux Group(0)
- Ubuntu Group(12)
- Linux Gaming channel(15)
- Random group whatever(3)
- Networking group(4)
- Routing group(10)
- Zabbix group(30)
- Stock Exchange Bot
-----your screen ends here-----
- Stickers Bot
- Admin Bot 01
- Admin Bot 02
- Random Bot 01

After creating some folders and moving chats to them, Main UI would look like:

- Linux (57)
- Random Stuff(3)
- IT Stuff(44)
- Bots

Touching the group should be enough to expand it: 

- Linux (57)
  - GNU/Linux Group(30)
  - Arch Linux Group(0)
  - Ubuntu Group(12)
  - Linux Gaming channel(15)
  - Random Stuff(3)
- IT Stuff(44)
- Bots

Also, folders should be always shown first than groups that does not belong to a folder.

**Comment by thermatk** [comment]
Hi!
Another cool idea, but it's too much for this fork, I guess you can fork the fork. 
- This would go against our goal of maintaining a clean upstream-but-floss
- I won't be able to carry another patch of this size forward
