### ISSUE TITLE
Add option to disable animated stickets

### ISSUE THREAD

**Issue by dueringa** [Telegram-FOSS-Team/Telegram-FOSS#349]
A feature request: Telegram 5.9.0 added animated stickers, which some people might find annoying.

Would it be possible to add an option (in the settings menu) to disable playing animated stickers (e.g. showing a text "Animated stickers are disabled" instead)?

**Comment by Bubu** [comment]
I'd suggest training your contacts. If that doesn't work consider running version 5.7, which does effectively what you suggested. (But misses some other features).

I doubt this would be integrated, even if someone would submit a patch. Every patch adds maintenance work to carry it forward and this frankly doesn't sound like it's worth the effort.

**Comment by dueringa** [comment]
Looks like a similar feature was already implemented in the original Telegram client version 5.10. So I guess I'll close this. Thanks anyway.
