### ISSUE TITLE
Modify this app to use the matrix protocol

### ISSUE THREAD

**Issue by RomanJos** [Telegram-FOSS-Team/Telegram-FOSS#352]
Hi i just want to know if its possible to make this app using the matrix protocol instead of the original Telegram ? that would be cool because Telegram is way ahead of riot and if we can merge those two world we could create something amazing

**Comment by shouko-git** [comment]
Well then it won't be compatible anymore with Telegram cloud.

**Comment by RomanJos** [comment]
yeah but its does not matter because it would not be used for Telegram

**Comment by Bubu** [comment]
This is not a useful proposal for this project.

Others tried to use the Telegram UI for other messengers but ultimately abandoned this (delta-chat). The code is really not meant for this but if someone else likes to try, sure go ahead.

(But this is not the place.)
