### ISSUE TITLE
Add option to use system emoji

### ISSUE THREAD

**Issue by igalic** [Telegram-FOSS-Team/Telegram-FOSS#355]
while i understand the need for a branded per app experience, i much more appreciate a cohesive experience across the OS.

there's hardly any modern android without a complete emoji set, so it would be nice if there was an option to simply use that.

**Comment by Bubu** [comment]
> there's hardly any modern android without a complete emoji set

Err, no. Even Android 8.1 is missing a bunch of the newer emojis. And android 9's market share is still at something like 2% I believe.

**Comment by thermatk** [comment]
And now everyone except iOS is missing the newest... no way

**Comment by danbrun** [comment]
Can this be reopened? I don't understand why we can't have the option to use system emoji. I want all the apps on my phone to use a consistent emoji set and I guarantee I won't miss the few new emoji I don't have because I don't use them anyway.

**Comment by chaptergy** [comment]
I would also love this option, since I find it very irritating to have my emojis on the keyboard when selecting the emoji, and it typing out as a totally different emoji style in the message. Furthermore, it seems the option is already in the code, but commented out?
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/6af57a378865ef65157afba35ca833abcd31676b/TMessagesProj/src/main/java/org/telegram/messenger/Emoji.java#L239

**Comment by dreamwhite** [comment]
@Telegram-FOSS-Team sorry for disturbing you. May you gently create a dedicated user settings to use system fonts? In my opinion it's awful having two different emojis sets on the same system  😅

**Comment by HannesGitH** [comment]
> > I would also love this option, since I find it very irritating to have my emojis on the keyboard when selecting the emoji, and it typing out as a totally different emoji style in the message. Furthermore, it seems the option is already in the code, but commented out?
> > https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/6af57a378865ef65157afba35ca833abcd31676b/TMessagesProj/src/main/java/org/telegram/messenger/Emoji.java#L239
> > 
> > https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/50d9b1746ae2d543a393aebcc4fa02492be7f500/TMessagesProj/src/main/java/org/telegram/messenger/SharedConfig.java#L254
> 
> So apparently I ~tried building the application with the edits suggested there, but sadly I get a compilation error regarding "textPaint". I still don't get how is that even possible...~ succeeded building the app with useSystemEmoji enabled, but links are broken. Still need to investigate

any progress? thinking about building my own as well

**Comment by HannesGitH** [comment]
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/pull/622#issuecomment-1227160057
