### ISSUE TITLE
Move screenshots and metadata for app stores upstream

### ISSUE THREAD

**Issue by PanderMusubi** [Telegram-FOSS-Team/Telegram-FOSS#356]
For automated adding of screenshots and metadata to app stores, several mechanisms exist such as metadata and fastlane. This saves the maintainer a lot of manual work uploading screenshots to app stores when new screenshots are available. This is a widely used mechanism help release new versions of apps.

For the F-Droid app store, screenshots and metadata have been created to facilitate this. These can be found at https://gitlab.com/fdroid/fdroiddata/tree/master/metadata/org.telegram.messenger/en-US

The request is to move this data upstream from the F-Droid repo to this repo, or perhaps even to https://github.com/DrKLO/Telegram . I can make a pull request for this or the upstream repo. Let me know what is welcomed. This will move screenshots to a more generic location allowing maintenance in one place for the benefit of all app stores.

**Comment by PanderMusubi** [comment]
This issue is part of an effort to remove custom screenshots from the F-Droid data repo, see also https://gitlab.com/fdroid/fdroiddata/issues/1413#note_193403754

**Comment by IzzySoft** [comment]
For details, please also see: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository

Note that this gives you a bunch of advantages as a welcome side effect:

* you can easily update/replace screenshots without the need of opening MRs at fdroiddata
* you can easily maintain app descriptions (including multi-locale) directly in your app's repo
* you can use the same for F-Droid and Google Play (so no redundant double-work)
* you can also include per-release changelogs (`changelogs/<versionCode>.txt`) which are displayed inline with the app description on both, F-Droid and Google Play – which in the F-Droid client make your app appear on the featured tab (still called "new") if you have screenshots along those changelogs

Thus resulting in a clear win-win-win (less work for you, less work for us, better information for the user). So this move is strongly encouraged :wink:

**Comment by PanderMusubi** [comment]
Any updates for this issue? Anyway I can help with this?

**Comment by thermatk** [comment]
I think we managed alright, thanks for all details, closing
