### ISSUE TITLE
telegram 5.10 source code available

### ISSUE THREAD

**Issue by ArmeF97** [Telegram-FOSS-Team/Telegram-FOSS#359]
https://twitter.com/TelegramBeta/status/1164332921953685504?s=19

**Comment by DI555** [comment]
What's new:

5.10: Silent Messages, Group Admin Titles and Slow Mode for Groups

• Hold the Send button to send any message without sound – in case the recipient is sleeping. 
• Enable Slow Mode in Group Permissions to control how frequently members can post.
• Set custom titles for admins.
• Tap the paperclip icon to open the redesigned attachment menu.
• Toggle looped playback for animated stickers.
• See preview thumbnails when scrubbing through a video. 
• Send animated emoji.
