### ISSUE TITLE
Can I switch from F-Droid updates to Play Market, without uninstalling?

### ISSUE THREAD

**Issue by azat11** [Telegram-FOSS-Team/Telegram-FOSS#364]
Updates seem to be coming later to F-Droid. Wanna switch, but don't wanna uninstall..

**Comment by anupritaisno1** [comment]
@azat11 if you find a way to replace the Telegram app on a real device without root and without uninstalling and reinstalling it, that would be a serious security bug that would need to fixed. There's intentionally no way to do this

**Comment by azat11** [comment]
How can I do this on a rooted device?

**Comment by anupritaisno1** [comment]
@azat11 Backup application data, uninstall, reinstall, restore application data

**Comment by azat11** [comment]
@anupritaisno1 Could you be more specific? What do I backup?

**Comment by adityasubathu** [comment]
@anupritaisno1 backup your telegram app using any backup app like Titanium Backup or Swift Backup from play store. Uninstall your version of tg and install from play store and when the play store version is installed, restore data with the same backup app

**Comment by niansa** [comment]
Replace the base APK inside Telegrams app folder, then reboot
