### ISSUE TITLE
Blurry call encryption verification emojis

### ISSUE THREAD

**Issue by Lesik** [Telegram-FOSS-Team/Telegram-FOSS#367]
I don't think this bug has been reported before: The last update brought us enlarged emojis during Telegram calls, which are blurry. This is probably a bug on our side and not upstream, since we change them out.

![Screenshot_20190913-130350](https://user-images.githubusercontent.com/2021487/64859733-59339000-d62b-11e9-968c-3a68ddca8fa7.png)

**Comment by thermatk** [comment]
They got less blurry now, but maybe we should make them blurry again because they take too much space in the apk :rofl: tapping verification emojis to enlarge them is a very special case

**Comment by Lesik** [comment]
Oh, I didn't realize it's only when you tap them. Must've tapped with my ear on accident. How much is the difference in size in the apk, and could you point to the commit that's fixed this please? Thanks!
