### ISSUE TITLE
Mentions Override The Notifications Settings From Show It Silently To Make Sound

### ISSUE THREAD

**Issue by TakuyaSama** [Telegram-FOSS-Team/Telegram-FOSS#369]
### Issue Description
I have configured the notification for all the chats at Telegram FOSS to be showed but silently (at the Android side), on Telegram FOSS i have muted a certain few groups, but when i got some mention (no matter what group is), that mention overrides and sets up the notification configuration for that chat to **make sound and pop up**.

Other workaround valid to me would be the possibility to establish the notification sound as none, but the app forces me to choose one valid sound file.

### What Actually Happens
Telegram FOSS overrides the notification configurations for some groups i have muted at the app and set up to show silently the notifications at the Android side, causing that sometimes, sounds with the given groups mentions, the notification sound disturbs me a lot.

### What Should Happen
Telegram FOSS should respect the notification configuration i've got on Android, no matter what mentions i got from anywhere.

### Miscellaneous Information
Device: **bacon** (**OnePlus One**)

Android Version: **9** (**LineageOS 16**).

Telegram FOSS Version: **5.11** (**build 17101**).

**Comment by Younes-L** [comment]
https://t.me/tgbetachat/66523

DrKlo : « you should not use android notification channels settings and manage all notifications setting within the app. App will overwrite everything you changed in system settings. »

**Comment by TakuyaSama** [comment]
> https://t.me/tgbetachat/66523
> 
> DrKlo : « you should not use android notification channels settings and manage all notifications setting within the app. App will overwrite everything you changed in system settings. »

I see, i really tried to just configure everything about notifications at the Telegram FOSS app, but i just couldn't. I just configured it a little more, i'll update after a few use if it was successful or not.

Thank you very much @Younes-L :).

Bests ^^.

**Comment by TakuyaSama** [comment]
@Younes-L Confirmed about 4-5 days ago. Configured at the app, now there's no sound at all, as i wanted, but i can't see the pop-up either, but well, better than nothing.

Closing the issue, cause there's no issue at all.
