### ISSUE TITLE
App connects to varios google servers

### ISSUE THREAD

**Issue by mahdi1234** [Telegram-FOSS-Team/Telegram-FOSS#373]
Hi,

noticed both in netguard as well as sniffing traffic with mitmproxy that app connects to servers like www.google.ru www.google.com or dns.google.com.

Not sure what's the reason, but it doesn't sound right to me for privacy app to do such queries (and I blocked them both in netguard as well as in pihole and app behaves totally normally).

These domains seem to come from here:

> grep -ri 'google\.' ./TMessagesProj/src/main/java/org/telegram/tgnet/ConnectionsManager.java 
>                 URL downloadUrl = new URL("https://www.google.com/resolve?name=" + currentHostName + "&type=A");
>                 httpConnection.addRequestProperty("Host", "dns.google.com");
>                         googleDomain = "www.google.com";
>                         googleDomain = "www.google.ru";
>                         googleDomain = "google.com";
>                     httpConnection.addRequestProperty("Host", "dns.google.com");
> 
> 
> 

Should this be some kind of ping, how about decide user which servers to use?

**Comment by thermatk** [comment]
Hi
This is expected behavior and used only to circumvent blocks. Since you found the code anyway and you see that it doesn't communicate your personal data, block it and be happy until your country blocks Telegram :)

**Comment by mahdi1234** [comment]
@thermatk Would you mind explaining what it does exactly then? First DNS request returns 301 anyway and then there's redirect elsewhere. Wouldn't it be better this is user-configurable instead of hardcoding google servers?

**Comment by DI555** [comment]
i suppose, it's built in dns resolver, is it?
What about an idea to make it like an option, and possibility to set a custon dns resolver?

**Comment by moriel5** [comment]
That would be awesome, I personally would rather that my DNS queries would pass through CloudFlare rather than Google, and it would be nice to run my own OpenDNS instance and have my queries go through it.
