### ISSUE TITLE
updating f-droid's builds problem

### ISSUE THREAD

**Issue by DI555** [Telegram-FOSS-Team/Telegram-FOSS#375]
i tried to update from prev. global build by new arcitecture-special one on my rootless device, and got error ;(.
are the new arc-specific builds signed by a different signature?
please fix it !
.... one signature for all build is highly needed just to make possible to migrate from one tipe of buld to another without any problems!

**Comment by Bubu** [comment]
> are the new arc-specific builds signed by a different signature?

No, of course not.

**Comment by DI555** [comment]
it's ok now! updating was siccessful!
but it seems only 0.6 mbyte is benefit  of moving to cpu specific build!
and it seems will be plus about 7-8 mbyte increase in the same types of builds...
is it all code base  became much larger? ;)

**Comment by DI555** [comment]
i have connecting problem, since was updated to 5.14.0 ...
all my google and other services are blocked by firewall, granted internet access only to telegram app. Was smth. change in telegram servers access structure ?

**Comment by DI555** [comment]
i'm in telegram blocked zone also...
could those server connection problems be in touch with new 'push' changes in 5.14.0 ?
in 5.11.0 all were working fine !
@thermatk , could you make those kinds of servers access works (in 5.11.0 and in 5.14.0) be optionable just to chose one way of them, please ?

**Comment by DI555** [comment]
it's a mystery ;)!
after almost 20 days of unpossibility to connect to servers my app has connected to them ;)!
