### ISSUE TITLE
feature option switch 'Contact joined Telegram message'

### ISSUE THREAD

**Issue by DI555** [Telegram-FOSS-Team/Telegram-FOSS#379]
Seems it's another little upstream bug...(or may be not)
this switch is turned off:
Settings —> Notifications and Sounds —> Contact joined Telegram
but the messages of it is still comming...

upd
since no option to stop comming messages of 'Contact joined Telegram' it's highly needed to be possible stop these annoing messages ;)!

**Comment by Younes-L** [comment]
This turns off the notifications, doesn't prevent the service messages from appearing as new unread chat in chat list. I do agree it would be better to have the ability to turn everything off, and it has been suggested multiple times in various telegram oriented groups. Still, feel free to suggest it once again here t.me/tgbetachat

**Comment by DI555** [comment]
hm..., i see..., than it's a FR issue ;)!
but imo, then this switch should be left and it's needed one more options switch like 'Contact joined Telegram message'

**Comment by DI555** [comment]
i mean would better to be two otions :
possible to switch on(off) notifications like now is, but 
possibility to switch off the exactly annoing messages about that ;) !

**Comment by thermatk** [comment]
Would be nice, but I don't really want to do feature requests. Difficult enough to keep up with the bare minimum of patches
