### ISSUE TITLE
my channel banned can you help my ? 

### ISSUE THREAD

**Issue by zetatechi** [Telegram-FOSS-Team/Telegram-FOSS#381]
I had a channel with 80K members for 4 years. Telegram has banned it without a single warning. It's not fair because we didn't do anything wrong during these 4 years.

which is not related to terrorism, not related to sex , not related to spam! not related to child porn , not related to Annoyance for the telegram

![image](https://user-images.githubusercontent.com/60185719/72903436-74817b00-3d42-11ea-9c2f-8c2017a18353.png)

**Comment by DrPhilosophus** [comment]
@zetatechi It's not at all relevant to the client Telegram FOSS
