### ISSUE TITLE
READ_CALL_LOG - Permission

### ISSUE THREAD

**Issue by Abdulaziz1525** [Telegram-FOSS-Team/Telegram-FOSS#385]
Telegram asks permission to access phone call logs (READ_CALL_LOG) for Account verification via phone call. (https://telegram.org/privacy#3-3-5-phone-number-and-contacts)

In the Google Play Market, What core functionalities in the Telegram app require Call Log permissions?

Here is the list of Core functionalities in the Play Market. Please help me to choose the correct choice for this app.

• Default SMS handler
• Default Phone handler
• Default Assistant handler
• Transactional backup and restore for users and archive for enterprise (time-limited/non-continuous)
• Enterprise archive, CRM, and device management
• Caller ID, spam detection, and blocking
• Connected device companion apps (for example, smartwatch or automotive)
• Cross-device synchronization or transfer of SMS or calls
• SMS-based financial transactions and related activity where access is restricted to financial SMS transactions (for example, 5-digit messages)
• SMS based money management
• Proxy calls
• Services - Carrier
• Services - OEM
• Device Automation
• Physical safety/emergency alert apps (e.g., senior safety)
• Call-based OTP account verification
• Using SMS_CB_RECEIVED for customer communications (e.g., Smart Zone Cast service)
• Write and Show Call History in Dialer
• In-vehicle hands-free use or projected display
• Anti-SMS Phishing

Thanks in advance!

**Comment by DrPhilosophus** [comment]
@Abdulaziz1525 Deny permission  for them

Manually enter OTP sent to another device or from the SMS sent

**Comment by wahidbha567-svg** [comment]
Can you show last 10 call history this number 7006823326
