### ISSUE TITLE
tabs realisation, new universal way!

### ISSUE THREAD

**Issue by DI555** [Telegram-FOSS-Team/Telegram-FOSS#386]
Just can't tell about it!
What if just create options 'add new tab' , 'move/copy to tab'(contacts, chats, channels etc.), and 'rename/delete tab' ?
So it will be just custom tabs, which you may create or delete...and give its names to whatever you want!
This feature shoudn't brake the main code imo and would be implemented like a patch to any code imo...
Sorry for the issue, but i thought implimentation like this is universal and great!

**Comment by thermatk** [comment]
@DI555 Don't see any patch attached 😉

**Comment by DrPhilosophus** [comment]
@DI555 Make PR and contribute to TG FOSS

**Comment by DI555** [comment]
yes, you all are right ;).  it's a good time for me to start in java.
 but nevertheless, on that issue the ideas of tab implimentation may be closed ;)

**Comment by DI555** [comment]
i suppose the new 'folders' in build 6.0.1 are very close to my 'tabs' !!! Some subfeatures are missed, like 'exclude listed in folders from main list', but it's a cosmetic ...
And i have a strong feeling that someone from telegram lab reads the current repo ;))). And if it is - it's very nice!
