### ISSUE TITLE
Gram Wallet on Fdroid?

### ISSUE THREAD

**Issue by Thisuu** [Telegram-FOSS-Team/Telegram-FOSS#391]
So, since the code for Gram Wallet is up at https://github.com/ton-blockchain/wallet-android/ & it seems like whether or not Telegram wins the ongoing court case, community will pick up the project and ton-blockchain will be up and running at some point, It would be nice to have the Gram wallet app in Fdrod.

Also, Even if Telegram will not be able to integrate Wallet with the Messenger at launch now (Until the blockchain is fully Decentralized, due to regulations), Telegram-FOSS will be able to do that at will, I guess.

**Comment by jugendhacker** [comment]
It depends on GSM as you can see here for example: https://github.com/ton-blockchain/wallet-android/blob/master/app/build.gradle#L19

**Comment by jugendhacker** [comment]
So there will be no option to get into Fdroid because GMS is proprietary

**Comment by Thisuu** [comment]
![photo_2020-02-25_15-50-00](https://user-images.githubusercontent.com/13273054/75238203-9a3cec80-57e6-11ea-8e7d-0ebccc4ed20e.jpg)

@jugendhacker  I think the Google Vision dependency is for QR Scan function, which can be removed.

**Comment by Thisuu** [comment]
https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java actually contains `TON_WALLET_STANDALONE` already, currently set to `false`. Interesting.
