### ISSUE TITLE
Update to 6.0.0

### ISSUE THREAD

**Issue by Niwla23** [Telegram-FOSS-Team/Telegram-FOSS#395]
Source Code is out!!!

**Comment by thermatk** [comment]
@Niwla23 Acknowledged 🥳

**Comment by TakuyaSama** [comment]
6.0.1 released already :).

I can't wait to have it, such wonderful new features.

**Comment by DI555** [comment]
Wow, they read our repo issues ;)))!!!
Custom folders and unlimited pins %)!

**Comment by TakuyaSama** [comment]
> Wow, they read our repo issues ;)))!!!???
> Custom folders and unlimited pins %)!

Looks like, **Plus Messenger** already had custom folders and tabs (each one separated), from what i know from a mate of mine.

Really wonderful news, now **official Telegram** has a really longtime desired feature, and that's something to celebrate.

I just can't wait until we've got Telegram-FOSS 6.0 released :).

**Comment by erayerdin** [comment]
:sob: 8 days and no update.

**Comment by TakuyaSama** [comment]
> 😭 8 days and no update.
> 
> **Edit:** Okay, it seems to be released. I commented because it was not on F-Droid.

That's it, waiting for the F-Droid package, they're a bit late, the main repo, (where Telegram is) has been updated twice since the release of 6.0.1 version, so I don't really get it.

I hope in two days at most, we'll have it there.

**Comment by piemonkey** [comment]
For those interested, 6.0.1 was [merged to the F-Droid data repo some days ago](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6577) but there was [a build issue](https://f-droid.org/wiki/page/org.telegram.messenger/lastbuild_19119). [The fix was merged](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6603) a couple of hours ago so it should be in the next metadata update.

**Comment by DI555** [comment]
@thermatk , are any plans to update to 6.1.0 ;) ?

**Comment by TakuyaSama** [comment]
6.1.0 update is currently WIP :).

Apr 27, 2020 9:00:26 PM DI555 <notifications@github.com>:

**Comment by DI555** [comment]
i suppose 6.1.1 is out already ;)!
