### ISSUE TITLE
Add video call feature using Jitsi

### ISSUE THREAD

**Issue by ahangarha** [Telegram-FOSS-Team/Telegram-FOSS#397]
Hi

I am using Jitsi as my default video call tool since I have left WhatsApp. Now I see some of my relatives have issue with userfriendliness of going into other app or open another website, make room and inform the other person to join that room.

I was wondering if we can add a feature to Telegram to use a customizable Jitsi server to make P2P call right withing Telegram.

I am not android developer but I guess we need to:
 - add video call button
 - make random room name
 - open popup from jitsi in telegram
 - make ring on the other person's device

Each person can config Jitst instance of their choice. So users wont be forced to use any specific instance.

**Comment by shoukolate** [comment]
TG-FOSS will not do it. They want to keep themselves as close as to the original TG.

**Comment by ahangarha** [comment]
So you suggest I make this feature request on https://github.com/DrKLO/Telegram?

**Comment by shoukolate** [comment]
Only thing you can do is to nag TG on twitter

**Comment by ahangarha** [comment]
tnx
