### ISSUE TITLE
Difference between F-Droid builds

### ISSUE THREAD

**Issue by rgabbo** [Telegram-FOSS-Team/Telegram-FOSS#398]
I noticed that there are two build in F-Droid with the same version and requirements. One is almost half the size of the other. Can you explain what are the differences? I wasn't able to find any statement about that.

![fdroid](https://user-images.githubusercontent.com/58396985/79343396-a1eb5880-7f2e-11ea-9bed-ebb62bc81c5f.png)

**Comment by r4sas** [comment]
First one have bundled libraries for architectures arm64-v8a, armeabi-v7a, x86, x86_64.
Second - only armeabi-v7a.

**Comment by MatiasConTilde** [comment]
Do they appear to you in the fdroid store? I still don't have the update
