### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by grravity** [Telegram-FOSS-Team/Telegram-FOSS#403]
Does Telegram-FOSS exist on Linux (Specifically Arch I guess)? 
If not, is it possible to get it on Linux? It'd be really nice to use.

**Comment by thermatk** [comment]
@grravity Official Telegram Desktop is FOSS and is available in official repos

**Comment by grravity** [comment]
> @grravity Official Telegram Desktop is FOSS and is available in official repos

Was not aware of this, is this a Linux only thing? Or does it apply to Windows too out of curiosity?
Telegram's mobile app isn't FOSS, so I don't understand why their desktop app would be?

**Comment by thermatk** [comment]
All official clients are open source, but not all can be built without some non-free stuff, e.g. the Android one
