### ISSUE TITLE
Connection to 8.8.4.4

### ISSUE THREAD

**Issue by PEPERSO** [Telegram-FOSS-Team/Telegram-FOSS#413]
# Describing issue
Hey there ! I've noticed (using NetMonitor and Blokada from f-droid) that Telegram-foss is connecting to google's DNS at ip adress 8.8.4.4.

# Expected behaviour
Could you please change telegrams connections to some privacy friendly DNS, like dns.watch ?

## Gathered information
I've read that Telegram uses google.ru and dns.google.com to resolve links from the apps, but those services could be replaced by alternatives, don't you think ? 

Hope it will be taken into account, and anyway thank you very much for your work, it is awesome :1st_place_medal: !

**Comment by GithubOwly** [comment]
thats a good idea, we could use a zero log dns server like the ones from blahdns.com or pi-dns.com, they are faster than the servers from dns.watch

**Comment by thermatk** [comment]
There is no dns used as dns and there are no alternatives. Please search for similar issues before opening new ones
