### ISSUE TITLE
Enable 'Ignore Content Restrictions'.

### ISSUE THREAD

**Issue by vdbhb59** [Telegram-FOSS-Team/Telegram-FOSS#414]
Just like TGX ('Settings' > 'Interface') and others, would it be possible to enable 'Ignore Content Restrictions' option?

**Comment by DI555** [comment]
and also switch please, 'settings'->'privacy and security'  ''Show Sensitive Content'', if only its both are not the same ;).

**Comment by DI555** [comment]
imho that 'Ignore Content Restrictons' and 'Show Sensitive Content' are the numero uno awaited switches now. Any black walls.. it's not for the telegram !!!
