### ISSUE TITLE
[Feature Request] Auto-Remove Exif Data, Auto-Rename

### ISSUE THREAD

**Issue by grravity** [Telegram-FOSS-Team/Telegram-FOSS#429]
Suggestintg the ability to auto-remove exif data to uploaded images, and rename the files to a random seed.

**Comment by varistov** [comment]
Telegram already removes EXIF data when you send it as an image. But not when you send it as a file. Use [Scrambled EXIF](https://f-droid.org/en/packages/com.jarsilio.android.scrambledeggsif) or [Imagepipe](https://f-droid.org/en/packages/de.kaffeemitkoffein.imagepipe/)
