### ISSUE TITLE
Options to use system emoji

### ISSUE THREAD

**Issue by tosziro** [Telegram-FOSS-Team/Telegram-FOSS#430]
Hello, could you please guys add options to use system emoji? Its irritating, emojis are difrent when you select it than actually show in messages.

**Comment by samyak039** [comment]
yes, this would be great..!!! as we can change the system emoji (after root) hence can use any emoji

**Comment by kojid0** [comment]
Would Telegram FOSS be able to allow users to display standard Apple emoji? Or is it something that F-Droid marks as Anti-Feature? Twemoji is the only thing keeping me back from using FOSS version - I really dislike them...

**Comment by hynet-mel** [comment]
I am aware NekoX allows it, hence why I use it.  Should be *relatively* easy to port over
I personally use Mutant Tech emojis everywhere, so being able to have TG-FOSS to adopt the system emojis (or a toggle for it in the settings) could actually be kinda neat.

**Comment by thermatk** [comment]
@hynet-mel We have no idea about licensing behind Apple's emojis, so we have to replace them with something understandable. System emojis are a valid option, but for now I manage to rebuild and replace assets which is cleaner and better. System emojis don't cover full set of Unicode version Whatever, so it can lead to unexpected problems

Telegram-FOSS is not a feature fork, its goal is to make original app libre with least intrusion and if possible rebuild missing functions with libre dependencies. But it can be a base for a feature fork. 

If you like Apple's emojis, just revert the commit replacing them. There is a reason I'm always trying to rebase in the most evident way possible

**Comment by samyak039** [comment]
I wonder why don't the TG developers themselves add emoji options, it's everywhere (TGX, TG-Desktop) except TG-Android.
