### ISSUE TITLE
Duplicated versions on F-Droid

### ISSUE THREAD

**Issue by Porrumentzio** [Telegram-FOSS-Team/Telegram-FOSS#434]
Is a lot time that there are two packages for each version of Telegram FOSS on F-Droid. 

![Screenshot with Telegram FOSS duplicated versions on F-Droid](https://user-images.githubusercontent.com/61913683/89729467-42add880-da36-11ea-8186-4e6900bf4755.png)

https://f-droid.org/en/packages/org.telegram.messenger/

**Comment by anupritaisno1** [comment]
The other one is for older devices. There's actually more than 2 releases but fdroid only shows the compatible releases

**Comment by Porrumentzio** [comment]
You mean that the two 6.3.0 stand for different versions? And same for the two 6.2.0, 6.1.0...?

**Comment by anupritaisno1** [comment]
They are for different devices

**Comment by Porrumentzio** [comment]
Okay, understood. Thanks!

**Comment by rustforfuture** [comment]
> Okay, understood. Thanks!

The architecture of cpu of the app is different.

This is exist to avoid merging them in a dat apk so reducing space that telegram foss needs.

Many apps do this.
