### ISSUE TITLE
[Feature Request] Manual read notifications

### ISSUE THREAD

**Issue by chrisfahr** [Telegram-FOSS-Team/Telegram-FOSS#444]
An option to disable automatic read notifications (the double checkmark) for messages would be great,
so that you either mark messages on the next answer or by tapping on them.
Reasons you might want this:
- You care about privacy and dont want people to know when you open stuff.
- Sometimes you dont want to answer someone straight away, it would be nice to be able to still read the message though without making them feel bad.
- Not exactly the notification to the other person itself: You use the new message marking to keep track what you still have to answer.

**Comment by thermatk** [comment]
This is strictly forbidden by ToS and not in scope of this fork
