### ISSUE TITLE
F-Droid repo update

### ISSUE THREAD

**Issue by joeftiger** [Telegram-FOSS-Team/Telegram-FOSS#445]
Hello dear team

Is it possible to update the apk on F-Droid? I am currently downloading from this repo's release channel. 
If not possible due to not enough time etc., I am interested in maintaining F-Droid, since especially the 7.0 update is very welcome to other people as well.
Thank you

**Comment by anupritaisno1** [comment]
Download it from the releases page. The package name is different

**Comment by joeftiger** [comment]
Yes, I know. 
But other people only relying on F-Droid are not. 
I am not thinking about how I download/install it, but how others will do.

**Comment by anupritaisno1** [comment]
No need to be concerned about "others" here

Open an issue with fdroid, not here

**Comment by thermatk** [comment]
It will come soon, the apks have been built :+1:
