### ISSUE TITLE
[FeatureRequest] Add support for listening to shoutcast radio for the embedded audio player

### ISSUE THREAD

**Issue by msin87** [Telegram-FOSS-Team/Telegram-FOSS#453]
This will create radio channels through which people can broadcast their music, send music to the radio channel, order advertisements, create live radio broadcasts, and much more. After all, this is not difficult. The addition of this functionality will make Telegram even more popular.
I've been waiting for this functionality for two years now.

**Comment by fcore117** [comment]
This should be separate radio app not integrated into Telegram as there is lot of persons who want Telegram to be pure communication and collaboration app without any extra bloat. Perhaps as a optional plugin or something that do not distract others.

**Comment by msin87** [comment]
> 
> 
> This should be separate radio app not integrated into Telegram as there is lot of persons who want Telegram to be pure communication and collaboration app without any extra bloat. Perhaps as a optional plugin or something that do not distract others.

But Telegram already supports Game API, purchases and sales, and a number of other options that make Telegram not just a messenger, but a very interesting platform. Telegram allows you to download music through bots. Telegram allows you to download videos through bots. It is no longer just a FIDO-style messenger.
Adding support (client) for radio broadcasting to the built-in player will not affect the visual component of the application in any way. Those who do not need radio - they will not even guess about the possibility of listening to radio broadcasts. And radio broadcasting is a means of transmitting information. A tool that can be accessed live simultaneously by multiple users.
For example, now I have to listen to YouTube radio channels (like https://www.youtube.com/watch?v=9dxxWnYlX_A) through FireFox with a bunch of plugins that allow me to do this with the screen off and without ads. So why not give people the opportunity to do the same, only via telegram? It can be just public radio channels, political, radio channels with news from the gaming industry, with news of science and technology. And all this is in the telegram, surrounded by Bot API. At the same time, it is possible to influence the broadcast by voting, send your written songs on the air, see the direct reaction of people to all this. This is very wonderful and amazing!

**Comment by thermatk** [comment]
Yes no maybe But it's not something to do in this fork anyway
