### ISSUE TITLE
Update to 7.1.3

### ISSUE THREAD

**Issue by MadFatVlad** [Telegram-FOSS-Team/Telegram-FOSS#456]
A new Telegram version with channel posts comments [has been](https://github.com/DrKLO/Telegram/releases/tag/release-7.1.3_2100) released!

**Comment by e-edgren** [comment]
Yepp. When will Telegram FOSS be updated to v7.1.3?

**Comment by DI555** [comment]
WIR)

**Comment by Fogapod** [comment]
7.1.3 is listed in changelog, but not published to F-Droid for some reason. Is it not ready yet or publishing new version takes a few weeks?

**Comment by DI555** [comment]
imo it's fdroid bugging((..

**Comment by martinszy** [comment]
Please!? Can someone check what is going on with the build process?

**Comment by r4sas** [comment]
See https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7551

**Comment by r4sas** [comment]
I think that can be closed now.
/cc @thermatk

**Comment by DI555** [comment]
sources v7.2.1 are announced ;)
