### ISSUE TITLE
Unable to login with QR code

### ISSUE THREAD

**Issue by codebam** [Telegram-FOSS-Team/Telegram-FOSS#469]
According to the login page I should go to `Settings -> Devices -> Scan QR` to login using a QR code however the option is not present in the Telegram FOSS app

**Comment by r4sas** [comment]
That functional dropped with Google Vision support:
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/commit/a46fb6d17cbd7c1523ed03d82b57b80a065784fa

**Comment by codebam** [comment]
Oh okay, thanks for the response

**Comment by trysten** [comment]
IMO this is still an issue. Users expect to use QR code login, and it would be nice to have for that reason. I'm not familiar with this project, so forgive me ignorance: Why? Why did you do a46fb6d? There's no explanation in the Changelog, issues, or the commit itself. Why is there no explanation?

Unless this is wont-fix, I think this issue should be reopened.

**Comment by Younes-L** [comment]
It's explained in the readme

>Removal of non-FOSS, untrustworthy or suspicious binaries or source code and their functionality:
>
> • Google Vision face detection and barcode scanning (Passport)

Also why would users expect to use QR code in tg-foss ?
Tg-foss is not the same as telegram app, and this is one of the differences

**Comment by zk-pre** [comment]
Assuming the QR-code is for logging in, I'd expect a foss replacement like the other features, as there are still maps and push notifications.

**Comment by jomo** [comment]
I suggest using [zxing](https://github.com/zxing/zxing) as a Google Vision replacement, or opening an external barcode scanning app. zxing seems to be included in TG-FOSS already, but apparently not used here?

The login QR codes use a URL of the format `tg://login?token=<base64>`. They can't be used by opening them as a link though, that just shows a warning (which is a good security measure and shouldn't be changed IMO)

**Comment by bingoxo** [comment]
please re-open the issue as a solution hasn't been implemented yet

**Comment by iminto** [comment]
> It's explained in the readme
> 
> > Removal of non-FOSS, untrustworthy or suspicious binaries or source code and their functionality:
> > • Google Vision face detection and barcode scanning (Passport)
> 
> Also why would users expect to use QR code in tg-foss ?
> Tg-foss is not the same as telegram app, and this is one of the differences

In some countries, such as China, mobile phone numbers are required to be authenticated with real names, and messages from Telegram cannot be received, even if you use a VPN.If the QR code feature is disabled, it will cause some problems and security concerns when logging into new devices.

So，QR code is necessary.

**Comment by cooldeboy** [comment]
> It's explained in the readme
> 
> > Removal of non-FOSS, untrustworthy or suspicious binaries or source code and their functionality:
> > • Google Vision face detection and barcode scanning (Passport)
> 
> Also why would users expect to use QR code in tg-foss ?
> Tg-foss is not the same as telegram app, and this is one of the differences

In socialist country , such as All we know, mobile phone numbers are required to be authenticated with real names and identity, and SMS from Telegram cannot be received, even you use a VPN.

If the QR code feature is disabled, it will cause some problems and security concerns when logging into new devices

**Comment by timonoj** [comment]
There's PLENTY of FOSS libraries for QR scanning. 
https://github.com/markusfisch/BinaryEye
https://github.com/dmitriy-ilchenko/QrAndBarcodeScanner
https://github.com/AndreMiras/QrScan
https://github.com/zxing/zxing
....
The list keeps going. All these are published no F-Droid. How much would it cost to just launch an intent to a QR-reading app? I don't think you'd even need to have full integration for this.

**Comment by m-alice** [comment]
Telegram Desktop 3.0.1 keeps demand qr code
![2021-09-11_11-09-23](https://user-images.githubusercontent.com/7101860/132941272-15aa5818-374d-4a62-a1cc-dd748bfd1f94.png)
When i use Barcode Scanner from ZXing 4.7.8, it redirect me to Telegram and i see it
![Screenshot_Telegram_FOSS_20210911-111412](https://user-images.githubusercontent.com/7101860/132941518-9f0ee0af-57bb-41ec-a961-6738905dcde8.png)
And, my version of Telegram Android 8.0.0 does not have the right menu item
![Screenshot_Telegram_FOSS_20210911-112159](https://user-images.githubusercontent.com/7101860/132941653-65c8b2c2-d506-4850-ae6d-b919cec7494d.png)
What next?

**Comment by Younes-L** [comment]
> Telegram Desktop 3.0.1 keeps demand qr code

QR code is one of two login options, tdesktop isn't forcing you to use qr code

> What next?

click "log in using phone number" at the bottom then proceed @m-alice 
![2021-09-11_11-09-23](https://user-images.githubusercontent.com/7101860/132941272-15aa5818-374d-4a62-a1cc-dd748bfd1f94.png)

**Comment by m-alice** [comment]
> using phone number
Dear friend, i'm still waiting for SMS-Code for a whole hour.
I do not say that using SMS login is a security blow.
As a solution, i used a fork, Nekogram X - there is all right with the menu item

**Comment by timonoj** [comment]
> 
> 
> > Telegram Desktop 3.0.1 keeps demand qr code
> 
> QR code is one of two login options, tdesktop isn't forcing you to use qr code
> 
> > What next?
> 
> click "log in using phone number" at the bottom then proceed @m-alice
> ![2021-09-11_11-09-23](https://user-images.githubusercontent.com/7101860/132941272-15aa5818-374d-4a62-a1cc-dd748bfd1f94.png)

Please don't justify the lack of a functionality with different options that the non-FOSS also gets. This is lacking a possibly fundamental option for people that don't want to disclose their phone number in their country. So now they get to choose which kind of privacy they prefer? The closed-code one with possible tracking, or the one that can be dangerous to your own person?
It seems such an easy solution is available, with plenty of alternatives already available. Why isn't it added to the code? Just a lazy intent? Why gimp the functionality?

**Comment by gnusuari0** [comment]
If someone replaces Telegram's QR library with a libre library, would you merge that change?

**Comment by Elinvention** [comment]
I felt a bit lost when Telegram Desktop asked me to scan a QR Code and I couldn't find it.

I though I must be stupid that I can't follow basic instructions. I got angry. My stress level increased. That's no good for my health. So here I am asking to add a simple text stating that the functionality is not available in Telegram-FOSS.

**Comment by alfianrehanusa** [comment]
> I felt a bit lost when Telegram Desktop asked me to scan a QR Code and I couldn't find it.
> 
> I though I must be stupid that I can't follow basic instructions. I got angry. My stress level increased. That's no good for my health. So here I am asking to add a simple text stating that the functionality is not available in Telegram-FOSS.

Actually I waste my time for searching this, and search in google instead :(

**Comment by paucazou** [comment]
Same problem with me : no sms, no message sent to telegram app, and QR code doesn't work... I just can't log in the desktop app.

**Comment by tangodev** [comment]
This is an issue. Why? Because **it's making Telegram look unprofessional.**

Not a long time ago I was helping someone with Telegram and I was utterly puzzled as to why they didn't see the `Scan QR` option. I assumed they were running an outdated version.

Fast forward to today and I'm having the same issue. "Is my client outdated? Is there something wrong with my phone?". This was a waste of time. And I also felt dumb "Why can't I find a button that's supposed to be **THERE**?!".

Less tech savvy users will never figure this out. They don't understand Google services and the Play Store. **They deserve to have their privacy respected, but they also deserve feature parity and the same UX.**

**Therefore, the issue is far from "closed".**

**Comment by r4sas** [comment]
@thermatk, I think we need bounty source for such situations, where somebody want's something for free when project adressing other problems.

**Comment by thermatk** [comment]
@r4sas I don't think we need bountysource, as QR codes are literally the only remaining functionality not on par with upstream as of now, considering we recently got back the heavy stuff like x86 builds

Also, the QR login supposedly works in NekoX, so the NekoX patches just need a backport at this point :)
but last time I looked it was a bit scattered across multiple commits

**Comment by thermatk** [comment]
QR login seems to be a server side switch (qr_login_camera):
https://core.telegram.org/api/config

Flipping the switch here to true makes it work:
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/f1ff2b493a529813cea50ed5af235f0763a1bc4f/TMessagesProj/src/main/java/org/telegram/ui/SessionsActivity.java#L649

that's a surprise :raised_eyebrow:

**Comment by r4sas** [comment]
I tried that already (but only with commenting out `&& getMessagesController().qrLoginCamera` part), but that didn't make it work on local build...

**Comment by Frikster** [comment]
> That functional dropped with Google Vision support: [a46fb6d](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/commit/a46fb6d17cbd7c1523ed03d82b57b80a065784fa)

If logging in by QR code was dropped then the bug is that the instructions still tell us that using a QR code is an option. There is still a bug. The QR instructions should be removed because they no longer work.

**Comment by m-alice** [comment]
Seems to be Neko 8.5.1 drop QR support too. NekoX 7.8.0 scans fine.

**Comment by thermatk** [comment]
set up Bountysource ASAP, because next version will have QR code login :rofl:

**Comment by tangodev** [comment]
> set up Bountysource ASAP, because next version will have QR code login rofl

Please specify what you mean. QR **only** login? Do I understand correctly?

**Comment by Frikster** [comment]
> Please specify what you mean. QR only login? Do I understand correctly?

I think he means set up a Bountysource to remove the QR code instructions and I think he is laughing because of how trivial such a fix should be, yet still a problem

**Comment by amlaku** [comment]
I have signed in before 1 weeks ago in my desktop but know I can't login by my phone number without qr code
 so I can't scan it please help me

**Comment by EugeneEliot** [comment]
When I turn on the camera <in the setting-device>to scan the QR code, there is no response. what's the matter?
