### ISSUE TITLE
Extreme amount of user data stored

### ISSUE THREAD

**Issue by puppykickr** [Telegram-FOSS-Team/Telegram-FOSS#473]
It seems that with the latest version, there is a much larger amount of 'user data' stored-  so much so that Telegram is now the largest app on my device.

Whatever this data is, I cannot find it in the usual ways, as it is not in the cache or accessible via a file manager.

OS:  8.1.0
Device:  Poblano Hot Pepper
App Version:  7.2.1

![Screenshot_2020-12-10_10-15-38](https://user-images.githubusercontent.com/44860287/101798574-d371ef00-3ad0-11eb-9aba-876ffa70dddc.jpg)

**Comment by Flam3z** [comment]
Settings -> data & storage

Then you'll see the type of media that is being cached due to you viewing/possibly downloading it to view. Hope this helps.

**Comment by Younes-L** [comment]
Check the logs and cached thumbnails here
`/sdcard/Android/data/org.telegram.messenger.beta/`
Or
`/sdcard/Android/data/org.telegram.messenger/`

**Comment by puppykickr** [comment]
Like I stated, I have checked all of the available storage areas.

I havecleared everything thatcan be cleared, and yet this app is still over 1GB in size.

My only alternative is to clear all data I guess.

**Comment by puppykickr** [comment]
![Screenshot_2020-12-13_14-51-22](https://user-images.githubusercontent.com/44860287/102023723-03c8c000-3d53-11eb-9a82-1e33d06165fa.jpg)

So far so good with previous version

**Comment by enda5377** [comment]
Closed #473.

**Comment by DI555** [comment]
i got over 1.2gb either (((... when was starting subscribing to groups

**Comment by c33s** [comment]
@DI555 just in case you missed it: have you already checked you settings?

groups cache the content you download from them. if you are subscibed to many groups with videos or pictures the cache starts to grow.

to reduce the place on you phone you can reduce to time the items should be stored.
- settings > data and storage > storage usage > keep media: 3days  (if you go to the smallest timeframe you can reduce the increase of the cache size. there you can also clear the telegram cache or the local database)
- settings > data and storage > automatic media download: disable autodownload to only download videos/photos/files you click on

**Comment by DI555** [comment]
1.·all media is cleared
2.·disabled
:(

**Comment by DI555** [comment]
so, the telegram 'storage usage' shows me that i have 550mb base...
but system manager shows that 1200mb got eaten for profile data((..

**Comment by DI555** [comment]
fragmentation?

**Comment by Younes-L** [comment]
@puppykickr @DI555 there seems to be a bug with clearing user data in upstream 7.2.x
If you need to clear data frequently wait for 7.3

**Comment by puppykickr** [comment]
Currently this issue has returned even when using another device.

![Screenshot_2021-01-10_13-07-24](https://user-images.githubusercontent.com/44860287/104132954-3b248f80-5346-11eb-950d-ee7399c4eb14.jpg)

Cannot use any version beyond 7.1.3 unless I want Telegram to be the largest app on any device used.

The features added after version 7.1.3 do not validate using any further versions that store so much data.

The idea that it is now occurring on multiple devices of different Android versions tells me that this is not a device specific issue.

I will now be downgrading back to 7.1.3 on all of my devices.

**Comment by puppykickr** [comment]
Going through all storage areas available, I took these screenshots just before I am about to downgrade to 7.1.3

![Screenshot_2021-01-10_13-22-55](https://user-images.githubusercontent.com/44860287/104133198-999e3d80-5347-11eb-9a5b-fb3b24ed8135.jpg)
![Screenshot_2021-01-10_13-23-21](https://user-images.githubusercontent.com/44860287/104133206-a3c03c00-5347-11eb-82b2-fd06ce9629f5.jpg)
![Screenshot_2021-01-10_13-25-40](https://user-images.githubusercontent.com/44860287/104133209-ae7ad100-5347-11eb-82f6-fb1a5de24064.jpg)

**Comment by puppykickr** [comment]
Ok.
So I checked on F-Droid, and it showed that there was an update available to gk to version 7.3.1

I did the update, started the app, and then went back to check the storage used.

It is now ~100 MB.

So I will be keeping a close eye on this to see if the issue persists.

As for now, I will leave my other devices on version 7.1.3 just in case.

**Comment by thermatk** [comment]
Fixed upstream
