### ISSUE TITLE
Update To Version 7.3

### ISSUE THREAD

**Issue by TakuyaSama** [Telegram-FOSS-Team/Telegram-FOSS#477]
Telegram was just updated to 7.3 recently, so whenever you can, it'd be terrific to start the update process of Telegram FOSS 😀😀.
Always thankful of your great work.
Hoping and desiring you the best, you're doing fine and are fine and healthy, you and your beloved ones.
Have a great holydays, rest well and charge the batteries.
I send you a huge, sincere, warm & virtual hug.

**Comment by TheComputerGuy96** [comment]
@TakuyaSama I have already made a 7.3.0 version of Telegram FOSS

Here's the repository: https://github.com/TheComputerGuy96/Telegram-FOSS

**Comment by roxchgt** [comment]
@TakuyaSama how about creating a Pull Request?
