### ISSUE TITLE
Periodic (~2days) large burst of connection attempts to 196.55.215.129.  

### ISSUE THREAD

**Issue by Okijames** [Telegram-FOSS-Team/Telegram-FOSS#490]
The FOSS Android client periodically tries to reach 196.55.215.129 very aggressively, >35K attempts in a single day. This is being blocked by my firewall, but why is this happening?  The IP seems to be in Africa?  Quite suspicious.

**Comment by iljaguzik** [comment]
Good Day/aftern. sir/mom, do you have any connection to fair mail-script..?

**Comment by CDanilo25** [comment]
Same situation. My router is blocking this IP a thousands of times a day and it's caused by the Telegram apps.

**Comment by sschueller** [comment]
More regarding the Issue: https://forum.netgate.com/topic/160121/pfb_pri1_v4-too-many-alerts-out-for-196-55-215-129-443-5222/14

**Comment by catfluoride** [comment]
Any news on this?

**Comment by CDanilo25** [comment]
> Any news on this?

The notifications stopped for me some days ago.

**Comment by Okijames** [comment]
Last attempts I see are from Feb 5th.  So guessing we might see a bunch sometime today (Feb 7th) but who knows.

**Comment by wiesel24** [comment]
For me to.....196000 attempts are logged on my blocklist. What is that?

**Comment by WPFilmmaker** [comment]
is there an easy way for users to check this from their phone?

**Comment by ioctl-user** [comment]
> is there an easy way for users to check this from their phone?

In general, you can use local VPN feature or rooted phone with some traffic monitor application.

**Comment by KhazAkar** [comment]
Any updates on this?

**Comment by thermatk** [comment]
I don't understand why Telegram app connecting to a Telegram DC is suspicious or needs comments, but I guess I'll just close it :+1:
