### ISSUE TITLE
Telegram FOSS version 7.4.2 on F-Droid soon?

### ISSUE THREAD

**Issue by ghost** [Telegram-FOSS-Team/Telegram-FOSS#492]
Is there coming an updated Telegram FOSS version on F-Droid soon? I am running 7.3.1 and saw that Google Play has an updated version 7.4.2?

**Comment by LibreFoss** [comment]
Keep calm and wait it takes time is humans to do the work...

**Comment by thermatk** [comment]
It's released and merged, just waiting on fdroid to build it

вс, 7 февр. 2021 г., 00:31 theappuser <notifications@github.com>:

**Comment by theappuser** [comment]
OK. I wasn't sure if it was F-Droid or not. I was tempted to just download from Google Play but not sure if it is really the same thing. I know the signature would be different. I like to wait for F-Droid apps so I can easily update them with the same signature.

**Comment by HemanthJabalpuri** [comment]
Someone tell me why F-droid apk of 7.3.1 is 30mb and Github releases has ~50mb?

**Comment by thermatk** [comment]
@HemanthJabalpuri Beta has both arm64 and armv7, release apks are separate pro architecture

**Comment by thermatk** [comment]
@thermatk Now we know build server is down
https://forum.f-droid.org/t/is-the-build-server-down
Nothing we can do, it will come eventually

**Comment by LibreFoss** [comment]
It's down again
