### ISSUE TITLE
Separate persistent notification

### ISSUE THREAD

**Issue by proletarius101** [Telegram-FOSS-Team/Telegram-FOSS#493]
Although it's reasonable to have a persistent notification to keep background push service alive, it's possible and more ideal to make the persistent notification separate. In such a way, we can turn off the persistent notification (turn of its appearance) while keep the service alive.

**Comment by thermatk** [comment]
Hi
That's exactly what I did, the persistent notification is in a separate notification channel that you should definitely mute and forget about :)

**Comment by proletarius101** [comment]
> Hi
> That's exactly what I did, the persistent notification is in a separate notification channel that you should definitely mute and forget about :)

Thanks for doing that. Then that could be elaborated in the docs (instead of saying "You will then receive the misleading system notification, which may be disabled as well with another long tap." which is confusing, and I only find 1 step in the system) or directly in the persistent notification
