### ISSUE TITLE
disable notification?

### ISSUE THREAD

**Issue by AverytheFurry** [Telegram-FOSS-Team/Telegram-FOSS#502]
Hey, I long pressed the notification and I'm not sure which setting I should use to just hide the placeholder notif. (The one here: https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/master/Notifications.md)
![Screenshot_20210318-194605](https://user-images.githubusercontent.com/47131867/111724649-d17fa080-8822-11eb-8b30-608c69ba213f.png)

**Comment by r4sas** [comment]
Push notifications service. Set its' priority to lowest or disable it.

**Comment by AverytheFurry** [comment]
> Push notifications service. Set its' priority to lowest or disable it.

Didnt realize i could click the left side
