### ISSUE TITLE
FOSS vs original from website

### ISSUE THREAD

**Issue by se7en-x230** [Telegram-FOSS-Team/Telegram-FOSS#508]
I am using your version since a long time but now I came across a video that explains that the play store one is full of "google" ...surprise surprise...but the original from the telegram website is "clean".

Is that correct?

**Comment by stefan-niedermann** [comment]
The list of differences is here: https://github.com/Telegram-FOSS-Team/Telegram-FOSS#changes

**Comment by se7en-x230** [comment]
Thanks I read that 
But that is the difference between foss and the google play store version and not the one on telegrams website.

**Comment by stefan-niedermann** [comment]
I guess the one from the website is identical with the one from the Play Store. But i don't think this is the right place to ask this questions. How should a community driven fork know differences of two apps which are provided by Telegram itself?

I recommend you to directly ask the creator and publisher of the both apps - Telegram: https://telegram.org/faq?setln=en#telegram-support

**Comment by se7en-x230** [comment]
Thanks I will check with them.

For now I assume website version --> play store (adds google stuff) --> telegram-foss (removes google stuff)

**Comment by Younes-L** [comment]
@se7en-x230 website version has the same Google stuff as play store version.
Play store version adds censorship,
Foss version removes Google stuff (and Microsoft stuff, and Apple stuff, and ...)

This is to say, telegram from website is not equivalent to telegram-foss ; if you don't want proprietary blobs from Google and others, the only choices available are telegram-foss and clients based on telegram-foss (like forkgram and nekoX)

**Comment by se7en-x230** [comment]
> @se7en-x230 website version has the same Google stuff as play store version.
> Play store version adds censorship,
> Foss version removes Google stuff (and Microsoft stuff, and Apple stuff, and ...)
> 
> This is to say, telegram from website is not equivalent to telegram-foss ; if you don't want proprietary blobs from Google and others, the only choices available are telegram-foss and clients based on telegram-foss (like forkgram and nekoX)

Thank you for the clear answer.

This is what I was thinking 
I will relay this information to friends who switches to the website version.

Thanks a lot for the help and the project. 🙏🏽🙏🏽🙏🏽

**Comment by thermatk** [comment]
Website build is just a flavor, `standalone`. For now the difference is package name and censorship checks, I'm plugging censorship checks in all the same places :)
