### ISSUE TITLE
Using JobScheduler instead of High Priority notification

### ISSUE THREAD

**Issue by alkino** [Telegram-FOSS-Team/Telegram-FOSS#510]
Hello,
I was reading: https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/master/Notifications.md
That leads to read: https://developer.android.com/about/versions/oreo/background#services

Instead of having a high priority notification, would it be possible to create a JobScheduler to listen to incoming messages?

Regards

**Comment by thermatk** [comment]
Hi!
15 minutes delay is not acceptable for a messenger

**Comment by alkino** [comment]
It seems that it can be around 1sec, isn't?
https://developer.android.com/reference/android/app/job/JobInfo#getIntervalMillis()
