### ISSUE TITLE
Rebuild libvpx yasm binaries for x86/x86_64

### ISSUE THREAD

**Issue by thermatk** [Telegram-FOSS-Team/Telegram-FOSS#516]
Please contribute a build recipe, if you know how to build libvpx yasm binaries for x86 and x86_64

`TMessagesProj/jni/third_party/libvpx/source/libvpx/vpx_dsp/x86/libvpx_x86_64_yasm.a`
`TMessagesProj/jni/third_party/libvpx/source/libvpx/vpx_dsp/x86/libvpx_x86_yasm.a`

**Comment by netsgnut** [comment]
Hi, not a well-versed Android dev here but want to help on this since I really want Telegram FOSS on Android x86.

Stumbled upon [this `PKGBUILD`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=android-x86-64-libvpx) from the AUR. Is something like this relevant? 🤔
