### ISSUE TITLE
What happend to telegram sv?

### ISSUE THREAD

**Issue by NSTAdventure** [Telegram-FOSS-Team/Telegram-FOSS#522]
The heck what happen to telegram server?
Some of media files are unable to downloaded captuing network via PCAP apps and i found some server are error:

App: Telegram FOSS (10242)
Protocol: TCP
Source: 10.215.173.1:38390
Destination: 149.154.165.96:5222
Status: Error
Bytes: 40 B received — 60 B sent
Packets: 1 received — 1 sent
Duration: 31 s
First Seen: 07/30/21 19:58:41.565
Last Seen: 07/30/21 19:59:12.949

Hi there official telegram developer you are not kidding are you? 🥴🥴🥴🥴🥴🥴

**Comment by stefan-niedermann** [comment]
> Hi there official telegram developer 

There is no official telegram developer here at this FOSS fork of the Telegram Android client. :wink: 
Please check the [README.md](https://github.com/Telegram-FOSS-Team/Telegram-FOSS#telegram-foss):
> This is an unofficial, FOSS-friendly fork of the original Telegram App for Android.

<details>
<summary>Link to official project</summary>
The official repository is here: https://github.com/DrKLO/Telegram (with disabled issues, so i suggest you to have a look here: https://telegram.org/faq#telegram-support).
</details>

**Comment by NSTAdventure** [comment]
> > Hi there official telegram developer
> 
> There is no official telegram developer here at this FOSS fork of the Telegram Android client. 😉
> Please check the [README.md](https://github.com/Telegram-FOSS-Team/Telegram-FOSS#telegram-foss):
> 
> > This is an unofficial, FOSS-friendly fork of the original Telegram App for Android.
> 
> Link to official project


OOPS :(
I forgot sorry 


MOOOOOOMMMMMYYYYYYY! 😟😟😟😟😟😟

@stefan-niedermann
