### ISSUE TITLE
No armeabi version

### ISSUE THREAD

**Issue by PascalMaximus** [Telegram-FOSS-Team/Telegram-FOSS#525]
My device is armeabi 
And i can't find a armeabi version anywhere.

**Comment by neuron303** [comment]
On F-Droid there are always arm64-v8a and armeabi-v7a versions published.
https://f-droid.org/en/packages/org.telegram.messenger/
In the F-Droid client you can see that in the versions group on the bottom of the app description.
On the website it does not show, but you will see that each version is duplicated. One of those is eabi, I believe it is always lower one (seems to be built and published first)

**Comment by Computershik73** [comment]
He meant armv6, not armv7a
