### ISSUE TITLE
Please increase multi account limit

### ISSUE THREAD

**Issue by rustforfuture** [Telegram-FOSS-Team/Telegram-FOSS#526]
Hello

May you please increase multi account limit?

I am not asking about unlimited or such numbers that will cause instability to the app but may he something like 10 will be great.

I want to get rid of other telegram clients that are either closed source or also the official one has gcm and appcenter sdks in it and also telegram foss is one of the most stable versions of telegram that i used.

May you please add this option and also forwarding without quote tht i described its use cases in this issue" #405

Thank you very much.
Best regards.

**Comment by kuesji** [comment]
i don't know anything about when you get stability problems but this feature request can be achievable by editing this line.

https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/383835939051f24e40b034581ccdcb772814e221/TMessagesProj/src/main/java/org/telegram/messenger/UserConfig.java#L25

**Comment by rustforfuture** [comment]
> i don't know anything about when you get stability problems but this feature request can be achievable by editing this line.
> 
> https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/383835939051f24e40b034581ccdcb772814e221/TMessagesProj/src/main/java/org/telegram/messenger/UserConfig.java#L25

Probably i wrote it badly.

I have stability problems with other clients and i said because telegram foss is most stable client i tested, please add this feature to it.

Also thank you for your help but I can't And don't know android programming to compile it myself.

Can't telegram foss devs add it to main release (F-Droid)?

Thank you very much

**Comment by kuesji** [comment]
you need to wait response from maintainers for implementing this in foss.
by the way building is easy but you need your own api keys for your own client if you wanna build by yourself.

**Comment by rustforfuture** [comment]
> you need to wait response from maintainers for implementing this in foss.
> by the way building is easy but you need your own api keys for your own client if you wanna build by yourself.

Thank you very much

**Comment by thermatk** [comment]
Hi
it should have been pretty obvious I'm not doing that :) 

we're not diverging, but fork it :+1:
