### ISSUE TITLE
Release 7.9.3 not on f-droid yet

### ISSUE THREAD

**Issue by DaleBCooper** [Telegram-FOSS-Team/Telegram-FOSS#528]
Will this version be included on f-droid soon?

Thanks for your great work!

**Comment by gbschenkel** [comment]
Today was released the version 8.0.0

**Comment by paolobarbolini** [comment]
> Today was released the version 8.0.0

I still don't see it on F-Droid, and 7.8.0 seeems to have a bug with setting the theme

**Comment by gbschenkel** [comment]
> > Today was released the version 8.0.0
> 
> I still don't see it on F-Droid, and 7.8.0 seems to have a bug with setting the theme

I mean the code on the official telegram git repo was released when I posted.
Now it is available in here, on Release area.
But yeah, on F-Droid it yet is not released, I think someone messed with pipeline to send the package to F-Droid.

**Comment by gbschenkel** [comment]
Yeah, the pipeline is broken.
https://gitlab.com/fdroid/fdroiddata/-/pipelines/365223343/builds

**Comment by DaleBCooper** [comment]
At least the build was successful last night:

https://monitor.f-droid.org/builds/log/org.telegram.messenger/24065#site-footer

So please be patient, it will be available soon.
