### ISSUE TITLE
search in CJK languages by character instead of word

### ISSUE THREAD

**Issue by OliverLew** [Telegram-FOSS-Team/Telegram-FOSS#529]
The reason is that cjk language does not have spaces in a sentence. While telegram seems to be searching for strings as words separated by spaces and punctuations, making search in CJK almost useless.

I am not sure if this is the place to request the feature, since this might be a fork focusing on making a FOSS version. But the upstream repo does not open their issues, so I'm trying here, maybe someone is willing to implement it here and send a PR to upstream or vice versa.

**Comment by OliverLew** [comment]
After some research, it seems that the direct reason is the FTS (Full Text Search) does not handle CJK very well (something about tokenizing). Is there anything that can be done on telegram's side?

**Comment by Younes-L** [comment]
As you know, search is handled by telegram's servers, which are not only closed source and centralised but also outside the scope of this project, telegram-foss is a fork of the client-side telegram software.
The issue you reported is currently the most upvoted card in telegram's own bugtracker, you can read the comments or give it another upvote here https://bugs.telegram.org/c/724

**Comment by OliverLew** [comment]
Thanks, that's really helpful! I will close the issue then.
