### ISSUE TITLE
This fork is not adherent to the requirements of the upstream developers.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [Telegram-FOSS-Team/Telegram-FOSS#531]
The requirements are available at http://github.com/DrKLO/Telegram#creating-your-telegram-application, because of the logo of https://github.com/Telegram-FOSS-Team/Telegram-FOSS.

**Comment by thermatk** [comment]
There is a special agreement in place for Telegram-FOSS with upstream.
