### ISSUE TITLE
Suggestion: adjustable video calls quality

### ISSUE THREAD

**Issue by OnlyPlayy** [Telegram-FOSS-Team/Telegram-FOSS#536]
My phone gets very hot and drains battery (20% in 45min, usually I recharge my phone once every two days) when I am talking on Telegram video calls. Probably trying to record everything at 1080p and 60Hz. Sometimes it's okay to show how I live in a new place at 1080p 60Hz, but most of the time I just want to talk and see the interlocutor where 720p and 30Hz would be enough.
I would like to see a button in the video call like: _Limit video quality._

And inside, there are 3 options:
- Video quality (4k, 1080p, 720p, 480p, 320p)
- Refresh rate (60Hz, 30Hz, 15Hz)
- Sound quality (48kbps, 128kbps, 192kbps)

**Comment by r4sas** [comment]
Such suggestions must be posted here: https://bugs.telegram.org/

@thermatk, close please.

**Comment by thermatk** [comment]
True, contact upstream or any of the feature forks 😉

**Comment by OnlyPlayy** [comment]
all right! thanks for info

**Comment by stefan-niedermann** [comment]
Maybe an issue template or a hint in the readme is a good idea?

**Comment by OnlyPlayy** [comment]
https://bugs.telegram.org/c/9673
