### ISSUE TITLE
Draining Battery From Notifications

### ISSUE THREAD

**Issue by HonestAbe7** [Telegram-FOSS-Team/Telegram-FOSS#541]
I did notice the battery on my Android phone drains very quickly if I turn on Telegram notifications. Would love to get notifications if they didn't drain my battery so much. I even had them set on 4 hour intervals. Any suggestions would be helpful!

**Comment by proletarius101** [comment]
See

- https://github.com/Telegram-FOSS-Team/Telegram-FOSS/pull/545
- https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/486
