### ISSUE TITLE
How to disable notification sounds when in do-not-disturb mode

### ISSUE THREAD

**Issue by BWPanda** [Telegram-FOSS-Team/Telegram-FOSS#544]
It seems from my testing that you can either enable notification sounds all the time (overriding DND mode), or not at all.

What I'd like is notification sounds during the day (when DND is off) but no notification sounds at night (when DND is on).

Is that possible?

**Comment by CWJamieson** [comment]
I tested this on both my Samsung S20+ (OS 11) and my Pixel 3 XL (OS 12) and couldn't reproduce the issue. They ring fine when the sound is on and respect DND mode.

Are you still experiencing this? If so, what Device/OS are you on?

**Comment by BWPanda** [comment]
Yep, still experiencing this.

I'm running Telegram-FOSS v8.2.7 (2470) arm64-v8a on Lineage 17.1-20211124-microG-tissot on a Xiaomi Mi A1.

**Comment by Younes-L** [comment]
> Yep, still experiencing this.
> 
> I'm running Telegram-FOSS v8.2.7 (2470) arm64-v8a on Lineage 17.1-20211124-microG-tissot on a Xiaomi Mi A1.

@BWPanda you can go to your system settings > applications > telegram > notifications , and open each notification "category" then turn off Override DnD
![Screenshot_20220103-224622_cropped](https://user-images.githubusercontent.com/23421600/147983974-def34b95-6a4c-4b03-b218-f2836d5918de.png)

If no success, you can go to telegram settings > notifications > open each 3 categories of notifications (private chats/groups/channels) and lower the importance (default is Urgent)

**Comment by BWPanda** [comment]
Thanks @Younes-L. I checked all notification categories in my system settings and all had 'Override DnD' disabled already. I have Telegram's notifications already set to 'High' - this seems to be the lowest setting that actually still notifies you, even when DnD is off. Setting it lower would mean I don't get notification sounds at all...

**Comment by Younes-L** [comment]
@BWPanda in that case something is wrong with your ROM, do ask the unofficial lineageOS maintainer / microG people about it
Or try with telegram app (upstream, from https://telegram.org/android)

**Comment by BWPanda** [comment]
Thanks @Younes-L, I tried installing Telegram X instead, but that had the same issue. That led me to investigate some more, and I found the DND feature for SMS's is now called "SMS, MMS **and messaging apps**" (I'm sure it didn't used to say that). Anyway, seems I can't set DND differently for Telegram and SMS's, so I've just disabled that now.

Sorry for the nuisance.
