### ISSUE TITLE
Fdroid - Polish translation error

### ISSUE THREAD

**Issue by marciniuk** [Telegram-FOSS-Team/Telegram-FOSS#548]
In the first paragraph of the description, at the very end there is the word "opuźnieniem" and it should be "opóźnieniem". This is a spelling mistake, I don't know where I can correct it![IMG_20211101_091332_551.jpg](https://user-images.githubusercontent.com/45925550/139641665-745ad9e1-2302-48b3-b418-90e2eaac6d5c.jpg)

**Comment by ZJaume** [comment]
It is here: https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/master/metadata/pl/description.txt

**Comment by DI555** [comment]
btw, where's 24701 (ARMv7) build on f-droid ???

**Comment by DI555** [comment]
btw, where's 24701 (ARMv7) build on f-droid ???

**Comment by Younes-L** [comment]
@DI555 24701 was only just built yesterday, after 24705. should be published soon (0~2 days)

**Comment by DI555** [comment]
great, 24701, it's done !
Younes-L, thanks!
