### ISSUE TITLE
Emulator detection

### ISSUE THREAD

**Issue by wolverine013** [Telegram-FOSS-Team/Telegram-FOSS#554]
It is related to a problem.

The problem is for self-destructing photos & videos in a personal chat, when you log in ro telegram using a computer it says "please view this message from your phone"
But 

> When you log in to telegram by a android emulator ( i.e. BlueStacks etc.) it shows the self-destructing picture or video you sent and normally like a phone after a particular time it disappears.. but in the meantime you can take your screenshot or screen-recording whatever you want from it

I haven't checked for secret chats 

 By detecting emulators this problem may be solved

**Comment by thermatk** [comment]
You also may just take a picture of your phone's screen using another phone, so we'll have to add OpenCV and use the front camera to recognize people taking pictures.
Hint: the idea of self-destructing pictures is not about being protected from a malicious receiver :)
