### ISSUE TITLE
(Bug) Changing orientation while sharing a photo using the camera exits back to the chat screen

### ISSUE THREAD

**Issue by davidginzbourg** [Telegram-FOSS-Team/Telegram-FOSS#557]
Steps to reproduce:
1. Enter a chat
2. Click the attach button
3. Click the live camera square
4. Rotate phone by 90 degrees

Expected behavior:
The app stays in the camera screen

Actual behavior:
Screen goes back to the chat (same one after doing step no. 1).

Same thing also happens after taking the photo, it should stay in the add text to the photo screen but instead goes back to change on orientation change.

**Comment by ahaneku** [comment]
Perhaps this issue only applies to your phone and OS version, 

I followed steps to reproduce bug on Samsung A22 OS 11 but The app stays in the camera screen after going through the steps

**Comment by davidginzbourg** [comment]
I forgot to close this issue, the bug was gone in the first or two updates that came after I opened this issue. Sorry!
