### ISSUE TITLE
Cant change theme

### ISSUE THREAD

**Issue by H3n-beep** [Telegram-FOSS-Team/Telegram-FOSS#562]
When trying to change theme it reverts back to dark light blue
Android 11
Ver 8.2.7 arm64 -v8a
Video of the bug:
 https://drive.google.com/file/d/19LPeFYc9SbCOG668qkeiZooF5TxvuXUa/view?usp=drivesdk

**Comment by Younes-L** [comment]
This is caused by the auto night mode toggle, turn it off to solve the problem

**Comment by H3n-beep** [comment]
It does work as a work around but a fix would be appreciated

**Comment by Younes-L** [comment]
@H3n-beep this is intended behaviour, as you haven't selected a night theme yet. So the default night theme is used when auto night mode kicks in.
To change that go to Telegram Settings -> Chat Settings , scroll down until you see "Auto-Night Mode" then open it (tap the text, not the toggle).
Next, assuming it is enabled (either scheduled or adaptative), you'll see a "preferred night theme".
Now choose your preferred night theme.

If you do not choose your preferred night theme, the default night theme is dark with blue accents, which will be enabled at night as long as auto night theme is also enabled.
