### ISSUE TITLE
Can I upload to Google Play?

### ISSUE THREAD

**Issue by srhughes89** [Telegram-FOSS-Team/Telegram-FOSS#563]
I have a question. Not sure if this is the right place for it. 

Can a person modify and compile Telegram-FOSS and put it on Google Play? What I am trying to accomplish is one code base and one app for my users whether they are Google Free or not.

**Comment by Younes-L** [comment]
> I have a question. Not sure if this is the right place for it.
> 
> Can a person modify and compile Telegram-FOSS and put it on Google Play? What I am trying to accomplish is one code base and one app for my users whether they are Google Free or not.

this app works for everyone regardless of wether they have google services or not

**Comment by srhughes89** [comment]
I know the app will work for either user but not sure if I can upload to Google Play. I tried uploading to Google Play but I am having an issue. Trying to see if it is a restriction of Telegram-FOSS or another issue I am having. Google is asking for credentials to login for app review.

**Comment by srhughes89** [comment]
May I ask how do I get that? The only way I know how you can login is thru entering your number and you receive a verification code via SMS or thru Telegram.

**Comment by theoware** [comment]
Yes I think thats the only possible way

**Comment by nift4** [comment]
Add Bot Token Login to your app

**Comment by srhughes89** [comment]
> Add Bot Token Login to your app

That worked thanks a lot.
