### ISSUE TITLE
This message is not supported by your version of Telegram. Please update the app to view: https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/master/Update.md

### ISSUE THREAD

**Issue by Scyten** [Telegram-FOSS-Team/Telegram-FOSS#564]
Hi, I have a chat where all messages are displayed like in the title of this issue.

The installed version shows 8.2.7 but if have definitely installed the newest 8.4.2 with success.

**Comment by theoware** [comment]
Are there multiple Telegram Apps on your device?

**Comment by pguimier** [comment]
Same here. I suppose this: you use froid version. The last available version of telegram foss on froid is 8.2.7.
Some channels/groups activated spoilers and reactions features, that are available with 8.4.2 version.

**Comment by Younes-L** [comment]
> Hi, I have a chat where all messages are displayed like in the title of this issue.

Unsupported messages are those with spoiler text formatting, this new feature is currently abused by kids who think it's cool.

> The installed version shows 8.2.7 but if have definitely installed the newest 8.4.2 with success.

if you truly installed 8.4.2 then the version would show 8.4.2, and you wouldn't have this problem of unsupported messages (but you will have other bugs introduced by 8.4.2, if you're willing to do the trade)

**Comment by Scyten** [comment]
@pguimier You are right. I have the f-droid Version installed but this APK is installed as another Telegramapp. That was my problem. Thanks for your time
