### ISSUE TITLE
libvpx

### ISSUE THREAD

**Issue by SupremeBarmaley** [Telegram-FOSS-Team/Telegram-FOSS#569]
I can't build libvpx due to error:
according to config.log
**error: unknown target CPU 'intel'**
when I changed FLAGS -mtune=x86-64 I got another one error:
**Toolchain is unable to link executables**

I'm using virtual box and linux lite for compile the project.
All dependences were installed like Android NDK, go, Ninja.

**Comment by sermart1234** [comment]
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/601
