### ISSUE TITLE
This one's actually for the Simple File Manager team

### ISSUE THREAD

**Issue by Robert987** [Telegram-FOSS-Team/Telegram-FOSS#573]
I'm sorry to post it here but I don't know how to get there.  My problem is not being able to find an option to rename files.  It's not that it doesn't work.  It simply isn't listed.  Also, some ebooks don't offer the option of being opened with different e-readers, just one.  I have more than one and would like the chance to choose which.  I'm pretty sure it's not a case of having the wrong format.  One of them does epub and pdf only, but the other handles pretty much all of them.

**Comment by thermatk** [comment]
:man_shrugging:
