### ISSUE TITLE
QR-reader to add desktop devices disappeard from settings->devices

### ISSUE THREAD

**Issue by ralhei** [Telegram-FOSS-Team/Telegram-FOSS#575]
The `settings -> devices` configuration page used to provide a button for scanning QR codes when connection to Telegram from a desktop device, e.g. from the browser. This option is still available in the Telegram version from the Google Playstore, but not any longer in the FOSS version. Is there any reason why this has disappeared? Thx.

**Comment by r4sas** [comment]
dupe: https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/469.

**Comment by Lord-Valen** [comment]
See also #496.
