### ISSUE TITLE
C-style format-specifier mishandling in search menu

### ISSUE THREAD

**Issue by qontinuum-dev** [Telegram-FOSS-Team/Telegram-FOSS#579]
Hey,

When sending a message containing a `%s`, the format-specifier is replaced by the sender name (as shown on the following screenshot).
It seems it only affects the first one if multiple are sent in a single message.

![2022-02-17-10-39-02](https://user-images.githubusercontent.com/79641156/154448068-22044ca1-ba7a-4785-9540-c44e7cb88393.png)

**Comment by r4sas** [comment]
https://bugs.telegram.org/

**Comment by qontinuum-dev** [comment]
Reported there, thanks
