### ISSUE TITLE
log in issue

### ISSUE THREAD

**Issue by wcatz** [Telegram-FOSS-Team/Telegram-FOSS#592]
I let my sim run out and lost my phone number. Few months back I learned the hard way this app does not have a qr scanner. 

On Linux I can copy the data file to new devices and get into the account

Lost my Telegram account had to make a new one. Lost many contacts because it was not clear to me this functionality was not present.

I recently purchased a M1 pro and would like to get my account on it. Does anyone have a solution for getting into my account? Would I have to get a new sim card then change the number in Telegram or is there a way to copy what I need from Linux to MacOS?

I wish I had realized the lack of qr code scanner or that it was removed? Hard to tell. It has really caused a lot of headache and here I am again.

Please advise, if I need to activate a new sim I guess that is what I have to do. The lack of this feature or no clear warning that you are screwed without a simcard is bad guys

**Comment by thermatk** [comment]
Luckily, the QR scanner is back since then :)

**Comment by wcatz** [comment]
Aw shit, just updated. Thank you!! lol was just trying to deal with add filled texting apps. closing nice work guys!
