### ISSUE TITLE
Edited photos not sent

### ISSUE THREAD

**Issue by guglovich** [Telegram-FOSS-Team/Telegram-FOSS#594]
The edited photos are not being sent. There is also no button in the interface to send compressed photos, only the original are sent.

![изображение](https://user-images.githubusercontent.com/54148165/161622480-4413fe98-7cc7-4475-85ce-421b5e3babab.png)

**Comment by Younes-L** [comment]
you need to grant telegram-foss app permission to read your media/files on android 11+

**Comment by guglovich** [comment]
> you need to grant telegram-foss app permission to read your media/files on android 11+

I know how to use the phone. The advice is too obvious. The problem has long since been solved by myself.

**Comment by Younes-L** [comment]
> The problem has long since been solved by myself.

Then go ahead and close this issue. Leaving it open signifies that you're still waiting for help.

**Comment by guglovich** [comment]
Closed. This error occurs when there is a problem with the media, in my case the memory card. For some reason, Telegram needs the memory to crop and process photos, even if photo saving is disabled.
