### ISSUE TITLE
Play Store Release vs Website Release

### ISSUE THREAD

**Issue by Pilzinsel64** [Telegram-FOSS-Team/Telegram-FOSS#616]
Hello!

Just want to ask on wich version Telegram Foss is based on. Is it based on Telegram from Google Play Store or on the extended version you can directly download on the website?

Play Store - org.telegram.messenger
Website - org.telegram.messenger.web
Foss - org.telegram.messenger

If it based on the Play Store version, would it make sense to use the website version instead? What difference would that make?

**Comment by nift4** [comment]
the source code is the same. telegram foss unlocked the web features

**Comment by Pilzinsel64** [comment]
Alright, thank you very much for your answer! ^^ So I'll close this as solved.
