### ISSUE TITLE
8.9.2 cannot open pdfs

### ISSUE THREAD

**Issue by joeftiger** [Telegram-FOSS-Team/Telegram-FOSS#624]
TG Foss 8.9.2 is suddenly unable to open PDFs after the update.
It keeps saying that there's no app installed to handle `application/pdf` even though there is.

Current workout around is to either 
- downgrade, or
- download the file and open it manually.

**Comment by J4CKED** [comment]
Same for txt files.

**Comment by kuesji** [comment]
log is here when i tried to open file named hmm.txt
```
09-09 14:55:24.540  4164  4199 D tmessages: get file path id=5825608106020703360 dc=4 type=3 path=/storage/emulated/0/Telegram/Telegram Files/hmm.txt
09-09 14:55:24.543  4164  4164 W System.err: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority null.provider
09-09 14:55:24.544  4164  4164 W System.err: 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:662)
09-09 14:55:24.544  4164  4164 W System.err: 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:635)
09-09 14:55:24.544  4164  4164 W System.err: 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:441)
09-09 14:55:24.544  4164  4164 W System.err: 	at org.telegram.messenger.AndroidUtilities.openForView(AndroidUtilities.java:3092)
09-09 14:55:24.544  4164  4164 W System.err: 	at org.telegram.messenger.AndroidUtilities.openForView(AndroidUtilities.java:3124)
09-09 14:55:24.544  4164  4164 W System.err: 	at org.telegram.ui.ChatActivity$ChatActivityAdapter$1.didPressImage(ChatActivity.java:25574)
09-09 14:55:24.544  4164  4164 W System.err: 	at org.telegram.ui.Cells.ChatMessageCell.didClickedImage(ChatMessageCell.java:3223)
09-09 14:55:24.544  4164  4164 W System.err: 	at org.telegram.ui.Cells.ChatMessageCell.checkPhotoImageMotionEvent(ChatMessageCell.java:2193)
09-09 14:55:24.544  4164  4164 W System.err: 	at org.telegram.ui.Cells.ChatMessageCell.onTouchEvent(ChatMessageCell.java:2558)
```

looks like ApplicationLoader.getApplicationId() is returning null at here https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/c54fc9915b3173f5f9ea56ef4d2ac1ac5f51e1a0/TMessagesProj/src/main/java/org/telegram/messenger/AndroidUtilities.java#L3092


so, i guess changing this from null to actual applicationId (`return getPackageName();`) will fix issue https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/f1748240d10a56758a113dd0fad70b35ca75efcf/TMessagesProj/src/main/java/org/telegram/messenger/ApplicationLoader.java#L99


i'm too lazy to send pull request. so, i leave the rest to you @thermatk ¯\_(ツ)_/¯

**Comment by kyak** [comment]
Same

**Comment by thermatk** [comment]
this should fix it, will submit to fdroid now
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/commit/2dc49fa0d9218988f68ccd0bbc6ddd99240ca398
