### ISSUE TITLE
[Privacy concerns] Hardcoded dns servers bypassing user configured ones.

### ISSUE THREAD

**Issue by Shituation** [Telegram-FOSS-Team/Telegram-FOSS#628]
Using Rethink DNS + firewall. I don't like what I see here.

![Screenshot_20220912-144036_RethinkDNS](https://user-images.githubusercontent.com/43975882/189722137-0af8452d-9643-4abd-a0f5-d9a60bf88905.png)
![Screenshot_20220912-144242_RethinkDNS](https://user-images.githubusercontent.com/43975882/189722162-e47f8cd5-1468-4f61-bf31-5090a2f4ec69.png)
![Screenshot_20220912-144250_RethinkDNS](https://user-images.githubusercontent.com/43975882/189722168-b27da1d9-1abe-4fcc-a095-e63996b90b9f.p
![Screenshot_20220912-145248_RethinkDNS](https://user-images.githubusercontent.com/43975882/189723036-80b02916-62a1-4674-9322-b42d3ad5c6c8.png)
ng)

While circumventing censorship is ok, using google dns and general unsecure DNS is not privacy friendly.
Also the app doesn't use end2end encryption by default...

is Telegram is starting to behave like whatsapp?
In my case, blocking any of those ip's completely breaks telegram.

**Comment by RHakurei** [comment]
This is not a Telegram FOSS issue, this is a Telegram issue.  E2E by default is not a feature within Telegram itself, neither are custom DNS servers.  If you do not like it, use another app like Signal or host your own Matrix instance.

Submit it to **bugs.telegram.org**

**Comment by Shituation** [comment]
Will have to switch, since apparently Telegram is not privacy friendly as I thought years ago.
Waiting some of the staff members to address this question/issue and say something about it.

**Comment by thermatk** [comment]
The app doesn't use these DNS servers for anything else like browsing or whatever you are blocking, it is there only for one specific task.
I would understand the issue with it otherwise, but it's not there.

**Comment by Shituation** [comment]
What is that "task" ? because blocking one IP there, block all telegram FOSS from working...

**Comment by thermatk** [comment]
now the failure to work is a more exciting thing, maybe need a try-catch block somewhere. Can you provide a logcat?
#629 then for you if true
