### ISSUE TITLE
Can you add some modified features from other telegram clients?

### ISSUE THREAD

**Issue by Wjxfi** [Telegram-FOSS-Team/Telegram-FOSS#632]
It seems incomplete to me, after BGram. please add some very useful features from BGram. Now I will say only the most important and general ones.
You can add: forwarding messages/photo without author, forwarding with message change, backup as in BGram, account avatar on menu button, exact number of members and views in groups and channels ("2180" instead of "2K"), shadowsocks except common socks5 proxy
 
I'm not asking to add everything. At least some

You don't need to answer that it's a regular foss client of telegram. It is not replaceable because it is open source, unlike other clients. But you put a license that does not allow editing. I can only ask you to add these functions

**Comment by r4sas** [comment]
Telegram-FOSS is a fork of the official Telegram client for Android with changes to provide a non-blob client. There will never be changes that are not in the official application.
