### ISSUE TITLE
[Regression] Rotating the phone while taking a picture throws you back to the chat

### ISSUE THREAD

**Issue by Coder-DG** [Telegram-FOSS-Team/Telegram-FOSS#633]
I'm on Lineage OS `19.1` and Telegram FOSS is on version `8.9.2a`.

I go to any chat, click the attach button, click on the live camera thumbnail, rotate the phone, the app goes back to the chat with the new orientation (any change in orientation does this).

I expect it to change the orientation but remain on the same page/activity and not go back to the chat.

This happened in previous versions (about a year ago) but came back in one of the recent versions (not sure when did it start).

**Comment by J4CKED** [comment]
In my case it works without this problem. Same version of Telegram. Custom Android 12.1.

**Comment by Coder-DG** [comment]
> In my case it works without this problem. Same version of Telegram. Custom Android 12.1.

Are you on build 2757 (saw it at the bottom of the settings menu in the app).

I'm using a OnePlus 8T. Other apps don't have that issue.


How should I proceed with testing it further? What can I try to solve it?

**Comment by J4CKED** [comment]
Same build.

**Comment by Coder-DG** [comment]
Happens upstream, closing. Thanks!
