### ISSUE TITLE
The ability to adjust the quality of voice messages

### ISSUE THREAD

**Issue by bmivzkrp** [Telegram-FOSS-Team/Telegram-FOSS#637]
Dear developers!
Could you implement bitrate, sample rate, and voice message audio format settings in Telegram FOSS?
Recently the quality of voice messages has improved, but it is not always acceptable for me and some other users, because we have to be prepared for the fact that the Internet will be unstable in the future. Therefore, we would like to reduce the size of voice messages, at the expense of poorer quality.
I will be very grateful to you for considering this issue.

**Comment by J4CKED** [comment]
This is impossible. Try asking the developers of the original Telegram.

**Comment by bmivzkrp** [comment]
Unfortunately, I have a very bad experience interacting with the 
developers of the official Telegram.
Ok, I ll close this issue.
