### ISSUE TITLE
New update crash

### ISSUE THREAD

**Issue by HybridZach** [Telegram-FOSS-Team/Telegram-FOSS#642]
The new version (9.1.5) no longer works for me. The moment I open the app on my phone it closes but the fingerprint verification stays. 
I am on Android 12. Is this known?

**Comment by kworr** [comment]
Update fails, Android 11.

**Comment by thermatk** [comment]
Can't confirm on Android 11, but I guess I'll try to stop the release build until later, thanks

**Comment by zetcamp** [comment]
Can confirm that new update fails to start and crash. Android 12.

**Comment by theoware** [comment]
Also crashes for me on a Pixel 6 on stock Android 13. I built the APK on my own and I don't have FP unlock enabled

**Comment by Kneit0r** [comment]
Crash after update, uninstalled, crash after fresh install.
Re-installed v9.0.2 again.
Galaxy s10 android 12.

**Comment by Neucher** [comment]
same for me on aosp a13

**Comment by HybridZach** [comment]
So how can I revert to an older version? Trying to install the older version doesn't seem to downgrade the app.

**Comment by HybridZach** [comment]
Accidentally closed it just now. So how do I revert to an older version. I tried to install an older APK but that didn't downgrade it.

**Comment by theoware** [comment]
On Android you can't downgrade without root and since you don't have the keystore for compiling your own apk you'll have to either wait for a new version or install a older or fixed version.

**Comment by HybridZach** [comment]
I thought as much. I can't uninstall the current version right now sadly. Hopefully the dev will fix this issue soon?

**Comment by HybridZach** [comment]
@Younes-L nope I simply forgot I was using a beta app. I'm perfectly aware beta is expexcted to have bugs.

**Comment by kworr** [comment]
Android 11: v9.1.6 fails to install for me.

**Comment by zetcamp** [comment]
I have no errors with latest 9.1.6 update over 9.0.2. Everything is working fine. Android 12.

**Comment by kworr** [comment]
Android 11: v9.2.2 fails to upgrade over v9.0.2.

**Comment by HybridZach** [comment]
9.2.2 works now for me personally. Android 12 still.
