### ISSUE TITLE
Little trick to make telegram notification icon disappear

### ISSUE THREAD

**Issue by languagemaniac** [Telegram-FOSS-Team/Telegram-FOSS#645]
Hi, I just updated to a custom ROM based on Android 12 (as my phone was stuck on Android 10) and noticed the icon in the notification area and just found out about this issue.

Trying to make it go away, I disabled the notifications for telegram and then enabled them again. (By long pressing the notification and touching the gear icon and then double tapping the first tab). 

By doing this, telegram icon disappears but still the notifications do show up when I receive messages.

In my case it's just a personal choice, as I don't like to have icons in the notification area, but I post this here just in case someone finds it useful.

However, when I reboot the phone, I have to do that again. It would be nice to find an automatic way to do this.

**Comment by sspphheerraa** [comment]
> However, when I reboot the phone, I have to do that again. It would be nice to find an automatic way to do this.

However, when I reboot the phone, I have to do that again.
