### ISSUE TITLE
Please package 9.1.0+ for F-Droid

### ISSUE THREAD

**Issue by rockstorm101** [Telegram-FOSS-Team/Telegram-FOSS#648]
First, thanks a lot for maintaining this fork. It's great, I wish there was more *-FOSS apps.
Some groups stopped working correctly due to the missing topics feature (introduced in 9.1.0 I believe). Since 9.1.6 is already released here, I would ask to please package it for F-Droid so we can get these latest features.
I don't have any experience in developing or packaging on Android but if I can help anyhow please let me know.

**Comment by theoware** [comment]
It's been available for almost a week, can be closed.

**Comment by rockstorm101** [comment]
Confirmed. Version 9.2.2 is now available on F-Droid. Closing this issue. Thanks a lot.
