### ISSUE TITLE
"Empty" voice messages!!!

### ISSUE THREAD

**Issue by MadMez** [Telegram-FOSS-Team/Telegram-FOSS#657]
Hi 🙂

Are some days that in some private chats I am not receiving voice messages but only a message saying 'Vuota', which in Italian translated means 'Empty'.

Can you fix it, please 🙏🏼

**Comment by r4sas** [comment]
https://bugs.telegram.org/

**Comment by PolGZ** [comment]
Same issue on v. 9.2.2 on android 13 Pixel 5

**Comment by ayuinaba** [comment]
Having the same issue with GIF's. Haven't tested the voice messages.
