### ISSUE TITLE
Strong performance problems, App not responding 

### ISSUE THREAD

**Issue by Sparrix** [Telegram-FOSS-Team/Telegram-FOSS#664]
Since updating to 9.3.3 i noticed that telegram foss has often strong performance impacts up to App is not responding/freezing. 

I happens everywhere random in the App, mostly if i click on several Chats, groups or channels and sliding between the folders. 

I tried to delete the Cache and everything else, no change.

I noticed the impacts after a few days of using. Most of the time everything works fine, but there are still often the Performance impacts/freezes.

Android 10, Telegram Foss 9.3.3 (3026) direct Arm64-v8a

**Comment by Sparrix** [comment]
![Screenshot_20230203-152045291 (1)](https://user-images.githubusercontent.com/53318182/216626900-1d4643b0-e7f7-4e29-9b2e-11f045487eba.jpg)

Device: Xiaomi Mi 9T 
OS: Resurrection Remix 8.6.5, a Custom Rom, Android 10

**Comment by myghi63** [comment]
I have the same problem, and it is happening due to a huge memory leak telegram-foss has. This situation has got even worse on the two newest versions to the point that my phone is even restarting by its own

**Comment by kyak** [comment]
I've noticed the same since couple of weeks ago. Pixel 5,  Android 13.

**Comment by Togn3K** [comment]
I've also noticed an HUGE amount of battery drain since the last update. Is it only happening to me?
Motorola moto g 5g plus, android 11.

**Comment by myghi63** [comment]
@Togn3K I am also having the exact same issue! My phone that usually lasts about 3 days away from the wall was lasting about a day, and also frequently rebooting itself at night

**Comment by Sparrix** [comment]
> I've also noticed an HUGE amount of battery drain since the last update. Is it only happening to me? Motorola moto g 5g plus, android 11.

**Comment by wijourdil** [comment]
Same issue for me, after a couple of days, the app begins to be slower and freezes sometimes.
And it get worse with the time, the only thing I can do to "reset" the performance issues is to force stop the app to make the app work normally for a new couple of days.

I have the latest version, on a OnePlus 6 and /e/OS 1.8.1 (android 10 fork)

![Screenshot_20230222-095619_Gestionnaire_de_mise_à_jour.png](https://user-images.githubusercontent.com/12596207/220571240-e492227c-1df8-4697-b0d6-6890b4e19375.png)

**Comment by mgw2013** [comment]
@wijourdil It is always a good idea to reboot the from time to time...

**Comment by wijourdil** [comment]
> @wijourdil It is always a good idea to reboot the from time to time...

It's normal to reboot the phone from time to time, yes for sure !

But it's not a normal behaviour to have to force kill an app once a week to make it work normally again 😬

**Comment by mrtaxi** [comment]
The same problem, Android 11, OnePlus 7 12/256

**Comment by yuukidesu9** [comment]
Same memory leak problem.
Android 11, LegionOS, Redmi Note 9 4G (aka Redmi 10X 4G/merlinx)
