### ISSUE TITLE
Un-fdroid version

### ISSUE THREAD

**Issue by BabyOilJohnson** [Telegram-FOSS-Team/Telegram-FOSS#699]
Release apk that is signed by u, I know there is a version that is dev signed but it has that "beta" thing. So release a version that is reciprocal to fdroid version but with your sign.

**Comment by thermatk** [comment]
As discussed multiple times, this would unnecessarily break too many things while bringing no improvements :) F-Droid builds signed with F-Droid key are the release APKs, beta is not to be used as a daily driver. In case of trust issues, the app is easy to build and sign with private API and signing keys.

**Comment by BabyOilJohnson** [comment]
Thanks for the reply 🙏
Yeah, I have trust issue that's why I asked.
