### ISSUE TITLE
Login feature has stopped working

### ISSUE THREAD

**Issue by aario** [Telegram-FOSS-Team/Telegram-FOSS#701]
Version 10.0.9
Android 13
Galaxy S20
Germany
Downloaded from: https://f-droid.org/en/packages/org.telegram.messenger/
I go to "Your phone number" page
Enter my phone number
Click the right arrow
Click Yes when asks for "Is this the correct number?"
Nothing happens. No error. Nothing. Just a loading icon for less than a second. That's all. Nothing. There is no other way to login. 
All permissions are allowed.
Workaround: Uninstalled and installed version Version 9.7.6 from the same website f-droid.org. The older version works.

**Comment by filipkamenski** [comment]
I have the same issue.

**Comment by filipkamenski** [comment]
I have the same issue.

**Comment by Procsiab** [comment]
I could login with the app version 9.7.6, than I update the app to the latest version 10.0.9. Hope this helps

**Comment by Giuseppe499** [comment]
I have the same issue

**Comment by amiria703** [comment]
Same
Sony Xperia Z1
Android 11 (Unofficial LineageOS)

**Comment by Shay123Shay123** [comment]
Same issue on a google android tablet I was offered a voice call option to a new number. 
Using my old number to reinstall on a new Murens phone says the code is sent to an alternative device without identifying the type of device..
Every other reset, login difficulty realises an alternative route is needed.
So Telegram moves towards Google and a buy out?

**Comment by futuretech6** [comment]
Same
v10.0.9(10/5/23) from F-Droid

**Comment by futuretech6** [comment]
> Same v10.0.9(10/5/23) from F-Droid

v10.0.9(9/25/23) works

**Comment by AJCxZ0** [comment]
Same.

10.0.9 from F-Droid
Android 14 on Pixel 7

Enabled and allowed all requested permissions and radios, put in phone number, clicked right arrow in circle, clicked "Yes" of the tick in a circle to confirm the number and was returned immediately to the **Your phone number** screen.
100% reproducible.

**Comment by thermatk** [comment]
It turns out the patched F-Droid version has an error in the API keys.
Fix incoming with new version

**Comment by thermatk** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13882

**Comment by Shay123Shay123** [comment]
Thanks for the suggestion about the version of F-Droid
However, the problem stems from the login of Telegram not the installation
U was using the latest F-Droid in any case and Telegram was downloaded from the Telegram website?
S

Seamus Crowe
+353 899 82 55 39
+34 649 701 707
+44 797 433 4730 Telegram - No Whatsapp

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
