### ISSUE TITLE
Telegram foss login issue

### ISSUE THREAD

**Issue by anumuraligis** [Telegram-FOSS-Team/Telegram-FOSS#706]
Facing a problem with the telegram Foss version.  I installed the foss version of Telegram from Fdroid on my new mobile phone (Oppo Reno 10 5G). It does not proceed to the next level after entering the country code and mobile number. Whereas the TelegramX from the Play Store is responding properly.. please help

**Comment by thermatk** [comment]
Known issue with the broken security update from fdroid, new version coming any minute now

https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/701
