### ISSUE TITLE
Hide premium features

### ISSUE THREAD

**Issue by SimoLRepo** [Telegram-FOSS-Team/Telegram-FOSS#721]
Hello, Would it be possible to implement an option to hide premium features if the user is using the free version? Thank you.

**Comment by SimoLRepo** [comment]
@thermatk No reply?

**Comment by thermatk** [comment]
This is not a feature fork, no options like this are to be added here :)

**Comment by SimoLRepo** [comment]
> This is not a feature fork, no options like this are to be added here :)

That's actually what I thought too, thanks anyway.
