### ISSUE TITLE
[BUG] NotificationPermissionDialog accidental dismiss logic is backwards

### ISSUE THREAD

**Issue by NinTheNoodle** [Telegram-FOSS-Team/Telegram-FOSS#752]
The logic [here](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/10da5406ed92d30c6add3b25d40b2b3b6995d873/TMessagesProj/src/main/java/org/telegram/ui/NotificationPermissionDialog.java#L167) is backwards and is causing the application to repeatedly ask me to enable notifications.

This current logic is saying to repeat the notification later only if the user did not accidentally dismiss the notification. The notification is also not repeated if they dismissed it within 300 milliseconds of it showing up. I suspect this it is intended to be the other way around.

**Comment by 306bobby-android** [comment]
It looks like the logic is correct, but if the press is under 3 seconds it is considered accidental.

Wait 3 seconds, then decline notifications.

#753  moves it to 1 second

**Comment by NinTheNoodle** [comment]
Thank you for the change. That should help. I must have read it wrong.

The phrasing of `if (!mayBeAccidentalDismiss) {
                askLater();
            }` reads to me as "if the dismissal is not potentially accidental, ask again later", which seemed backwards to me.

I have not downloaded a development build, so I if it works then it works. Thanks.

**Comment by Christia7nccas963bug** [comment]
***@***.***
