### ISSUE TITLE
[FEATURE REQUEST] Use Organic Maps for geo

### ISSUE THREAD

**Issue by khurozov** [Telegram-FOSS-Team/Telegram-FOSS#755]
[Organic Maps](https://github.com/organicmaps/organicmaps) seems quite user-friendly. Is it possible to integrate it?

Or is there a way to choose which OSM app to use?

**Comment by ildar** [comment]
WDYM? Telegram shows geopositions inside itself, no external app is used.
You can't integrate one app into the other.

**Comment by khurozov** [comment]
Sorry, my bad.

Telegram FOSS could find my location at first. After installing OsmAnd it worked. I think it was connected to app like official Telegram. Now I deleted OsmAnd and rechecked, it is working.

Thanks.
